/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui.enums;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum ImGuiNavMoveFlags implements IDLEnum<ImGuiNavMoveFlags> {

    CUSTOM(0),
    None(ImGuiNavMoveFlags_None_NATIVE()),
    LoopX(ImGuiNavMoveFlags_LoopX_NATIVE()),
    LoopY(ImGuiNavMoveFlags_LoopY_NATIVE()),
    WrapX(ImGuiNavMoveFlags_WrapX_NATIVE()),
    WrapY(ImGuiNavMoveFlags_WrapY_NATIVE()),
    WrapMask_(ImGuiNavMoveFlags_WrapMask__NATIVE()),
    AllowCurrentNavId(ImGuiNavMoveFlags_AllowCurrentNavId_NATIVE()),
    AlsoScoreVisibleSet(ImGuiNavMoveFlags_AlsoScoreVisibleSet_NATIVE()),
    ScrollToEdgeY(ImGuiNavMoveFlags_ScrollToEdgeY_NATIVE()),
    Forwarded(ImGuiNavMoveFlags_Forwarded_NATIVE()),
    DebugNoResult(ImGuiNavMoveFlags_DebugNoResult_NATIVE()),
    FocusApi(ImGuiNavMoveFlags_FocusApi_NATIVE()),
    IsTabbing(ImGuiNavMoveFlags_IsTabbing_NATIVE()),
    IsPageMove(ImGuiNavMoveFlags_IsPageMove_NATIVE()),
    Activate(ImGuiNavMoveFlags_Activate_NATIVE()),
    NoSelect(ImGuiNavMoveFlags_NoSelect_NATIVE()),
    NoSetNavCursorVisible(ImGuiNavMoveFlags_NoSetNavCursorVisible_NATIVE()),
    NoClearActiveId(ImGuiNavMoveFlags_NoClearActiveId_NATIVE());

    private int value;

    private ImGuiNavMoveFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiNavMoveFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiNavMoveFlags getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_None;
*/
    private static native int ImGuiNavMoveFlags_None_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_LoopX;
*/
    private static native int ImGuiNavMoveFlags_LoopX_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_LoopY;
*/
    private static native int ImGuiNavMoveFlags_LoopY_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_WrapX;
*/
    private static native int ImGuiNavMoveFlags_WrapX_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_WrapY;
*/
    private static native int ImGuiNavMoveFlags_WrapY_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_WrapMask_;
*/
    private static native int ImGuiNavMoveFlags_WrapMask__NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_AllowCurrentNavId;
*/
    private static native int ImGuiNavMoveFlags_AllowCurrentNavId_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_AlsoScoreVisibleSet;
*/
    private static native int ImGuiNavMoveFlags_AlsoScoreVisibleSet_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_ScrollToEdgeY;
*/
    private static native int ImGuiNavMoveFlags_ScrollToEdgeY_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_Forwarded;
*/
    private static native int ImGuiNavMoveFlags_Forwarded_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_DebugNoResult;
*/
    private static native int ImGuiNavMoveFlags_DebugNoResult_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_FocusApi;
*/
    private static native int ImGuiNavMoveFlags_FocusApi_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_IsTabbing;
*/
    private static native int ImGuiNavMoveFlags_IsTabbing_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_IsPageMove;
*/
    private static native int ImGuiNavMoveFlags_IsPageMove_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_Activate;
*/
    private static native int ImGuiNavMoveFlags_Activate_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_NoSelect;
*/
    private static native int ImGuiNavMoveFlags_NoSelect_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_NoSetNavCursorVisible;
*/
    private static native int ImGuiNavMoveFlags_NoSetNavCursorVisible_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavMoveFlags_NoClearActiveId;
*/
    private static native int ImGuiNavMoveFlags_NoClearActiveId_NATIVE();
}
