/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui.enums;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum ImGuiNavLayer implements IDLEnum<ImGuiNavLayer> {

    CUSTOM(0), Main(ImGuiNavLayer_Main_NATIVE()), Menu(ImGuiNavLayer_Menu_NATIVE()), COUNT(ImGuiNavLayer_COUNT_NATIVE());

    private int value;

    private ImGuiNavLayer(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiNavLayer setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiNavLayer getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavLayer_Main;
*/
    private static native int ImGuiNavLayer_Main_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavLayer_Menu;
*/
    private static native int ImGuiNavLayer_Menu_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiNavLayer_COUNT;
*/
    private static native int ImGuiNavLayer_COUNT_NATIVE();
}
