/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui.enums;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum ImGuiScrollFlags implements IDLEnum<ImGuiScrollFlags> {

    CUSTOM(0),
    None(ImGuiScrollFlags_None_NATIVE()),
    KeepVisibleEdgeX(ImGuiScrollFlags_KeepVisibleEdgeX_NATIVE()),
    KeepVisibleEdgeY(ImGuiScrollFlags_KeepVisibleEdgeY_NATIVE()),
    KeepVisibleCenterX(ImGuiScrollFlags_KeepVisibleCenterX_NATIVE()),
    KeepVisibleCenterY(ImGuiScrollFlags_KeepVisibleCenterY_NATIVE()),
    AlwaysCenterX(ImGuiScrollFlags_AlwaysCenterX_NATIVE()),
    AlwaysCenterY(ImGuiScrollFlags_AlwaysCenterY_NATIVE()),
    NoScrollParent(ImGuiScrollFlags_NoScrollParent_NATIVE()),
    MaskX_(ImGuiScrollFlags_MaskX__NATIVE()),
    MaskY_(ImGuiScrollFlags_MaskY__NATIVE());

    private int value;

    private ImGuiScrollFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiScrollFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiScrollFlags getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)ImGuiScrollFlags_None;
*/
    private static native int ImGuiScrollFlags_None_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiScrollFlags_KeepVisibleEdgeX;
*/
    private static native int ImGuiScrollFlags_KeepVisibleEdgeX_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiScrollFlags_KeepVisibleEdgeY;
*/
    private static native int ImGuiScrollFlags_KeepVisibleEdgeY_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiScrollFlags_KeepVisibleCenterX;
*/
    private static native int ImGuiScrollFlags_KeepVisibleCenterX_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiScrollFlags_KeepVisibleCenterY;
*/
    private static native int ImGuiScrollFlags_KeepVisibleCenterY_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiScrollFlags_AlwaysCenterX;
*/
    private static native int ImGuiScrollFlags_AlwaysCenterX_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiScrollFlags_AlwaysCenterY;
*/
    private static native int ImGuiScrollFlags_AlwaysCenterY_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiScrollFlags_NoScrollParent;
*/
    private static native int ImGuiScrollFlags_NoScrollParent_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiScrollFlags_MaskX_;
*/
    private static native int ImGuiScrollFlags_MaskX__NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiScrollFlags_MaskY_;
*/
    private static native int ImGuiScrollFlags_MaskY__NATIVE();
}
