/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImGuiTabBarFlagsPrivate_ implements NativeEnum<ImGuiTabBarFlagsPrivate_> {

    CUSTOM(0), DockNode(ImGuiTabBarFlags_DockNode_NATIVE()), IsFocused(ImGuiTabBarFlags_IsFocused_NATIVE()), SaveSettings(ImGuiTabBarFlags_SaveSettings_NATIVE());

    private int value;

    private ImGuiTabBarFlagsPrivate_(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiTabBarFlagsPrivate_ setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiTabBarFlagsPrivate_ getCustom() {
        return CUSTOM;
    }

    private static native int ImGuiTabBarFlags_DockNode_NATIVE();

    private static native int ImGuiTabBarFlags_IsFocused_NATIVE();

    private static native int ImGuiTabBarFlags_SaveSettings_NATIVE();
}
