/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui.enums;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum ImGuiTabItemFlagsPrivate_ implements IDLEnum<ImGuiTabItemFlagsPrivate_> {

    CUSTOM(0),
    SectionMask_(ImGuiTabItemFlags_SectionMask__NATIVE()),
    NoCloseButton(ImGuiTabItemFlags_NoCloseButton_NATIVE()),
    Button(ImGuiTabItemFlags_Button_NATIVE()),
    Invisible(ImGuiTabItemFlags_Invisible_NATIVE()),
    Unsorted(ImGuiTabItemFlags_Unsorted_NATIVE());

    private int value;

    private ImGuiTabItemFlagsPrivate_(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiTabItemFlagsPrivate_ setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiTabItemFlagsPrivate_ getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_SectionMask_;
*/
    private static native int ImGuiTabItemFlags_SectionMask__NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_NoCloseButton;
*/
    private static native int ImGuiTabItemFlags_NoCloseButton_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_Button;
*/
    private static native int ImGuiTabItemFlags_Button_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_Invisible;
*/
    private static native int ImGuiTabItemFlags_Invisible_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_Unsorted;
*/
    private static native int ImGuiTabItemFlags_Unsorted_NATIVE();
}
