/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImGuiDragDropFlags implements NativeEnum<ImGuiDragDropFlags> {

    CUSTOM(0),
    None(ImGuiDragDropFlags_None_NATIVE()),
    SourceNoPreviewTooltip(ImGuiDragDropFlags_SourceNoPreviewTooltip_NATIVE()),
    SourceNoDisableHover(ImGuiDragDropFlags_SourceNoDisableHover_NATIVE()),
    SourceNoHoldToOpenOthers(ImGuiDragDropFlags_SourceNoHoldToOpenOthers_NATIVE()),
    SourceAllowNullID(ImGuiDragDropFlags_SourceAllowNullID_NATIVE()),
    SourceExtern(ImGuiDragDropFlags_SourceExtern_NATIVE()),
    PayloadAutoExpire(ImGuiDragDropFlags_PayloadAutoExpire_NATIVE()),
    PayloadNoCrossContext(ImGuiDragDropFlags_PayloadNoCrossContext_NATIVE()),
    PayloadNoCrossProcess(ImGuiDragDropFlags_PayloadNoCrossProcess_NATIVE()),
    AcceptBeforeDelivery(ImGuiDragDropFlags_AcceptBeforeDelivery_NATIVE()),
    AcceptNoDrawDefaultRect(ImGuiDragDropFlags_AcceptNoDrawDefaultRect_NATIVE()),
    AcceptNoPreviewTooltip(ImGuiDragDropFlags_AcceptNoPreviewTooltip_NATIVE()),
    AcceptPeekOnly(ImGuiDragDropFlags_AcceptPeekOnly_NATIVE());

    private int value;

    private ImGuiDragDropFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiDragDropFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiDragDropFlags getCustom() {
        return CUSTOM;
    }

    private static native int ImGuiDragDropFlags_None_NATIVE();

    private static native int ImGuiDragDropFlags_SourceNoPreviewTooltip_NATIVE();

    private static native int ImGuiDragDropFlags_SourceNoDisableHover_NATIVE();

    private static native int ImGuiDragDropFlags_SourceNoHoldToOpenOthers_NATIVE();

    private static native int ImGuiDragDropFlags_SourceAllowNullID_NATIVE();

    private static native int ImGuiDragDropFlags_SourceExtern_NATIVE();

    private static native int ImGuiDragDropFlags_PayloadAutoExpire_NATIVE();

    private static native int ImGuiDragDropFlags_PayloadNoCrossContext_NATIVE();

    private static native int ImGuiDragDropFlags_PayloadNoCrossProcess_NATIVE();

    private static native int ImGuiDragDropFlags_AcceptBeforeDelivery_NATIVE();

    private static native int ImGuiDragDropFlags_AcceptNoDrawDefaultRect_NATIVE();

    private static native int ImGuiDragDropFlags_AcceptNoPreviewTooltip_NATIVE();

    private static native int ImGuiDragDropFlags_AcceptPeekOnly_NATIVE();
}
