/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui.enums;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum ImTextureStatus implements IDLEnum<ImTextureStatus> {

    CUSTOM(0),
    OK(ImTextureStatus_OK_NATIVE()),
    Destroyed(ImTextureStatus_Destroyed_NATIVE()),
    WantCreate(ImTextureStatus_WantCreate_NATIVE()),
    WantUpdates(ImTextureStatus_WantUpdates_NATIVE()),
    WantDestroy(ImTextureStatus_WantDestroy_NATIVE());

    private int value;

    private ImTextureStatus(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImTextureStatus setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImTextureStatus getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)ImTextureStatus_OK;
*/
    private static native int ImTextureStatus_OK_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImTextureStatus_Destroyed;
*/
    private static native int ImTextureStatus_Destroyed_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImTextureStatus_WantCreate;
*/
    private static native int ImTextureStatus_WantCreate_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImTextureStatus_WantUpdates;
*/
    private static native int ImTextureStatus_WantUpdates_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImTextureStatus_WantDestroy;
*/
    private static native int ImTextureStatus_WantDestroy_NATIVE();
}
