/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImGuiWindowRefreshFlags implements NativeEnum<ImGuiWindowRefreshFlags> {

    CUSTOM(0), None(ImGuiWindowRefreshFlags_None_NATIVE()), TryToAvoidRefresh(ImGuiWindowRefreshFlags_TryToAvoidRefresh_NATIVE()), RefreshOnHover(ImGuiWindowRefreshFlags_RefreshOnHover_NATIVE()), RefreshOnFocus(ImGuiWindowRefreshFlags_RefreshOnFocus_NATIVE());

    private int value;

    private ImGuiWindowRefreshFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiWindowRefreshFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiWindowRefreshFlags getCustom() {
        return CUSTOM;
    }

    private static int ImGuiWindowRefreshFlags_None_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiWindowRefreshFlags_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiWindowRefreshFlags_TryToAvoidRefresh_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiWindowRefreshFlags_TryToAvoidRefresh_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiWindowRefreshFlags_RefreshOnHover_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiWindowRefreshFlags_RefreshOnHover_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiWindowRefreshFlags_RefreshOnFocus_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiWindowRefreshFlags_RefreshOnFocus_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle ImGuiWindowRefreshFlags_None_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguiwindowrefreshflags_imguiwindowrefreshflags_none_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiWindowRefreshFlags_TryToAvoidRefresh_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguiwindowrefreshflags_imguiwindowrefreshflags_trytoavoidrefresh_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiWindowRefreshFlags_RefreshOnHover_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguiwindowrefreshflags_imguiwindowrefreshflags_refreshonhover_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiWindowRefreshFlags_RefreshOnFocus_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguiwindowrefreshflags_imguiwindowrefreshflags_refreshonfocus_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
