/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImGuiDataTypePrivate_ implements NativeEnum<ImGuiDataTypePrivate_> {

    CUSTOM(0), Pointer(ImGuiDataType_Pointer_NATIVE()), ID(ImGuiDataType_ID_NATIVE());

    private int value;

    private ImGuiDataTypePrivate_(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiDataTypePrivate_ setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiDataTypePrivate_ getCustom() {
        return CUSTOM;
    }

    private static int ImGuiDataType_Pointer_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiDataType_Pointer_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiDataType_ID_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiDataType_ID_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle ImGuiDataType_Pointer_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguidatatypeprivate__imguidatatype_pointer_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiDataType_ID_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguidatatypeprivate__imguidatatype_id_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
