/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImGuiActivateFlags implements NativeEnum<ImGuiActivateFlags> {

    CUSTOM(0),
    None(ImGuiActivateFlags_None_NATIVE()),
    PreferInput(ImGuiActivateFlags_PreferInput_NATIVE()),
    PreferTweak(ImGuiActivateFlags_PreferTweak_NATIVE()),
    TryToPreserveState(ImGuiActivateFlags_TryToPreserveState_NATIVE()),
    FromTabbing(ImGuiActivateFlags_FromTabbing_NATIVE()),
    FromShortcut(ImGuiActivateFlags_FromShortcut_NATIVE()),
    FromFocusApi(ImGuiActivateFlags_FromFocusApi_NATIVE());

    private int value;

    private ImGuiActivateFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiActivateFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiActivateFlags getCustom() {
        return CUSTOM;
    }

    private static int ImGuiActivateFlags_None_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiActivateFlags_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiActivateFlags_PreferInput_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiActivateFlags_PreferInput_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiActivateFlags_PreferTweak_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiActivateFlags_PreferTweak_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiActivateFlags_TryToPreserveState_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiActivateFlags_TryToPreserveState_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiActivateFlags_FromTabbing_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiActivateFlags_FromTabbing_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiActivateFlags_FromShortcut_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiActivateFlags_FromShortcut_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiActivateFlags_FromFocusApi_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiActivateFlags_FromFocusApi_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle ImGuiActivateFlags_None_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguiactivateflags_imguiactivateflags_none_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiActivateFlags_PreferInput_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguiactivateflags_imguiactivateflags_preferinput_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiActivateFlags_PreferTweak_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguiactivateflags_imguiactivateflags_prefertweak_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiActivateFlags_TryToPreserveState_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguiactivateflags_imguiactivateflags_trytopreservestate_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiActivateFlags_FromTabbing_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguiactivateflags_imguiactivateflags_fromtabbing_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiActivateFlags_FromShortcut_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguiactivateflags_imguiactivateflags_fromshortcut_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiActivateFlags_FromFocusApi_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguiactivateflags_imguiactivateflags_fromfocusapi_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
