/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImGuiComboFlags implements NativeEnum<ImGuiComboFlags> {

    CUSTOM(0),
    None(ImGuiComboFlags_None_NATIVE()),
    PopupAlignLeft(ImGuiComboFlags_PopupAlignLeft_NATIVE()),
    HeightSmall(ImGuiComboFlags_HeightSmall_NATIVE()),
    HeightRegular(ImGuiComboFlags_HeightRegular_NATIVE()),
    HeightLarge(ImGuiComboFlags_HeightLarge_NATIVE()),
    HeightLargest(ImGuiComboFlags_HeightLargest_NATIVE()),
    NoArrowButton(ImGuiComboFlags_NoArrowButton_NATIVE()),
    NoPreview(ImGuiComboFlags_NoPreview_NATIVE()),
    WidthFitPreview(ImGuiComboFlags_WidthFitPreview_NATIVE()),
    HeightMask_(ImGuiComboFlags_HeightMask__NATIVE());

    private int value;

    private ImGuiComboFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiComboFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiComboFlags getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiComboFlags_None;
*/
    private static int ImGuiComboFlags_None_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiComboFlags_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiComboFlags_PopupAlignLeft;
*/
    private static int ImGuiComboFlags_PopupAlignLeft_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiComboFlags_PopupAlignLeft_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiComboFlags_HeightSmall;
*/
    private static int ImGuiComboFlags_HeightSmall_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiComboFlags_HeightSmall_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiComboFlags_HeightRegular;
*/
    private static int ImGuiComboFlags_HeightRegular_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiComboFlags_HeightRegular_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiComboFlags_HeightLarge;
*/
    private static int ImGuiComboFlags_HeightLarge_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiComboFlags_HeightLarge_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiComboFlags_HeightLargest;
*/
    private static int ImGuiComboFlags_HeightLargest_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiComboFlags_HeightLargest_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiComboFlags_NoArrowButton;
*/
    private static int ImGuiComboFlags_NoArrowButton_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiComboFlags_NoArrowButton_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiComboFlags_NoPreview;
*/
    private static int ImGuiComboFlags_NoPreview_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiComboFlags_NoPreview_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiComboFlags_WidthFitPreview;
*/
    private static int ImGuiComboFlags_WidthFitPreview_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiComboFlags_WidthFitPreview_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiComboFlags_HeightMask_;
*/
    private static int ImGuiComboFlags_HeightMask__NATIVE() {
        try {
            return (int) FFMHandles.ImGuiComboFlags_HeightMask__NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_CRITICAL = new java.lang.foreign.Linker.Option[] { java.lang.foreign.Linker.Option.critical(true) };

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_DEFAULT = new java.lang.foreign.Linker.Option[0];

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static RuntimeException rethrow(Throwable e) {
            if (e instanceof RuntimeException)
                return (RuntimeException) e;
            if (e instanceof Error)
                throw (Error) e;
            return new RuntimeException(e);
        }

        static java.lang.invoke.MethodHandle downcallDefault(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
        }

        static java.lang.invoke.MethodHandle downcallCritical(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            try {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_CRITICAL);
            } catch (Throwable ignored) {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
            }
        }

        static final java.lang.invoke.MethodHandle ImGuiComboFlags_None_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiComboFlags_ImGuiComboFlags_1None_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiComboFlags_PopupAlignLeft_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiComboFlags_ImGuiComboFlags_1PopupAlignLeft_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiComboFlags_HeightSmall_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiComboFlags_ImGuiComboFlags_1HeightSmall_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiComboFlags_HeightRegular_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiComboFlags_ImGuiComboFlags_1HeightRegular_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiComboFlags_HeightLarge_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiComboFlags_ImGuiComboFlags_1HeightLarge_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiComboFlags_HeightLargest_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiComboFlags_ImGuiComboFlags_1HeightLargest_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiComboFlags_NoArrowButton_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiComboFlags_ImGuiComboFlags_1NoArrowButton_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiComboFlags_NoPreview_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiComboFlags_ImGuiComboFlags_1NoPreview_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiComboFlags_WidthFitPreview_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiComboFlags_ImGuiComboFlags_1WidthFitPreview_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiComboFlags_HeightMask__NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiComboFlags_ImGuiComboFlags_1HeightMask_1_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
