/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImGuiScrollFlags implements NativeEnum<ImGuiScrollFlags> {

    CUSTOM(0),
    None(ImGuiScrollFlags_None_NATIVE()),
    KeepVisibleEdgeX(ImGuiScrollFlags_KeepVisibleEdgeX_NATIVE()),
    KeepVisibleEdgeY(ImGuiScrollFlags_KeepVisibleEdgeY_NATIVE()),
    KeepVisibleCenterX(ImGuiScrollFlags_KeepVisibleCenterX_NATIVE()),
    KeepVisibleCenterY(ImGuiScrollFlags_KeepVisibleCenterY_NATIVE()),
    AlwaysCenterX(ImGuiScrollFlags_AlwaysCenterX_NATIVE()),
    AlwaysCenterY(ImGuiScrollFlags_AlwaysCenterY_NATIVE()),
    NoScrollParent(ImGuiScrollFlags_NoScrollParent_NATIVE()),
    MaskX_(ImGuiScrollFlags_MaskX__NATIVE()),
    MaskY_(ImGuiScrollFlags_MaskY__NATIVE());

    private int value;

    private ImGuiScrollFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiScrollFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiScrollFlags getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiScrollFlags_None;
*/
    private static int ImGuiScrollFlags_None_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiScrollFlags_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiScrollFlags_KeepVisibleEdgeX;
*/
    private static int ImGuiScrollFlags_KeepVisibleEdgeX_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiScrollFlags_KeepVisibleEdgeX_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiScrollFlags_KeepVisibleEdgeY;
*/
    private static int ImGuiScrollFlags_KeepVisibleEdgeY_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiScrollFlags_KeepVisibleEdgeY_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiScrollFlags_KeepVisibleCenterX;
*/
    private static int ImGuiScrollFlags_KeepVisibleCenterX_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiScrollFlags_KeepVisibleCenterX_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiScrollFlags_KeepVisibleCenterY;
*/
    private static int ImGuiScrollFlags_KeepVisibleCenterY_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiScrollFlags_KeepVisibleCenterY_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiScrollFlags_AlwaysCenterX;
*/
    private static int ImGuiScrollFlags_AlwaysCenterX_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiScrollFlags_AlwaysCenterX_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiScrollFlags_AlwaysCenterY;
*/
    private static int ImGuiScrollFlags_AlwaysCenterY_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiScrollFlags_AlwaysCenterY_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiScrollFlags_NoScrollParent;
*/
    private static int ImGuiScrollFlags_NoScrollParent_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiScrollFlags_NoScrollParent_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiScrollFlags_MaskX_;
*/
    private static int ImGuiScrollFlags_MaskX__NATIVE() {
        try {
            return (int) FFMHandles.ImGuiScrollFlags_MaskX__NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiScrollFlags_MaskY_;
*/
    private static int ImGuiScrollFlags_MaskY__NATIVE() {
        try {
            return (int) FFMHandles.ImGuiScrollFlags_MaskY__NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_CRITICAL = new java.lang.foreign.Linker.Option[] { java.lang.foreign.Linker.Option.critical(true) };

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_DEFAULT = new java.lang.foreign.Linker.Option[0];

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static RuntimeException rethrow(Throwable e) {
            if (e instanceof RuntimeException)
                return (RuntimeException) e;
            if (e instanceof Error)
                throw (Error) e;
            return new RuntimeException(e);
        }

        static java.lang.invoke.MethodHandle downcallDefault(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
        }

        static java.lang.invoke.MethodHandle downcallCritical(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            try {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_CRITICAL);
            } catch (Throwable ignored) {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
            }
        }

        static final java.lang.invoke.MethodHandle ImGuiScrollFlags_None_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiScrollFlags_ImGuiScrollFlags_1None_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiScrollFlags_KeepVisibleEdgeX_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiScrollFlags_ImGuiScrollFlags_1KeepVisibleEdgeX_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiScrollFlags_KeepVisibleEdgeY_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiScrollFlags_ImGuiScrollFlags_1KeepVisibleEdgeY_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiScrollFlags_KeepVisibleCenterX_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiScrollFlags_ImGuiScrollFlags_1KeepVisibleCenterX_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiScrollFlags_KeepVisibleCenterY_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiScrollFlags_ImGuiScrollFlags_1KeepVisibleCenterY_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiScrollFlags_AlwaysCenterX_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiScrollFlags_ImGuiScrollFlags_1AlwaysCenterX_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiScrollFlags_AlwaysCenterY_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiScrollFlags_ImGuiScrollFlags_1AlwaysCenterY_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiScrollFlags_NoScrollParent_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiScrollFlags_ImGuiScrollFlags_1NoScrollParent_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiScrollFlags_MaskX__NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiScrollFlags_ImGuiScrollFlags_1MaskX_1_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiScrollFlags_MaskY__NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiScrollFlags_ImGuiScrollFlags_1MaskY_1_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
