/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImGuiViewportFlags implements NativeEnum<ImGuiViewportFlags> {

    CUSTOM(0),
    None(ImGuiViewportFlags_None_NATIVE()),
    IsPlatformWindow(ImGuiViewportFlags_IsPlatformWindow_NATIVE()),
    IsPlatformMonitor(ImGuiViewportFlags_IsPlatformMonitor_NATIVE()),
    OwnedByApp(ImGuiViewportFlags_OwnedByApp_NATIVE()),
    NoDecoration(ImGuiViewportFlags_NoDecoration_NATIVE()),
    NoTaskBarIcon(ImGuiViewportFlags_NoTaskBarIcon_NATIVE()),
    NoFocusOnAppearing(ImGuiViewportFlags_NoFocusOnAppearing_NATIVE()),
    NoFocusOnClick(ImGuiViewportFlags_NoFocusOnClick_NATIVE()),
    NoInputs(ImGuiViewportFlags_NoInputs_NATIVE()),
    NoRendererClear(ImGuiViewportFlags_NoRendererClear_NATIVE()),
    NoAutoMerge(ImGuiViewportFlags_NoAutoMerge_NATIVE()),
    TopMost(ImGuiViewportFlags_TopMost_NATIVE()),
    CanHostOtherWindows(ImGuiViewportFlags_CanHostOtherWindows_NATIVE()),
    IsMinimized(ImGuiViewportFlags_IsMinimized_NATIVE()),
    IsFocused(ImGuiViewportFlags_IsFocused_NATIVE());

    private int value;

    private ImGuiViewportFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiViewportFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiViewportFlags getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_None;
*/
    private static int ImGuiViewportFlags_None_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_IsPlatformWindow;
*/
    private static int ImGuiViewportFlags_IsPlatformWindow_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_IsPlatformWindow_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_IsPlatformMonitor;
*/
    private static int ImGuiViewportFlags_IsPlatformMonitor_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_IsPlatformMonitor_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_OwnedByApp;
*/
    private static int ImGuiViewportFlags_OwnedByApp_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_OwnedByApp_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_NoDecoration;
*/
    private static int ImGuiViewportFlags_NoDecoration_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_NoDecoration_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_NoTaskBarIcon;
*/
    private static int ImGuiViewportFlags_NoTaskBarIcon_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_NoTaskBarIcon_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_NoFocusOnAppearing;
*/
    private static int ImGuiViewportFlags_NoFocusOnAppearing_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_NoFocusOnAppearing_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_NoFocusOnClick;
*/
    private static int ImGuiViewportFlags_NoFocusOnClick_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_NoFocusOnClick_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_NoInputs;
*/
    private static int ImGuiViewportFlags_NoInputs_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_NoInputs_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_NoRendererClear;
*/
    private static int ImGuiViewportFlags_NoRendererClear_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_NoRendererClear_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_NoAutoMerge;
*/
    private static int ImGuiViewportFlags_NoAutoMerge_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_NoAutoMerge_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_TopMost;
*/
    private static int ImGuiViewportFlags_TopMost_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_TopMost_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_CanHostOtherWindows;
*/
    private static int ImGuiViewportFlags_CanHostOtherWindows_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_CanHostOtherWindows_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_IsMinimized;
*/
    private static int ImGuiViewportFlags_IsMinimized_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_IsMinimized_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiViewportFlags_IsFocused;
*/
    private static int ImGuiViewportFlags_IsFocused_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiViewportFlags_IsFocused_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_CRITICAL = new java.lang.foreign.Linker.Option[] { java.lang.foreign.Linker.Option.critical(true) };

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_DEFAULT = new java.lang.foreign.Linker.Option[0];

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static RuntimeException rethrow(Throwable e) {
            if (e instanceof RuntimeException)
                return (RuntimeException) e;
            if (e instanceof Error)
                throw (Error) e;
            return new RuntimeException(e);
        }

        static java.lang.invoke.MethodHandle downcallDefault(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
        }

        static java.lang.invoke.MethodHandle downcallCritical(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            try {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_CRITICAL);
            } catch (Throwable ignored) {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
            }
        }

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_None_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1None_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_IsPlatformWindow_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1IsPlatformWindow_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_IsPlatformMonitor_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1IsPlatformMonitor_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_OwnedByApp_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1OwnedByApp_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_NoDecoration_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1NoDecoration_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_NoTaskBarIcon_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1NoTaskBarIcon_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_NoFocusOnAppearing_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1NoFocusOnAppearing_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_NoFocusOnClick_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1NoFocusOnClick_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_NoInputs_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1NoInputs_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_NoRendererClear_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1NoRendererClear_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_NoAutoMerge_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1NoAutoMerge_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_TopMost_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1TopMost_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_CanHostOtherWindows_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1CanHostOtherWindows_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_IsMinimized_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1IsMinimized_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiViewportFlags_IsFocused_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiViewportFlags_ImGuiViewportFlags_1IsFocused_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
