/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImGuiItemFlagsPrivate_ implements NativeEnum<ImGuiItemFlagsPrivate_> {

    CUSTOM(0),
    Disabled(ImGuiItemFlags_Disabled_NATIVE()),
    ReadOnly(ImGuiItemFlags_ReadOnly_NATIVE()),
    MixedValue(ImGuiItemFlags_MixedValue_NATIVE()),
    NoWindowHoverableCheck(ImGuiItemFlags_NoWindowHoverableCheck_NATIVE()),
    AllowOverlap(ImGuiItemFlags_AllowOverlap_NATIVE()),
    NoNavDisableMouseHover(ImGuiItemFlags_NoNavDisableMouseHover_NATIVE()),
    NoMarkEdited(ImGuiItemFlags_NoMarkEdited_NATIVE()),
    NoFocus(ImGuiItemFlags_NoFocus_NATIVE()),
    Inputable(ImGuiItemFlags_Inputable_NATIVE()),
    HasSelectionUserData(ImGuiItemFlags_HasSelectionUserData_NATIVE()),
    IsMultiSelect(ImGuiItemFlags_IsMultiSelect_NATIVE()),
    Default_(ImGuiItemFlags_Default__NATIVE());

    private int value;

    private ImGuiItemFlagsPrivate_(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiItemFlagsPrivate_ setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiItemFlagsPrivate_ getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_Disabled;
*/
    private static int ImGuiItemFlags_Disabled_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_Disabled_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_ReadOnly;
*/
    private static int ImGuiItemFlags_ReadOnly_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_ReadOnly_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_MixedValue;
*/
    private static int ImGuiItemFlags_MixedValue_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_MixedValue_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_NoWindowHoverableCheck;
*/
    private static int ImGuiItemFlags_NoWindowHoverableCheck_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_NoWindowHoverableCheck_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_AllowOverlap;
*/
    private static int ImGuiItemFlags_AllowOverlap_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_AllowOverlap_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_NoNavDisableMouseHover;
*/
    private static int ImGuiItemFlags_NoNavDisableMouseHover_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_NoNavDisableMouseHover_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_NoMarkEdited;
*/
    private static int ImGuiItemFlags_NoMarkEdited_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_NoMarkEdited_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_NoFocus;
*/
    private static int ImGuiItemFlags_NoFocus_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_NoFocus_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_Inputable;
*/
    private static int ImGuiItemFlags_Inputable_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_Inputable_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_HasSelectionUserData;
*/
    private static int ImGuiItemFlags_HasSelectionUserData_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_HasSelectionUserData_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_IsMultiSelect;
*/
    private static int ImGuiItemFlags_IsMultiSelect_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_IsMultiSelect_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiItemFlags_Default_;
*/
    private static int ImGuiItemFlags_Default__NATIVE() {
        try {
            return (int) FFMHandles.ImGuiItemFlags_Default__NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_CRITICAL = new java.lang.foreign.Linker.Option[] { java.lang.foreign.Linker.Option.critical(true) };

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_DEFAULT = new java.lang.foreign.Linker.Option[0];

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static RuntimeException rethrow(Throwable e) {
            if (e instanceof RuntimeException)
                return (RuntimeException) e;
            if (e instanceof Error)
                throw (Error) e;
            return new RuntimeException(e);
        }

        static java.lang.invoke.MethodHandle downcallDefault(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
        }

        static java.lang.invoke.MethodHandle downcallCritical(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            try {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_CRITICAL);
            } catch (Throwable ignored) {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
            }
        }

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_Disabled_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1Disabled_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_ReadOnly_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1ReadOnly_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_MixedValue_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1MixedValue_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_NoWindowHoverableCheck_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1NoWindowHoverableCheck_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_AllowOverlap_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1AllowOverlap_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_NoNavDisableMouseHover_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1NoNavDisableMouseHover_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_NoMarkEdited_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1NoMarkEdited_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_NoFocus_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1NoFocus_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_Inputable_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1Inputable_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_HasSelectionUserData_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1HasSelectionUserData_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_IsMultiSelect_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1IsMultiSelect_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiItemFlags_Default__NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiItemFlagsPrivate_1_ImGuiItemFlags_1Default_1_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
