/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImGuiTreeNodeFlags implements NativeEnum<ImGuiTreeNodeFlags> {

    CUSTOM(0),
    None(ImGuiTreeNodeFlags_None_NATIVE()),
    Selected(ImGuiTreeNodeFlags_Selected_NATIVE()),
    Framed(ImGuiTreeNodeFlags_Framed_NATIVE()),
    AllowOverlap(ImGuiTreeNodeFlags_AllowOverlap_NATIVE()),
    NoTreePushOnOpen(ImGuiTreeNodeFlags_NoTreePushOnOpen_NATIVE()),
    NoAutoOpenOnLog(ImGuiTreeNodeFlags_NoAutoOpenOnLog_NATIVE()),
    DefaultOpen(ImGuiTreeNodeFlags_DefaultOpen_NATIVE()),
    OpenOnDoubleClick(ImGuiTreeNodeFlags_OpenOnDoubleClick_NATIVE()),
    OpenOnArrow(ImGuiTreeNodeFlags_OpenOnArrow_NATIVE()),
    Leaf(ImGuiTreeNodeFlags_Leaf_NATIVE()),
    Bullet(ImGuiTreeNodeFlags_Bullet_NATIVE()),
    FramePadding(ImGuiTreeNodeFlags_FramePadding_NATIVE()),
    SpanAvailWidth(ImGuiTreeNodeFlags_SpanAvailWidth_NATIVE()),
    SpanFullWidth(ImGuiTreeNodeFlags_SpanFullWidth_NATIVE()),
    SpanLabelWidth(ImGuiTreeNodeFlags_SpanLabelWidth_NATIVE()),
    SpanAllColumns(ImGuiTreeNodeFlags_SpanAllColumns_NATIVE()),
    LabelSpanAllColumns(ImGuiTreeNodeFlags_LabelSpanAllColumns_NATIVE()),
    NavLeftJumpsToParent(ImGuiTreeNodeFlags_NavLeftJumpsToParent_NATIVE()),
    CollapsingHeader(ImGuiTreeNodeFlags_CollapsingHeader_NATIVE()),
    DrawLinesNone(ImGuiTreeNodeFlags_DrawLinesNone_NATIVE()),
    DrawLinesFull(ImGuiTreeNodeFlags_DrawLinesFull_NATIVE()),
    DrawLinesToNodes(ImGuiTreeNodeFlags_DrawLinesToNodes_NATIVE());

    private int value;

    private ImGuiTreeNodeFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiTreeNodeFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiTreeNodeFlags getCustom() {
        return CUSTOM;
    }

    private static int ImGuiTreeNodeFlags_None_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_Selected_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_Selected_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_Framed_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_Framed_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_AllowOverlap_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_AllowOverlap_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_NoTreePushOnOpen_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_NoTreePushOnOpen_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_NoAutoOpenOnLog_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_NoAutoOpenOnLog_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_DefaultOpen_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_DefaultOpen_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_OpenOnDoubleClick_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_OpenOnDoubleClick_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_OpenOnArrow_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_OpenOnArrow_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_Leaf_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_Leaf_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_Bullet_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_Bullet_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_FramePadding_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_FramePadding_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_SpanAvailWidth_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_SpanAvailWidth_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_SpanFullWidth_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_SpanFullWidth_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_SpanLabelWidth_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_SpanLabelWidth_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_SpanAllColumns_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_SpanAllColumns_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_LabelSpanAllColumns_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_LabelSpanAllColumns_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_NavLeftJumpsToParent_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_NavLeftJumpsToParent_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_CollapsingHeader_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_CollapsingHeader_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_DrawLinesNone_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_DrawLinesNone_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_DrawLinesFull_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_DrawLinesFull_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiTreeNodeFlags_DrawLinesToNodes_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiTreeNodeFlags_DrawLinesToNodes_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_None_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_none_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_Selected_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_selected_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_Framed_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_framed_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_AllowOverlap_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_allowoverlap_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_NoTreePushOnOpen_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_notreepushonopen_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_NoAutoOpenOnLog_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_noautoopenonlog_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_DefaultOpen_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_defaultopen_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_OpenOnDoubleClick_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_openondoubleclick_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_OpenOnArrow_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_openonarrow_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_Leaf_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_leaf_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_Bullet_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_bullet_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_FramePadding_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_framepadding_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_SpanAvailWidth_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_spanavailwidth_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_SpanFullWidth_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_spanfullwidth_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_SpanLabelWidth_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_spanlabelwidth_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_SpanAllColumns_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_spanallcolumns_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_LabelSpanAllColumns_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_labelspanallcolumns_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_NavLeftJumpsToParent_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_navleftjumpstoparent_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_CollapsingHeader_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_collapsingheader_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_DrawLinesNone_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_drawlinesnone_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_DrawLinesFull_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_drawlinesfull_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiTreeNodeFlags_DrawLinesToNodes_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguitreenodeflags_imguitreenodeflags_drawlinestonodes_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
