/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImGuiInputTextFlags implements NativeEnum<ImGuiInputTextFlags> {

    CUSTOM(0),
    None(ImGuiInputTextFlags_None_NATIVE()),
    CharsDecimal(ImGuiInputTextFlags_CharsDecimal_NATIVE()),
    CharsHexadecimal(ImGuiInputTextFlags_CharsHexadecimal_NATIVE()),
    CharsScientific(ImGuiInputTextFlags_CharsScientific_NATIVE()),
    CharsUppercase(ImGuiInputTextFlags_CharsUppercase_NATIVE()),
    CharsNoBlank(ImGuiInputTextFlags_CharsNoBlank_NATIVE()),
    AllowTabInput(ImGuiInputTextFlags_AllowTabInput_NATIVE()),
    EnterReturnsTrue(ImGuiInputTextFlags_EnterReturnsTrue_NATIVE()),
    EscapeClearsAll(ImGuiInputTextFlags_EscapeClearsAll_NATIVE()),
    CtrlEnterForNewLine(ImGuiInputTextFlags_CtrlEnterForNewLine_NATIVE()),
    ReadOnly(ImGuiInputTextFlags_ReadOnly_NATIVE()),
    Password(ImGuiInputTextFlags_Password_NATIVE()),
    AlwaysOverwrite(ImGuiInputTextFlags_AlwaysOverwrite_NATIVE()),
    AutoSelectAll(ImGuiInputTextFlags_AutoSelectAll_NATIVE()),
    ParseEmptyRefVal(ImGuiInputTextFlags_ParseEmptyRefVal_NATIVE()),
    DisplayEmptyRefVal(ImGuiInputTextFlags_DisplayEmptyRefVal_NATIVE()),
    NoHorizontalScroll(ImGuiInputTextFlags_NoHorizontalScroll_NATIVE()),
    NoUndoRedo(ImGuiInputTextFlags_NoUndoRedo_NATIVE()),
    ElideLeft(ImGuiInputTextFlags_ElideLeft_NATIVE()),
    CallbackCompletion(ImGuiInputTextFlags_CallbackCompletion_NATIVE()),
    CallbackHistory(ImGuiInputTextFlags_CallbackHistory_NATIVE()),
    CallbackAlways(ImGuiInputTextFlags_CallbackAlways_NATIVE()),
    CallbackCharFilter(ImGuiInputTextFlags_CallbackCharFilter_NATIVE()),
    CallbackResize(ImGuiInputTextFlags_CallbackResize_NATIVE()),
    CallbackEdit(ImGuiInputTextFlags_CallbackEdit_NATIVE()),
    WordWrap(ImGuiInputTextFlags_WordWrap_NATIVE());

    private int value;

    private ImGuiInputTextFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiInputTextFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiInputTextFlags getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_None;
*/
    private static int ImGuiInputTextFlags_None_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CharsDecimal;
*/
    private static int ImGuiInputTextFlags_CharsDecimal_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CharsDecimal_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CharsHexadecimal;
*/
    private static int ImGuiInputTextFlags_CharsHexadecimal_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CharsHexadecimal_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CharsScientific;
*/
    private static int ImGuiInputTextFlags_CharsScientific_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CharsScientific_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CharsUppercase;
*/
    private static int ImGuiInputTextFlags_CharsUppercase_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CharsUppercase_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CharsNoBlank;
*/
    private static int ImGuiInputTextFlags_CharsNoBlank_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CharsNoBlank_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_AllowTabInput;
*/
    private static int ImGuiInputTextFlags_AllowTabInput_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_AllowTabInput_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_EnterReturnsTrue;
*/
    private static int ImGuiInputTextFlags_EnterReturnsTrue_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_EnterReturnsTrue_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_EscapeClearsAll;
*/
    private static int ImGuiInputTextFlags_EscapeClearsAll_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_EscapeClearsAll_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CtrlEnterForNewLine;
*/
    private static int ImGuiInputTextFlags_CtrlEnterForNewLine_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CtrlEnterForNewLine_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_ReadOnly;
*/
    private static int ImGuiInputTextFlags_ReadOnly_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_ReadOnly_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_Password;
*/
    private static int ImGuiInputTextFlags_Password_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_Password_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_AlwaysOverwrite;
*/
    private static int ImGuiInputTextFlags_AlwaysOverwrite_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_AlwaysOverwrite_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_AutoSelectAll;
*/
    private static int ImGuiInputTextFlags_AutoSelectAll_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_AutoSelectAll_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_ParseEmptyRefVal;
*/
    private static int ImGuiInputTextFlags_ParseEmptyRefVal_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_ParseEmptyRefVal_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_DisplayEmptyRefVal;
*/
    private static int ImGuiInputTextFlags_DisplayEmptyRefVal_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_DisplayEmptyRefVal_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_NoHorizontalScroll;
*/
    private static int ImGuiInputTextFlags_NoHorizontalScroll_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_NoHorizontalScroll_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_NoUndoRedo;
*/
    private static int ImGuiInputTextFlags_NoUndoRedo_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_NoUndoRedo_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_ElideLeft;
*/
    private static int ImGuiInputTextFlags_ElideLeft_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_ElideLeft_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CallbackCompletion;
*/
    private static int ImGuiInputTextFlags_CallbackCompletion_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CallbackCompletion_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CallbackHistory;
*/
    private static int ImGuiInputTextFlags_CallbackHistory_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CallbackHistory_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CallbackAlways;
*/
    private static int ImGuiInputTextFlags_CallbackAlways_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CallbackAlways_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CallbackCharFilter;
*/
    private static int ImGuiInputTextFlags_CallbackCharFilter_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CallbackCharFilter_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CallbackResize;
*/
    private static int ImGuiInputTextFlags_CallbackResize_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CallbackResize_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_CallbackEdit;
*/
    private static int ImGuiInputTextFlags_CallbackEdit_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_CallbackEdit_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)ImGuiInputTextFlags_WordWrap;
*/
    private static int ImGuiInputTextFlags_WordWrap_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiInputTextFlags_WordWrap_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_CRITICAL = new java.lang.foreign.Linker.Option[] { java.lang.foreign.Linker.Option.critical(true) };

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_DEFAULT = new java.lang.foreign.Linker.Option[0];

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static RuntimeException rethrow(Throwable e) {
            if (e instanceof RuntimeException)
                return (RuntimeException) e;
            if (e instanceof Error)
                throw (Error) e;
            return new RuntimeException(e);
        }

        static java.lang.invoke.MethodHandle downcallDefault(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
        }

        static java.lang.invoke.MethodHandle downcallCritical(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            try {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_CRITICAL);
            } catch (Throwable ignored) {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
            }
        }

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_None_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1None_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CharsDecimal_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CharsDecimal_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CharsHexadecimal_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CharsHexadecimal_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CharsScientific_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CharsScientific_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CharsUppercase_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CharsUppercase_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CharsNoBlank_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CharsNoBlank_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_AllowTabInput_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1AllowTabInput_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_EnterReturnsTrue_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1EnterReturnsTrue_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_EscapeClearsAll_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1EscapeClearsAll_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CtrlEnterForNewLine_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CtrlEnterForNewLine_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_ReadOnly_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1ReadOnly_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_Password_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1Password_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_AlwaysOverwrite_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1AlwaysOverwrite_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_AutoSelectAll_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1AutoSelectAll_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_ParseEmptyRefVal_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1ParseEmptyRefVal_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_DisplayEmptyRefVal_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1DisplayEmptyRefVal_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_NoHorizontalScroll_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1NoHorizontalScroll_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_NoUndoRedo_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1NoUndoRedo_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_ElideLeft_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1ElideLeft_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CallbackCompletion_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CallbackCompletion_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CallbackHistory_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CallbackHistory_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CallbackAlways_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CallbackAlways_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CallbackCharFilter_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CallbackCharFilter_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CallbackResize_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CallbackResize_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_CallbackEdit_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1CallbackEdit_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiInputTextFlags_WordWrap_NATIVE__ = downcallDefault("jparser_imgui_enums_ImGuiInputTextFlags_ImGuiInputTextFlags_1WordWrap_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
