/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImTextureStatus implements NativeEnum<ImTextureStatus> {

    CUSTOM(0),
    OK(ImTextureStatus_OK_NATIVE()),
    Destroyed(ImTextureStatus_Destroyed_NATIVE()),
    WantCreate(ImTextureStatus_WantCreate_NATIVE()),
    WantUpdates(ImTextureStatus_WantUpdates_NATIVE()),
    WantDestroy(ImTextureStatus_WantDestroy_NATIVE());

    private int value;

    private ImTextureStatus(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImTextureStatus setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImTextureStatus getCustom() {
        return CUSTOM;
    }

    private static int ImTextureStatus_OK_NATIVE() {
        try {
            return (int) FFMHandles.ImTextureStatus_OK_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImTextureStatus_Destroyed_NATIVE() {
        try {
            return (int) FFMHandles.ImTextureStatus_Destroyed_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImTextureStatus_WantCreate_NATIVE() {
        try {
            return (int) FFMHandles.ImTextureStatus_WantCreate_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImTextureStatus_WantUpdates_NATIVE() {
        try {
            return (int) FFMHandles.ImTextureStatus_WantUpdates_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImTextureStatus_WantDestroy_NATIVE() {
        try {
            return (int) FFMHandles.ImTextureStatus_WantDestroy_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle ImTextureStatus_OK_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imtexturestatus_imtexturestatus_ok_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImTextureStatus_Destroyed_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imtexturestatus_imtexturestatus_destroyed_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImTextureStatus_WantCreate_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imtexturestatus_imtexturestatus_wantcreate_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImTextureStatus_WantUpdates_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imtexturestatus_imtexturestatus_wantupdates_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImTextureStatus_WantDestroy_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imtexturestatus_imtexturestatus_wantdestroy_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
