/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.natives;

import imgui.*;

final public class JNI_ImTextureRef {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_long_addr(long tex_id);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetTexID(long this_addr);
}
