/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.natives;

import imgui.*;

final public class JNI_ImGuiContext {

    public static native double internal_native_get_Time(long this_addr);

    public static native int internal_native_get_NavId(long this_addr);

    public static native long internal_native_get_Windows_addr(long this_addr);

    public static native long internal_native_get_WindowsFocusOrder_addr(long this_addr);

    public static native long internal_native_get_WindowsTempSortBuffer_addr(long this_addr);

    public static native long internal_native_get_CurrentWindowStack_addr(long this_addr);

    public static native long internal_native_get_WindowsById_addr(long this_addr);

    public static native int internal_native_get_WindowsActiveCount(long this_addr);

    public static native float internal_native_get_WindowsBorderHoverPadding(long this_addr);

    public static native int internal_native_get_DebugBreakInWindow(long this_addr);

    public static native long internal_native_get_CurrentWindow_addr(long this_addr);

    public static native long internal_native_get_HoveredWindow_addr(long this_addr);

    public static native long internal_native_get_HoveredWindowUnderMovingWindow_addr(long this_addr);

    public static native long internal_native_get_HoveredWindowBeforeClear_addr(long this_addr);

    public static native long internal_native_get_MovingWindow_addr(long this_addr);

    public static native long internal_native_get_WheelingWindow_addr(long this_addr);

    public static native long internal_native_get_WheelingWindowRefMousePos_addr(long this_addr);

    public static native int internal_native_get_WheelingWindowStartFrame(long this_addr);

    public static native int internal_native_get_WheelingWindowScrolledFrame(long this_addr);

    public static native float internal_native_get_WheelingWindowReleaseTimer(long this_addr);

    public static native long internal_native_get_WheelingWindowWheelRemainder_addr(long this_addr);

    public static native long internal_native_get_WheelingAxisAvg_addr(long this_addr);

    public static native int internal_native_get_DebugDrawIdConflictsId(long this_addr);

    public static native int internal_native_get_DebugHookIdInfoId(long this_addr);

    public static native int internal_native_get_HoveredId(long this_addr);

    public static native int internal_native_get_HoveredIdPreviousFrame(long this_addr);

    public static native int internal_native_get_HoveredIdPreviousFrameItemCount(long this_addr);

    public static native float internal_native_get_HoveredIdTimer(long this_addr);

    public static native float internal_native_get_HoveredIdNotActiveTimer(long this_addr);

    public static native boolean internal_native_get_HoveredIdAllowOverlap(long this_addr);

    public static native boolean internal_native_get_HoveredIdIsDisabled(long this_addr);

    public static native boolean internal_native_get_ItemUnclipByLog(long this_addr);

    public static native int internal_native_get_ActiveId(long this_addr);

    public static native int internal_native_get_ActiveIdIsAlive(long this_addr);

    public static native float internal_native_get_ActiveIdTimer(long this_addr);

    public static native boolean internal_native_get_ActiveIdIsJustActivated(long this_addr);

    public static native boolean internal_native_get_ActiveIdAllowOverlap(long this_addr);

    public static native boolean internal_native_get_ActiveIdNoClearOnFocusLoss(long this_addr);

    public static native boolean internal_native_get_ActiveIdHasBeenPressedBefore(long this_addr);

    public static native boolean internal_native_get_ActiveIdHasBeenEditedBefore(long this_addr);

    public static native boolean internal_native_get_ActiveIdHasBeenEditedThisFrame(long this_addr);

    public static native boolean internal_native_get_ActiveIdFromShortcut(long this_addr);

    public static native int internal_native_get_ActiveIdDisabledId(long this_addr);

    public static native int internal_native_get_ActiveIdMouseButton(long this_addr);

    public static native long internal_native_get_ActiveIdClickOffset_addr(long this_addr);

    public static native long internal_native_get_ActiveIdWindow_addr(long this_addr);

    public static native int internal_native_get_ActiveIdPreviousFrame(long this_addr);

    public static native int internal_native_get_LastActiveId(long this_addr);

    public static native float internal_native_get_LastActiveIdTimer(long this_addr);

    public static native long internal_native_get_LastItemData_addr(long this_addr);
}
