/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public class ImGuiContext extends NativeObject {

    private ImVectorImGuiWindowPtr ImVectorImGuiWindowPtr_TEMP_GEN_0;

    private ImVectorImGuiWindowPtr ImVectorImGuiWindowPtr_TEMP_GEN_1;

    private ImVectorImGuiWindowPtr ImVectorImGuiWindowPtr_TEMP_GEN_2;

    private ImVectorImGuiWindowStackData ImVectorImGuiWindowStackData_TEMP_GEN_0;

    private ImGuiStorage ImGuiStorage_TEMP_GEN_0;

    private ImGuiWindow ImGuiWindow_TEMP_GEN_0;

    private ImGuiWindow ImGuiWindow_TEMP_GEN_1;

    private ImGuiWindow ImGuiWindow_TEMP_GEN_2;

    private ImGuiWindow ImGuiWindow_TEMP_GEN_3;

    private ImGuiWindow ImGuiWindow_TEMP_GEN_4;

    private ImGuiWindow ImGuiWindow_TEMP_GEN_5;

    private ImVec2 ImVec2_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_1;

    private ImVec2 ImVec2_TEMP_GEN_2;

    private ImVec2 ImVec2_TEMP_GEN_3;

    private ImGuiWindow ImGuiWindow_TEMP_GEN_6;

    private ImGuiLastItemData ImGuiLastItemData_TEMP_GEN_0;

    static public final ImGuiContext NULL = ImGuiContext.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiContext(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiContext native_new() {
        return new ImGuiContext((byte) 0, (char) 0);
    }

    public double get_Time() {
        return internal_native_get_Time(native_address);
    }

    public static double internal_native_get_Time(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_Time(this_addr);
    }

    public int get_NavId() {
        return internal_native_get_NavId(native_address);
    }

    public static int internal_native_get_NavId(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_NavId(this_addr);
    }

    public ImVectorImGuiWindowPtr get_Windows() {
        long addr = internal_native_get_Windows_addr(native_address);
        if (addr == 0)
            return ImVectorImGuiWindowPtr.NULL;
        if (ImVectorImGuiWindowPtr_TEMP_GEN_0 == null)
            ImVectorImGuiWindowPtr_TEMP_GEN_0 = ImVectorImGuiWindowPtr.native_new();
        ImVectorImGuiWindowPtr_TEMP_GEN_0.internal_reset(addr, false);
        return ImVectorImGuiWindowPtr_TEMP_GEN_0;
    }

    public static long internal_native_get_Windows_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_Windows_addr(this_addr);
    }

    public ImVectorImGuiWindowPtr get_WindowsFocusOrder() {
        long addr = internal_native_get_WindowsFocusOrder_addr(native_address);
        if (addr == 0)
            return ImVectorImGuiWindowPtr.NULL;
        if (ImVectorImGuiWindowPtr_TEMP_GEN_1 == null)
            ImVectorImGuiWindowPtr_TEMP_GEN_1 = ImVectorImGuiWindowPtr.native_new();
        ImVectorImGuiWindowPtr_TEMP_GEN_1.internal_reset(addr, false);
        return ImVectorImGuiWindowPtr_TEMP_GEN_1;
    }

    public static long internal_native_get_WindowsFocusOrder_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WindowsFocusOrder_addr(this_addr);
    }

    public ImVectorImGuiWindowPtr get_WindowsTempSortBuffer() {
        long addr = internal_native_get_WindowsTempSortBuffer_addr(native_address);
        if (addr == 0)
            return ImVectorImGuiWindowPtr.NULL;
        if (ImVectorImGuiWindowPtr_TEMP_GEN_2 == null)
            ImVectorImGuiWindowPtr_TEMP_GEN_2 = ImVectorImGuiWindowPtr.native_new();
        ImVectorImGuiWindowPtr_TEMP_GEN_2.internal_reset(addr, false);
        return ImVectorImGuiWindowPtr_TEMP_GEN_2;
    }

    public static long internal_native_get_WindowsTempSortBuffer_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WindowsTempSortBuffer_addr(this_addr);
    }

    public ImVectorImGuiWindowStackData get_CurrentWindowStack() {
        long addr = internal_native_get_CurrentWindowStack_addr(native_address);
        if (addr == 0)
            return ImVectorImGuiWindowStackData.NULL;
        if (ImVectorImGuiWindowStackData_TEMP_GEN_0 == null)
            ImVectorImGuiWindowStackData_TEMP_GEN_0 = ImVectorImGuiWindowStackData.native_new();
        ImVectorImGuiWindowStackData_TEMP_GEN_0.internal_reset(addr, false);
        return ImVectorImGuiWindowStackData_TEMP_GEN_0;
    }

    public static long internal_native_get_CurrentWindowStack_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_CurrentWindowStack_addr(this_addr);
    }

    public ImGuiStorage get_WindowsById() {
        long addr = internal_native_get_WindowsById_addr(native_address);
        if (addr == 0)
            return ImGuiStorage.NULL;
        if (ImGuiStorage_TEMP_GEN_0 == null)
            ImGuiStorage_TEMP_GEN_0 = ImGuiStorage.native_new();
        ImGuiStorage_TEMP_GEN_0.internal_reset(addr, false);
        return ImGuiStorage_TEMP_GEN_0;
    }

    public static long internal_native_get_WindowsById_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WindowsById_addr(this_addr);
    }

    public int get_WindowsActiveCount() {
        return internal_native_get_WindowsActiveCount(native_address);
    }

    public static int internal_native_get_WindowsActiveCount(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WindowsActiveCount(this_addr);
    }

    public float get_WindowsBorderHoverPadding() {
        return internal_native_get_WindowsBorderHoverPadding(native_address);
    }

    public static float internal_native_get_WindowsBorderHoverPadding(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WindowsBorderHoverPadding(this_addr);
    }

    public int get_DebugBreakInWindow() {
        return internal_native_get_DebugBreakInWindow(native_address);
    }

    public static int internal_native_get_DebugBreakInWindow(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_DebugBreakInWindow(this_addr);
    }

    public ImGuiWindow get_CurrentWindow() {
        long addr = internal_native_get_CurrentWindow_addr(native_address);
        if (addr == 0)
            return ImGuiWindow.NULL;
        if (ImGuiWindow_TEMP_GEN_0 == null)
            ImGuiWindow_TEMP_GEN_0 = ImGuiWindow.native_new();
        ImGuiWindow_TEMP_GEN_0.internal_reset(addr, false);
        return ImGuiWindow_TEMP_GEN_0;
    }

    public static long internal_native_get_CurrentWindow_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_CurrentWindow_addr(this_addr);
    }

    public ImGuiWindow get_HoveredWindow() {
        long addr = internal_native_get_HoveredWindow_addr(native_address);
        if (addr == 0)
            return ImGuiWindow.NULL;
        if (ImGuiWindow_TEMP_GEN_1 == null)
            ImGuiWindow_TEMP_GEN_1 = ImGuiWindow.native_new();
        ImGuiWindow_TEMP_GEN_1.internal_reset(addr, false);
        return ImGuiWindow_TEMP_GEN_1;
    }

    public static long internal_native_get_HoveredWindow_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_HoveredWindow_addr(this_addr);
    }

    public ImGuiWindow get_HoveredWindowUnderMovingWindow() {
        long addr = internal_native_get_HoveredWindowUnderMovingWindow_addr(native_address);
        if (addr == 0)
            return ImGuiWindow.NULL;
        if (ImGuiWindow_TEMP_GEN_2 == null)
            ImGuiWindow_TEMP_GEN_2 = ImGuiWindow.native_new();
        ImGuiWindow_TEMP_GEN_2.internal_reset(addr, false);
        return ImGuiWindow_TEMP_GEN_2;
    }

    public static long internal_native_get_HoveredWindowUnderMovingWindow_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_HoveredWindowUnderMovingWindow_addr(this_addr);
    }

    public ImGuiWindow get_HoveredWindowBeforeClear() {
        long addr = internal_native_get_HoveredWindowBeforeClear_addr(native_address);
        if (addr == 0)
            return ImGuiWindow.NULL;
        if (ImGuiWindow_TEMP_GEN_3 == null)
            ImGuiWindow_TEMP_GEN_3 = ImGuiWindow.native_new();
        ImGuiWindow_TEMP_GEN_3.internal_reset(addr, false);
        return ImGuiWindow_TEMP_GEN_3;
    }

    public static long internal_native_get_HoveredWindowBeforeClear_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_HoveredWindowBeforeClear_addr(this_addr);
    }

    public ImGuiWindow get_MovingWindow() {
        long addr = internal_native_get_MovingWindow_addr(native_address);
        if (addr == 0)
            return ImGuiWindow.NULL;
        if (ImGuiWindow_TEMP_GEN_4 == null)
            ImGuiWindow_TEMP_GEN_4 = ImGuiWindow.native_new();
        ImGuiWindow_TEMP_GEN_4.internal_reset(addr, false);
        return ImGuiWindow_TEMP_GEN_4;
    }

    public static long internal_native_get_MovingWindow_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_MovingWindow_addr(this_addr);
    }

    public ImGuiWindow get_WheelingWindow() {
        long addr = internal_native_get_WheelingWindow_addr(native_address);
        if (addr == 0)
            return ImGuiWindow.NULL;
        if (ImGuiWindow_TEMP_GEN_5 == null)
            ImGuiWindow_TEMP_GEN_5 = ImGuiWindow.native_new();
        ImGuiWindow_TEMP_GEN_5.internal_reset(addr, false);
        return ImGuiWindow_TEMP_GEN_5;
    }

    public static long internal_native_get_WheelingWindow_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WheelingWindow_addr(this_addr);
    }

    public ImVec2 get_WheelingWindowRefMousePos() {
        long addr = internal_native_get_WheelingWindowRefMousePos_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_0 == null)
            ImVec2_TEMP_GEN_0 = ImVec2.native_new();
        ImVec2_TEMP_GEN_0.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_0;
    }

    public static long internal_native_get_WheelingWindowRefMousePos_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WheelingWindowRefMousePos_addr(this_addr);
    }

    public int get_WheelingWindowStartFrame() {
        return internal_native_get_WheelingWindowStartFrame(native_address);
    }

    public static int internal_native_get_WheelingWindowStartFrame(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WheelingWindowStartFrame(this_addr);
    }

    public int get_WheelingWindowScrolledFrame() {
        return internal_native_get_WheelingWindowScrolledFrame(native_address);
    }

    public static int internal_native_get_WheelingWindowScrolledFrame(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WheelingWindowScrolledFrame(this_addr);
    }

    public float get_WheelingWindowReleaseTimer() {
        return internal_native_get_WheelingWindowReleaseTimer(native_address);
    }

    public static float internal_native_get_WheelingWindowReleaseTimer(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WheelingWindowReleaseTimer(this_addr);
    }

    public ImVec2 get_WheelingWindowWheelRemainder() {
        long addr = internal_native_get_WheelingWindowWheelRemainder_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_1 == null)
            ImVec2_TEMP_GEN_1 = ImVec2.native_new();
        ImVec2_TEMP_GEN_1.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_1;
    }

    public static long internal_native_get_WheelingWindowWheelRemainder_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WheelingWindowWheelRemainder_addr(this_addr);
    }

    public ImVec2 get_WheelingAxisAvg() {
        long addr = internal_native_get_WheelingAxisAvg_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_2 == null)
            ImVec2_TEMP_GEN_2 = ImVec2.native_new();
        ImVec2_TEMP_GEN_2.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_2;
    }

    public static long internal_native_get_WheelingAxisAvg_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_WheelingAxisAvg_addr(this_addr);
    }

    public int get_DebugDrawIdConflictsId() {
        return internal_native_get_DebugDrawIdConflictsId(native_address);
    }

    public static int internal_native_get_DebugDrawIdConflictsId(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_DebugDrawIdConflictsId(this_addr);
    }

    public int get_DebugHookIdInfoId() {
        return internal_native_get_DebugHookIdInfoId(native_address);
    }

    public static int internal_native_get_DebugHookIdInfoId(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_DebugHookIdInfoId(this_addr);
    }

    public int get_HoveredId() {
        return internal_native_get_HoveredId(native_address);
    }

    public static int internal_native_get_HoveredId(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_HoveredId(this_addr);
    }

    public int get_HoveredIdPreviousFrame() {
        return internal_native_get_HoveredIdPreviousFrame(native_address);
    }

    public static int internal_native_get_HoveredIdPreviousFrame(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_HoveredIdPreviousFrame(this_addr);
    }

    public int get_HoveredIdPreviousFrameItemCount() {
        return internal_native_get_HoveredIdPreviousFrameItemCount(native_address);
    }

    public static int internal_native_get_HoveredIdPreviousFrameItemCount(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_HoveredIdPreviousFrameItemCount(this_addr);
    }

    public float get_HoveredIdTimer() {
        return internal_native_get_HoveredIdTimer(native_address);
    }

    public static float internal_native_get_HoveredIdTimer(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_HoveredIdTimer(this_addr);
    }

    public float get_HoveredIdNotActiveTimer() {
        return internal_native_get_HoveredIdNotActiveTimer(native_address);
    }

    public static float internal_native_get_HoveredIdNotActiveTimer(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_HoveredIdNotActiveTimer(this_addr);
    }

    public boolean get_HoveredIdAllowOverlap() {
        return internal_native_get_HoveredIdAllowOverlap(native_address);
    }

    public static boolean internal_native_get_HoveredIdAllowOverlap(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_HoveredIdAllowOverlap(this_addr);
    }

    public boolean get_HoveredIdIsDisabled() {
        return internal_native_get_HoveredIdIsDisabled(native_address);
    }

    public static boolean internal_native_get_HoveredIdIsDisabled(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_HoveredIdIsDisabled(this_addr);
    }

    public boolean get_ItemUnclipByLog() {
        return internal_native_get_ItemUnclipByLog(native_address);
    }

    public static boolean internal_native_get_ItemUnclipByLog(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ItemUnclipByLog(this_addr);
    }

    public int get_ActiveId() {
        return internal_native_get_ActiveId(native_address);
    }

    public static int internal_native_get_ActiveId(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveId(this_addr);
    }

    public int get_ActiveIdIsAlive() {
        return internal_native_get_ActiveIdIsAlive(native_address);
    }

    public static int internal_native_get_ActiveIdIsAlive(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdIsAlive(this_addr);
    }

    public float get_ActiveIdTimer() {
        return internal_native_get_ActiveIdTimer(native_address);
    }

    public static float internal_native_get_ActiveIdTimer(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdTimer(this_addr);
    }

    public boolean get_ActiveIdIsJustActivated() {
        return internal_native_get_ActiveIdIsJustActivated(native_address);
    }

    public static boolean internal_native_get_ActiveIdIsJustActivated(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdIsJustActivated(this_addr);
    }

    public boolean get_ActiveIdAllowOverlap() {
        return internal_native_get_ActiveIdAllowOverlap(native_address);
    }

    public static boolean internal_native_get_ActiveIdAllowOverlap(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdAllowOverlap(this_addr);
    }

    public boolean get_ActiveIdNoClearOnFocusLoss() {
        return internal_native_get_ActiveIdNoClearOnFocusLoss(native_address);
    }

    public static boolean internal_native_get_ActiveIdNoClearOnFocusLoss(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdNoClearOnFocusLoss(this_addr);
    }

    public boolean get_ActiveIdHasBeenPressedBefore() {
        return internal_native_get_ActiveIdHasBeenPressedBefore(native_address);
    }

    public static boolean internal_native_get_ActiveIdHasBeenPressedBefore(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdHasBeenPressedBefore(this_addr);
    }

    public boolean get_ActiveIdHasBeenEditedBefore() {
        return internal_native_get_ActiveIdHasBeenEditedBefore(native_address);
    }

    public static boolean internal_native_get_ActiveIdHasBeenEditedBefore(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdHasBeenEditedBefore(this_addr);
    }

    public boolean get_ActiveIdHasBeenEditedThisFrame() {
        return internal_native_get_ActiveIdHasBeenEditedThisFrame(native_address);
    }

    public static boolean internal_native_get_ActiveIdHasBeenEditedThisFrame(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdHasBeenEditedThisFrame(this_addr);
    }

    public boolean get_ActiveIdFromShortcut() {
        return internal_native_get_ActiveIdFromShortcut(native_address);
    }

    public static boolean internal_native_get_ActiveIdFromShortcut(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdFromShortcut(this_addr);
    }

    public int get_ActiveIdDisabledId() {
        return internal_native_get_ActiveIdDisabledId(native_address);
    }

    public static int internal_native_get_ActiveIdDisabledId(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdDisabledId(this_addr);
    }

    public int get_ActiveIdMouseButton() {
        return internal_native_get_ActiveIdMouseButton(native_address);
    }

    public static int internal_native_get_ActiveIdMouseButton(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdMouseButton(this_addr);
    }

    public ImVec2 get_ActiveIdClickOffset() {
        long addr = internal_native_get_ActiveIdClickOffset_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_3 == null)
            ImVec2_TEMP_GEN_3 = ImVec2.native_new();
        ImVec2_TEMP_GEN_3.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_3;
    }

    public static long internal_native_get_ActiveIdClickOffset_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdClickOffset_addr(this_addr);
    }

    public ImGuiWindow get_ActiveIdWindow() {
        long addr = internal_native_get_ActiveIdWindow_addr(native_address);
        if (addr == 0)
            return ImGuiWindow.NULL;
        if (ImGuiWindow_TEMP_GEN_6 == null)
            ImGuiWindow_TEMP_GEN_6 = ImGuiWindow.native_new();
        ImGuiWindow_TEMP_GEN_6.internal_reset(addr, false);
        return ImGuiWindow_TEMP_GEN_6;
    }

    public static long internal_native_get_ActiveIdWindow_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdWindow_addr(this_addr);
    }

    public int get_ActiveIdPreviousFrame() {
        return internal_native_get_ActiveIdPreviousFrame(native_address);
    }

    public static int internal_native_get_ActiveIdPreviousFrame(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_ActiveIdPreviousFrame(this_addr);
    }

    public int get_LastActiveId() {
        return internal_native_get_LastActiveId(native_address);
    }

    public static int internal_native_get_LastActiveId(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_LastActiveId(this_addr);
    }

    public float get_LastActiveIdTimer() {
        return internal_native_get_LastActiveIdTimer(native_address);
    }

    public static float internal_native_get_LastActiveIdTimer(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_LastActiveIdTimer(this_addr);
    }

    public ImGuiLastItemData get_LastItemData() {
        long addr = internal_native_get_LastItemData_addr(native_address);
        if (addr == 0)
            return ImGuiLastItemData.NULL;
        if (ImGuiLastItemData_TEMP_GEN_0 == null)
            ImGuiLastItemData_TEMP_GEN_0 = ImGuiLastItemData.native_new();
        ImGuiLastItemData_TEMP_GEN_0.internal_reset(addr, false);
        return ImGuiLastItemData_TEMP_GEN_0;
    }

    public static long internal_native_get_LastItemData_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiContext.internal_native_get_LastItemData_addr(this_addr);
    }
}
