/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public class ImGuiStorage extends NativeObject {

    private NativeObject NativeObject_TEMP_GEN_0;

    private ImVectorImGuiStoragePair ImVectorImGuiStoragePair_TEMP_GEN_0;

    static public final ImGuiStorage NULL = ImGuiStorage.native_new();

    public ImGuiStorage() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return imgui.natives.JNI_ImGuiStorage.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiStorage(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiStorage native_new() {
        return new ImGuiStorage((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        imgui.natives.JNI_ImGuiStorage.internal_native_deleteNative(this_addr);
    }

    public void Clear() {
        internal_native_Clear(native_address);
    }

    public static void internal_native_Clear(long this_addr) {
        imgui.natives.JNI_ImGuiStorage.internal_native_Clear(this_addr);
    }

    public int GetInt(int key, int default_val) {
        return internal_native_GetInt(native_address, key, default_val);
    }

    public static int internal_native_GetInt(long this_addr, int key, int default_val) {
        return imgui.natives.JNI_ImGuiStorage.internal_native_GetInt(this_addr, key, default_val);
    }

    public int GetInt(int key) {
        return internal_native_GetInt(native_address, key);
    }

    public static int internal_native_GetInt(long this_addr, int key) {
        return imgui.natives.JNI_ImGuiStorage.internal_native_GetInt(this_addr, key);
    }

    public void SetInt(int key, int val) {
        internal_native_SetInt(native_address, key, val);
    }

    public static void internal_native_SetInt(long this_addr, int key, int val) {
        imgui.natives.JNI_ImGuiStorage.internal_native_SetInt(this_addr, key, val);
    }

    public boolean GetBool(int key, boolean default_val) {
        return internal_native_GetBool(native_address, key, default_val);
    }

    public static boolean internal_native_GetBool(long this_addr, int key, boolean default_val) {
        return imgui.natives.JNI_ImGuiStorage.internal_native_GetBool(this_addr, key, default_val);
    }

    public boolean GetBool(int key) {
        return internal_native_GetBool(native_address, key);
    }

    public static boolean internal_native_GetBool(long this_addr, int key) {
        return imgui.natives.JNI_ImGuiStorage.internal_native_GetBool(this_addr, key);
    }

    public void SetBool(int key, boolean val) {
        internal_native_SetBool(native_address, key, val);
    }

    public static void internal_native_SetBool(long this_addr, int key, boolean val) {
        imgui.natives.JNI_ImGuiStorage.internal_native_SetBool(this_addr, key, val);
    }

    public float GetFloat(int key, float default_val) {
        return internal_native_GetFloat(native_address, key, default_val);
    }

    public static float internal_native_GetFloat(long this_addr, int key, float default_val) {
        return imgui.natives.JNI_ImGuiStorage.internal_native_GetFloat(this_addr, key, default_val);
    }

    public float GetFloat(int key) {
        return internal_native_GetFloat(native_address, key);
    }

    public static float internal_native_GetFloat(long this_addr, int key) {
        return imgui.natives.JNI_ImGuiStorage.internal_native_GetFloat(this_addr, key);
    }

    public void SetFloat(int key, float val) {
        internal_native_SetFloat(native_address, key, val);
    }

    public static void internal_native_SetFloat(long this_addr, int key, float val) {
        imgui.natives.JNI_ImGuiStorage.internal_native_SetFloat(this_addr, key, val);
    }

    public NativeObject GetVoidPtr(int key) {
        long addr = internal_native_GetVoidPtr_addr(native_address, key);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    public static long internal_native_GetVoidPtr_addr(long this_addr, int key) {
        return imgui.natives.JNI_ImGuiStorage.internal_native_GetVoidPtr_addr(this_addr, key);
    }

    public void SetVoidPtr(int key, NativeObject val) {
        internal_native_SetVoidPtr(native_address, key, val.native_void_address);
    }

    public static void internal_native_SetVoidPtr(long this_addr, int key, long val_addr) {
        imgui.natives.JNI_ImGuiStorage.internal_native_SetVoidPtr(this_addr, key, val_addr);
    }

    public ImVectorImGuiStoragePair get_Data() {
        long addr = internal_native_get_Data_addr(native_address);
        if (addr == 0)
            return ImVectorImGuiStoragePair.NULL;
        if (ImVectorImGuiStoragePair_TEMP_GEN_0 == null)
            ImVectorImGuiStoragePair_TEMP_GEN_0 = ImVectorImGuiStoragePair.native_new();
        ImVectorImGuiStoragePair_TEMP_GEN_0.internal_reset(addr, false);
        return ImVectorImGuiStoragePair_TEMP_GEN_0;
    }

    public static long internal_native_get_Data_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiStorage.internal_native_get_Data_addr(this_addr);
    }
}
