/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public class ImVec4 extends NativeObject {

    static public final ImVec4 NULL = ImVec4.native_new();

    public ImVec4() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return imgui.natives.JNI_ImVec4.internal_native_create_addr();
    }

    public ImVec4(float x, float y, float z, float w) {
        long addr = internal_native_create_float_float_float_float_addr(x, y, z, w);
        internal_reset(addr, true);
    }

    public static long internal_native_create_float_float_float_float_addr(float x, float y, float z, float w) {
        return imgui.natives.JNI_ImVec4.internal_native_create_float_float_float_float_addr(x, y, z, w);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImVec4(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImVec4 native_new() {
        return new ImVec4((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        imgui.natives.JNI_ImVec4.internal_native_deleteNative(this_addr);
    }

    public ImVec4 copy(ImVec4 value) {
        internal_native_copy_addr(native_address, value.native_address);
        return this;
    }

    public static long internal_native_copy_addr(long this_addr, long value_addr) {
        return imgui.natives.JNI_ImVec4.internal_native_copy_addr(this_addr, value_addr);
    }

    public float get_x() {
        return internal_native_get_x(native_address);
    }

    public static float internal_native_get_x(long this_addr) {
        return imgui.natives.JNI_ImVec4.internal_native_get_x(this_addr);
    }

    public void set_x(float x) {
        internal_native_set_x(native_address, x);
    }

    public static void internal_native_set_x(long this_addr, float x) {
        imgui.natives.JNI_ImVec4.internal_native_set_x(this_addr, x);
    }

    public float get_y() {
        return internal_native_get_y(native_address);
    }

    public static float internal_native_get_y(long this_addr) {
        return imgui.natives.JNI_ImVec4.internal_native_get_y(this_addr);
    }

    public void set_y(float y) {
        internal_native_set_y(native_address, y);
    }

    public static void internal_native_set_y(long this_addr, float y) {
        imgui.natives.JNI_ImVec4.internal_native_set_y(this_addr, y);
    }

    public float get_z() {
        return internal_native_get_z(native_address);
    }

    public static float internal_native_get_z(long this_addr) {
        return imgui.natives.JNI_ImVec4.internal_native_get_z(this_addr);
    }

    public void set_z(float z) {
        internal_native_set_z(native_address, z);
    }

    public static void internal_native_set_z(long this_addr, float z) {
        imgui.natives.JNI_ImVec4.internal_native_set_z(this_addr, z);
    }

    public float get_w() {
        return internal_native_get_w(native_address);
    }

    public static float internal_native_get_w(long this_addr) {
        return imgui.natives.JNI_ImVec4.internal_native_get_w(this_addr);
    }

    public void set_w(float w) {
        internal_native_set_w(native_address, w);
    }

    public static void internal_native_set_w(long this_addr, float w) {
        imgui.natives.JNI_ImVec4.internal_native_set_w(this_addr, w);
    }
}
