/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public class ImVectorImGuiID extends NativeObject {

    private NativeObject NativeObject_TEMP_GEN_0;

    static public final ImVectorImGuiID NULL = ImVectorImGuiID.native_new();

    public ImVectorImGuiID() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return imgui.natives.JNI_ImVectorImGuiID.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImVectorImGuiID(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImVectorImGuiID native_new() {
        return new ImVectorImGuiID((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        imgui.natives.JNI_ImVectorImGuiID.internal_native_deleteNative(this_addr);
    }

    public int size() {
        return internal_native_size(native_address);
    }

    public static int internal_native_size(long this_addr) {
        return imgui.natives.JNI_ImVectorImGuiID.internal_native_size(this_addr);
    }

    public int getData(int index) {
        return internal_native_getData(native_address, index);
    }

    public static int internal_native_getData(long this_addr, int index) {
        return imgui.natives.JNI_ImVectorImGuiID.internal_native_getData(this_addr, index);
    }

    public void push_back(int v) {
        internal_native_push_back(native_address, v);
    }

    public static void internal_native_push_back(long this_addr, int v) {
        imgui.natives.JNI_ImVectorImGuiID.internal_native_push_back(this_addr, v);
    }

    public void reserve(int new_capacity) {
        internal_native_reserve(native_address, new_capacity);
    }

    public static void internal_native_reserve(long this_addr, int new_capacity) {
        imgui.natives.JNI_ImVectorImGuiID.internal_native_reserve(this_addr, new_capacity);
    }

    public void resize(int new_size) {
        internal_native_resize(native_address, new_size);
    }

    public static void internal_native_resize(long this_addr, int new_size) {
        imgui.natives.JNI_ImVectorImGuiID.internal_native_resize(this_addr, new_size);
    }

    public void clear() {
        internal_native_clear(native_address);
    }

    public static void internal_native_clear(long this_addr) {
        imgui.natives.JNI_ImVectorImGuiID.internal_native_clear(this_addr);
    }

    public NativeObject get_Data() {
        long addr = internal_native_get_Data_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    public static long internal_native_get_Data_addr(long this_addr) {
        return imgui.natives.JNI_ImVectorImGuiID.internal_native_get_Data_addr(this_addr);
    }
}
