/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums.natives;

import imgui.enums.*;

final public class JNI_ImGuiWindowDockStyleCol {

    static native public int ImGuiWindowDockStyleCol_Text_NATIVE();

    static native public int ImGuiWindowDockStyleCol_TabHovered_NATIVE();

    static native public int ImGuiWindowDockStyleCol_TabFocused_NATIVE();

    static native public int ImGuiWindowDockStyleCol_TabSelected_NATIVE();

    static native public int ImGuiWindowDockStyleCol_TabSelectedOverline_NATIVE();

    static native public int ImGuiWindowDockStyleCol_TabDimmed_NATIVE();

    static native public int ImGuiWindowDockStyleCol_TabDimmedSelected_NATIVE();

    static native public int ImGuiWindowDockStyleCol_TabDimmedSelectedOverline_NATIVE();

    static native public int ImGuiWindowDockStyleCol_COUNT_NATIVE();
}
