/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums.natives;

import imgui.enums.*;

final public class JNI_ImGuiInputSource {

    static native public int ImGuiInputSource_None_NATIVE();

    static native public int ImGuiInputSource_Mouse_NATIVE();

    static native public int ImGuiInputSource_Keyboard_NATIVE();

    static native public int ImGuiInputSource_Gamepad_NATIVE();

    static native public int ImGuiInputSource_COUNT_NATIVE();
}
