/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums.natives;

import imgui.enums.*;

final public class JNI_ImFontAtlasFlags {

    static native public int ImFontAtlasFlags_None_NATIVE();

    static native public int ImFontAtlasFlags_NoPowerOfTwoHeight_NATIVE();

    static native public int ImFontAtlasFlags_NoMouseCursors_NATIVE();

    static native public int ImFontAtlasFlags_NoBakedLines_NATIVE();
}
