/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums.natives;

import imgui.enums.*;

final public class JNI_ImGuiLogFlags {

    static native public int ImGuiLogFlags_None_NATIVE();

    static native public int ImGuiLogFlags_OutputTTY_NATIVE();

    static native public int ImGuiLogFlags_OutputFile_NATIVE();

    static native public int ImGuiLogFlags_OutputBuffer_NATIVE();

    static native public int ImGuiLogFlags_OutputClipboard_NATIVE();

    static native public int ImGuiLogFlags_OutputMask__NATIVE();
}
