/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums.natives;

import imgui.enums.*;

final public class JNI_ImFontFlags {

    static native public int ImFontFlags_None_NATIVE();

    static native public int ImFontFlags_NoLoadError_NATIVE();

    static native public int ImFontFlags_NoLoadGlyphs_NATIVE();

    static native public int ImFontFlags_LockBakedSizes_NATIVE();
}
