/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums.natives;

import imgui.enums.*;

final public class JNI_ImGuiCond {

    static native public int ImGuiCond_None_NATIVE();

    static native public int ImGuiCond_Always_NATIVE();

    static native public int ImGuiCond_Once_NATIVE();

    static native public int ImGuiCond_FirstUseEver_NATIVE();

    static native public int ImGuiCond_Appearing_NATIVE();
}
