/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums.natives;

import imgui.enums.*;

final public class JNI_ImGuiButtonFlags {

    static native public int ImGuiButtonFlags_None_NATIVE();

    static native public int ImGuiButtonFlags_MouseButtonLeft_NATIVE();

    static native public int ImGuiButtonFlags_MouseButtonRight_NATIVE();

    static native public int ImGuiButtonFlags_MouseButtonMiddle_NATIVE();

    static native public int ImGuiButtonFlags_MouseButtonMask__NATIVE();

    static native public int ImGuiButtonFlags_EnableNav_NATIVE();
}
