/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.extension.nodeeditor;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class LoadSaveSettingsListener extends NativeObject {

    static private NativeString NativeString_TEMP_STATIC_GEN_0;

    static private NativeString NativeString_TEMP_STATIC_GEN_1;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_onLoad = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onLoad = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onSave = java.lang.invoke.MethodType.methodType(boolean.class, long.class, int.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onSave = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_INT);

    static public final LoadSaveSettingsListener NULL = LoadSaveSettingsListener.native_new();

    @Deprecated()
    protected LoadSaveSettingsListener(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static LoadSaveSettingsListener native_new() {
        return new LoadSaveSettingsListener((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public LoadSaveSettingsListener() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_onLoad = callbackLookup.findVirtual(LoadSaveSettingsListener.class, "internal_onLoad", callbackMethodType_onLoad).bindTo(this);
            upcallStub_onLoad = callbackLinker.upcallStub(mh_onLoad, callbackDescriptor_onLoad, upcallArena);
            java.lang.invoke.MethodHandle mh_onSave = callbackLookup.findVirtual(LoadSaveSettingsListener.class, "internal_onSave", callbackMethodType_onSave).bindTo(this);
            upcallStub_onSave = callbackLinker.upcallStub(mh_onSave, callbackDescriptor_onSave, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_onLoad.address(), upcallStub_onSave.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected void onLoad(NativeString data) {
    }

    private void internal_onLoad(long data_addr) {
        if (NativeString_TEMP_STATIC_GEN_0 == null)
            NativeString_TEMP_STATIC_GEN_0 = NativeString.native_new();
        NativeString_TEMP_STATIC_GEN_0.internal_reset(data_addr, false);
        onLoad(NativeString_TEMP_STATIC_GEN_0);
    }

    protected boolean onSave(NativeString data, SaveReasonFlags reason) {
        return false;
    }

    private boolean internal_onSave(long data_addr, int reason_addr) {
        if (NativeString_TEMP_STATIC_GEN_1 == null)
            NativeString_TEMP_STATIC_GEN_1 = NativeString.native_new();
        NativeString_TEMP_STATIC_GEN_1.internal_reset(data_addr, false);
        SaveReasonFlags reason_addr_enum = SaveReasonFlags.CUSTOM.setValue(reason_addr);
        SaveReasonFlags[] reason_addr_enum_values = SaveReasonFlags.values();
        for (int i = 0; i < reason_addr_enum_values.length; i++) {
            SaveReasonFlags enumVal = reason_addr_enum_values[i];
            if (enumVal != SaveReasonFlags.CUSTOM && enumVal.getValue() == reason_addr) {
                reason_addr_enum = reason_addr_enum_values[i];
                break;
            }
        }
        return onSave(NativeString_TEMP_STATIC_GEN_1, reason_addr_enum);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_onLoad;

    private MemorySegment upcallStub_onSave;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_onLoad = null;
        upcallStub_onSave = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long onLoad_fp, long onSave_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJJ.invokeExact(this_addr, onLoad_fp, onSave_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_extension_nodeeditor_loadsavesettingslistener_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_extension_nodeeditor_loadsavesettingslistener_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_extension_nodeeditor_loadsavesettingslistener_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
