/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImFontFlags implements NativeEnum<ImFontFlags> {

    CUSTOM(0), None(ImFontFlags_None_NATIVE()), NoLoadError(ImFontFlags_NoLoadError_NATIVE()), NoLoadGlyphs(ImFontFlags_NoLoadGlyphs_NATIVE()), LockBakedSizes(ImFontFlags_LockBakedSizes_NATIVE());

    private int value;

    private ImFontFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImFontFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImFontFlags getCustom() {
        return CUSTOM;
    }

    private static int ImFontFlags_None_NATIVE() {
        return imgui.enums.natives.JNI_ImFontFlags.ImFontFlags_None_NATIVE();
    }

    private static int ImFontFlags_NoLoadError_NATIVE() {
        return imgui.enums.natives.JNI_ImFontFlags.ImFontFlags_NoLoadError_NATIVE();
    }

    private static int ImFontFlags_NoLoadGlyphs_NATIVE() {
        return imgui.enums.natives.JNI_ImFontFlags.ImFontFlags_NoLoadGlyphs_NATIVE();
    }

    private static int ImFontFlags_LockBakedSizes_NATIVE() {
        return imgui.enums.natives.JNI_ImFontFlags.ImFontFlags_LockBakedSizes_NATIVE();
    }
}
