/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImGuiItemFlags implements NativeEnum<ImGuiItemFlags> {

    CUSTOM(0),
    None(ImGuiItemFlags_None_NATIVE()),
    NoTabStop(ImGuiItemFlags_NoTabStop_NATIVE()),
    NoNav(ImGuiItemFlags_NoNav_NATIVE()),
    NoNavDefaultFocus(ImGuiItemFlags_NoNavDefaultFocus_NATIVE()),
    ButtonRepeat(ImGuiItemFlags_ButtonRepeat_NATIVE()),
    AutoClosePopups(ImGuiItemFlags_AutoClosePopups_NATIVE()),
    AllowDuplicateId(ImGuiItemFlags_AllowDuplicateId_NATIVE());

    private int value;

    private ImGuiItemFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiItemFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiItemFlags getCustom() {
        return CUSTOM;
    }

    private static int ImGuiItemFlags_None_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlags.ImGuiItemFlags_None_NATIVE();
    }

    private static int ImGuiItemFlags_NoTabStop_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlags.ImGuiItemFlags_NoTabStop_NATIVE();
    }

    private static int ImGuiItemFlags_NoNav_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlags.ImGuiItemFlags_NoNav_NATIVE();
    }

    private static int ImGuiItemFlags_NoNavDefaultFocus_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlags.ImGuiItemFlags_NoNavDefaultFocus_NATIVE();
    }

    private static int ImGuiItemFlags_ButtonRepeat_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlags.ImGuiItemFlags_ButtonRepeat_NATIVE();
    }

    private static int ImGuiItemFlags_AutoClosePopups_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlags.ImGuiItemFlags_AutoClosePopups_NATIVE();
    }

    private static int ImGuiItemFlags_AllowDuplicateId_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlags.ImGuiItemFlags_AllowDuplicateId_NATIVE();
    }
}
