/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImGuiItemFlagsPrivate_ implements NativeEnum<ImGuiItemFlagsPrivate_> {

    CUSTOM(0),
    Disabled(ImGuiItemFlags_Disabled_NATIVE()),
    ReadOnly(ImGuiItemFlags_ReadOnly_NATIVE()),
    MixedValue(ImGuiItemFlags_MixedValue_NATIVE()),
    NoWindowHoverableCheck(ImGuiItemFlags_NoWindowHoverableCheck_NATIVE()),
    AllowOverlap(ImGuiItemFlags_AllowOverlap_NATIVE()),
    NoNavDisableMouseHover(ImGuiItemFlags_NoNavDisableMouseHover_NATIVE()),
    NoMarkEdited(ImGuiItemFlags_NoMarkEdited_NATIVE()),
    NoFocus(ImGuiItemFlags_NoFocus_NATIVE()),
    Inputable(ImGuiItemFlags_Inputable_NATIVE()),
    HasSelectionUserData(ImGuiItemFlags_HasSelectionUserData_NATIVE()),
    IsMultiSelect(ImGuiItemFlags_IsMultiSelect_NATIVE()),
    Default_(ImGuiItemFlags_Default__NATIVE());

    private int value;

    private ImGuiItemFlagsPrivate_(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiItemFlagsPrivate_ setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiItemFlagsPrivate_ getCustom() {
        return CUSTOM;
    }

    private static int ImGuiItemFlags_Disabled_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_Disabled_NATIVE();
    }

    private static int ImGuiItemFlags_ReadOnly_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_ReadOnly_NATIVE();
    }

    private static int ImGuiItemFlags_MixedValue_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_MixedValue_NATIVE();
    }

    private static int ImGuiItemFlags_NoWindowHoverableCheck_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_NoWindowHoverableCheck_NATIVE();
    }

    private static int ImGuiItemFlags_AllowOverlap_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_AllowOverlap_NATIVE();
    }

    private static int ImGuiItemFlags_NoNavDisableMouseHover_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_NoNavDisableMouseHover_NATIVE();
    }

    private static int ImGuiItemFlags_NoMarkEdited_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_NoMarkEdited_NATIVE();
    }

    private static int ImGuiItemFlags_NoFocus_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_NoFocus_NATIVE();
    }

    private static int ImGuiItemFlags_Inputable_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_Inputable_NATIVE();
    }

    private static int ImGuiItemFlags_HasSelectionUserData_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_HasSelectionUserData_NATIVE();
    }

    private static int ImGuiItemFlags_IsMultiSelect_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_IsMultiSelect_NATIVE();
    }

    private static int ImGuiItemFlags_Default__NATIVE() {
        return imgui.enums.natives.JNI_ImGuiItemFlagsPrivate_.ImGuiItemFlags_Default__NATIVE();
    }
}
