/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImGuiTabBarFlags implements NativeEnum<ImGuiTabBarFlags> {

    CUSTOM(0),
    None(ImGuiTabBarFlags_None_NATIVE()),
    Reorderable(ImGuiTabBarFlags_Reorderable_NATIVE()),
    AutoSelectNewTabs(ImGuiTabBarFlags_AutoSelectNewTabs_NATIVE()),
    TabListPopupButton(ImGuiTabBarFlags_TabListPopupButton_NATIVE()),
    NoCloseWithMiddleMouseButton(ImGuiTabBarFlags_NoCloseWithMiddleMouseButton_NATIVE()),
    NoTabListScrollingButtons(ImGuiTabBarFlags_NoTabListScrollingButtons_NATIVE()),
    NoTooltip(ImGuiTabBarFlags_NoTooltip_NATIVE()),
    DrawSelectedOverline(ImGuiTabBarFlags_DrawSelectedOverline_NATIVE()),
    FittingPolicyMixed(ImGuiTabBarFlags_FittingPolicyMixed_NATIVE()),
    FittingPolicyShrink(ImGuiTabBarFlags_FittingPolicyShrink_NATIVE()),
    FittingPolicyScroll(ImGuiTabBarFlags_FittingPolicyScroll_NATIVE()),
    FittingPolicyMask_(ImGuiTabBarFlags_FittingPolicyMask__NATIVE()),
    FittingPolicyDefault_(ImGuiTabBarFlags_FittingPolicyDefault__NATIVE());

    private int value;

    private ImGuiTabBarFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiTabBarFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiTabBarFlags getCustom() {
        return CUSTOM;
    }

    private static int ImGuiTabBarFlags_None_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_None_NATIVE();
    }

    private static int ImGuiTabBarFlags_Reorderable_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_Reorderable_NATIVE();
    }

    private static int ImGuiTabBarFlags_AutoSelectNewTabs_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_AutoSelectNewTabs_NATIVE();
    }

    private static int ImGuiTabBarFlags_TabListPopupButton_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_TabListPopupButton_NATIVE();
    }

    private static int ImGuiTabBarFlags_NoCloseWithMiddleMouseButton_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_NoCloseWithMiddleMouseButton_NATIVE();
    }

    private static int ImGuiTabBarFlags_NoTabListScrollingButtons_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_NoTabListScrollingButtons_NATIVE();
    }

    private static int ImGuiTabBarFlags_NoTooltip_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_NoTooltip_NATIVE();
    }

    private static int ImGuiTabBarFlags_DrawSelectedOverline_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_DrawSelectedOverline_NATIVE();
    }

    private static int ImGuiTabBarFlags_FittingPolicyMixed_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_FittingPolicyMixed_NATIVE();
    }

    private static int ImGuiTabBarFlags_FittingPolicyShrink_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_FittingPolicyShrink_NATIVE();
    }

    private static int ImGuiTabBarFlags_FittingPolicyScroll_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_FittingPolicyScroll_NATIVE();
    }

    private static int ImGuiTabBarFlags_FittingPolicyMask__NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_FittingPolicyMask__NATIVE();
    }

    private static int ImGuiTabBarFlags_FittingPolicyDefault__NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabBarFlags.ImGuiTabBarFlags_FittingPolicyDefault__NATIVE();
    }
}
