/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImGuiTabItemFlagsPrivate_ implements NativeEnum<ImGuiTabItemFlagsPrivate_> {

    CUSTOM(0),
    SectionMask_(ImGuiTabItemFlags_SectionMask__NATIVE()),
    NoCloseButton(ImGuiTabItemFlags_NoCloseButton_NATIVE()),
    Button(ImGuiTabItemFlags_Button_NATIVE()),
    Invisible(ImGuiTabItemFlags_Invisible_NATIVE()),
    Unsorted(ImGuiTabItemFlags_Unsorted_NATIVE());

    private int value;

    private ImGuiTabItemFlagsPrivate_(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiTabItemFlagsPrivate_ setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiTabItemFlagsPrivate_ getCustom() {
        return CUSTOM;
    }

    private static int ImGuiTabItemFlags_SectionMask__NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabItemFlagsPrivate_.ImGuiTabItemFlags_SectionMask__NATIVE();
    }

    private static int ImGuiTabItemFlags_NoCloseButton_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabItemFlagsPrivate_.ImGuiTabItemFlags_NoCloseButton_NATIVE();
    }

    private static int ImGuiTabItemFlags_Button_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabItemFlagsPrivate_.ImGuiTabItemFlags_Button_NATIVE();
    }

    private static int ImGuiTabItemFlags_Invisible_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabItemFlagsPrivate_.ImGuiTabItemFlags_Invisible_NATIVE();
    }

    private static int ImGuiTabItemFlags_Unsorted_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTabItemFlagsPrivate_.ImGuiTabItemFlags_Unsorted_NATIVE();
    }
}
