/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImGuiSliderFlags implements NativeEnum<ImGuiSliderFlags> {

    CUSTOM(0),
    None(ImGuiSliderFlags_None_NATIVE()),
    Logarithmic(ImGuiSliderFlags_Logarithmic_NATIVE()),
    NoRoundToFormat(ImGuiSliderFlags_NoRoundToFormat_NATIVE()),
    NoInput(ImGuiSliderFlags_NoInput_NATIVE()),
    WrapAround(ImGuiSliderFlags_WrapAround_NATIVE()),
    ClampOnInput(ImGuiSliderFlags_ClampOnInput_NATIVE()),
    ClampZeroRange(ImGuiSliderFlags_ClampZeroRange_NATIVE()),
    NoSpeedTweaks(ImGuiSliderFlags_NoSpeedTweaks_NATIVE()),
    AlwaysClamp(ImGuiSliderFlags_AlwaysClamp_NATIVE()),
    InvalidMask_(ImGuiSliderFlags_InvalidMask__NATIVE());

    private int value;

    private ImGuiSliderFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiSliderFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiSliderFlags getCustom() {
        return CUSTOM;
    }

    private static int ImGuiSliderFlags_None_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSliderFlags.ImGuiSliderFlags_None_NATIVE();
    }

    private static int ImGuiSliderFlags_Logarithmic_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSliderFlags.ImGuiSliderFlags_Logarithmic_NATIVE();
    }

    private static int ImGuiSliderFlags_NoRoundToFormat_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSliderFlags.ImGuiSliderFlags_NoRoundToFormat_NATIVE();
    }

    private static int ImGuiSliderFlags_NoInput_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSliderFlags.ImGuiSliderFlags_NoInput_NATIVE();
    }

    private static int ImGuiSliderFlags_WrapAround_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSliderFlags.ImGuiSliderFlags_WrapAround_NATIVE();
    }

    private static int ImGuiSliderFlags_ClampOnInput_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSliderFlags.ImGuiSliderFlags_ClampOnInput_NATIVE();
    }

    private static int ImGuiSliderFlags_ClampZeroRange_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSliderFlags.ImGuiSliderFlags_ClampZeroRange_NATIVE();
    }

    private static int ImGuiSliderFlags_NoSpeedTweaks_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSliderFlags.ImGuiSliderFlags_NoSpeedTweaks_NATIVE();
    }

    private static int ImGuiSliderFlags_AlwaysClamp_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSliderFlags.ImGuiSliderFlags_AlwaysClamp_NATIVE();
    }

    private static int ImGuiSliderFlags_InvalidMask__NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSliderFlags.ImGuiSliderFlags_InvalidMask__NATIVE();
    }
}
