/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImGuiTableColumnFlags implements NativeEnum<ImGuiTableColumnFlags> {

    CUSTOM(0),
    None(ImGuiTableColumnFlags_None_NATIVE()),
    Disabled(ImGuiTableColumnFlags_Disabled_NATIVE()),
    DefaultHide(ImGuiTableColumnFlags_DefaultHide_NATIVE()),
    DefaultSort(ImGuiTableColumnFlags_DefaultSort_NATIVE()),
    WidthStretch(ImGuiTableColumnFlags_WidthStretch_NATIVE()),
    WidthFixed(ImGuiTableColumnFlags_WidthFixed_NATIVE()),
    NoResize(ImGuiTableColumnFlags_NoResize_NATIVE()),
    NoReorder(ImGuiTableColumnFlags_NoReorder_NATIVE()),
    NoHide(ImGuiTableColumnFlags_NoHide_NATIVE()),
    NoClip(ImGuiTableColumnFlags_NoClip_NATIVE()),
    NoSort(ImGuiTableColumnFlags_NoSort_NATIVE()),
    NoSortAscending(ImGuiTableColumnFlags_NoSortAscending_NATIVE()),
    NoSortDescending(ImGuiTableColumnFlags_NoSortDescending_NATIVE()),
    NoHeaderLabel(ImGuiTableColumnFlags_NoHeaderLabel_NATIVE()),
    NoHeaderWidth(ImGuiTableColumnFlags_NoHeaderWidth_NATIVE()),
    PreferSortAscending(ImGuiTableColumnFlags_PreferSortAscending_NATIVE()),
    PreferSortDescending(ImGuiTableColumnFlags_PreferSortDescending_NATIVE()),
    IndentEnable(ImGuiTableColumnFlags_IndentEnable_NATIVE()),
    IndentDisable(ImGuiTableColumnFlags_IndentDisable_NATIVE()),
    AngledHeader(ImGuiTableColumnFlags_AngledHeader_NATIVE()),
    IsEnabled(ImGuiTableColumnFlags_IsEnabled_NATIVE()),
    IsVisible(ImGuiTableColumnFlags_IsVisible_NATIVE()),
    IsSorted(ImGuiTableColumnFlags_IsSorted_NATIVE()),
    IsHovered(ImGuiTableColumnFlags_IsHovered_NATIVE()),
    WidthMask_(ImGuiTableColumnFlags_WidthMask__NATIVE()),
    IndentMask_(ImGuiTableColumnFlags_IndentMask__NATIVE()),
    StatusMask_(ImGuiTableColumnFlags_StatusMask__NATIVE()),
    NoDirectResize_(ImGuiTableColumnFlags_NoDirectResize__NATIVE());

    private int value;

    private ImGuiTableColumnFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiTableColumnFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiTableColumnFlags getCustom() {
        return CUSTOM;
    }

    private static int ImGuiTableColumnFlags_None_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_None_NATIVE();
    }

    private static int ImGuiTableColumnFlags_Disabled_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_Disabled_NATIVE();
    }

    private static int ImGuiTableColumnFlags_DefaultHide_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_DefaultHide_NATIVE();
    }

    private static int ImGuiTableColumnFlags_DefaultSort_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_DefaultSort_NATIVE();
    }

    private static int ImGuiTableColumnFlags_WidthStretch_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_WidthStretch_NATIVE();
    }

    private static int ImGuiTableColumnFlags_WidthFixed_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_WidthFixed_NATIVE();
    }

    private static int ImGuiTableColumnFlags_NoResize_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_NoResize_NATIVE();
    }

    private static int ImGuiTableColumnFlags_NoReorder_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_NoReorder_NATIVE();
    }

    private static int ImGuiTableColumnFlags_NoHide_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_NoHide_NATIVE();
    }

    private static int ImGuiTableColumnFlags_NoClip_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_NoClip_NATIVE();
    }

    private static int ImGuiTableColumnFlags_NoSort_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_NoSort_NATIVE();
    }

    private static int ImGuiTableColumnFlags_NoSortAscending_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_NoSortAscending_NATIVE();
    }

    private static int ImGuiTableColumnFlags_NoSortDescending_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_NoSortDescending_NATIVE();
    }

    private static int ImGuiTableColumnFlags_NoHeaderLabel_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_NoHeaderLabel_NATIVE();
    }

    private static int ImGuiTableColumnFlags_NoHeaderWidth_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_NoHeaderWidth_NATIVE();
    }

    private static int ImGuiTableColumnFlags_PreferSortAscending_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_PreferSortAscending_NATIVE();
    }

    private static int ImGuiTableColumnFlags_PreferSortDescending_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_PreferSortDescending_NATIVE();
    }

    private static int ImGuiTableColumnFlags_IndentEnable_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_IndentEnable_NATIVE();
    }

    private static int ImGuiTableColumnFlags_IndentDisable_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_IndentDisable_NATIVE();
    }

    private static int ImGuiTableColumnFlags_AngledHeader_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_AngledHeader_NATIVE();
    }

    private static int ImGuiTableColumnFlags_IsEnabled_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_IsEnabled_NATIVE();
    }

    private static int ImGuiTableColumnFlags_IsVisible_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_IsVisible_NATIVE();
    }

    private static int ImGuiTableColumnFlags_IsSorted_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_IsSorted_NATIVE();
    }

    private static int ImGuiTableColumnFlags_IsHovered_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_IsHovered_NATIVE();
    }

    private static int ImGuiTableColumnFlags_WidthMask__NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_WidthMask__NATIVE();
    }

    private static int ImGuiTableColumnFlags_IndentMask__NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_IndentMask__NATIVE();
    }

    private static int ImGuiTableColumnFlags_StatusMask__NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_StatusMask__NATIVE();
    }

    private static int ImGuiTableColumnFlags_NoDirectResize__NATIVE() {
        return imgui.enums.natives.JNI_ImGuiTableColumnFlags.ImGuiTableColumnFlags_NoDirectResize__NATIVE();
    }
}
