/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImGuiCol implements NativeEnum<ImGuiCol> {

    CUSTOM(0),
    Text(ImGuiCol_Text_NATIVE()),
    TextDisabled(ImGuiCol_TextDisabled_NATIVE()),
    WindowBg(ImGuiCol_WindowBg_NATIVE()),
    ChildBg(ImGuiCol_ChildBg_NATIVE()),
    PopupBg(ImGuiCol_PopupBg_NATIVE()),
    Border(ImGuiCol_Border_NATIVE()),
    BorderShadow(ImGuiCol_BorderShadow_NATIVE()),
    FrameBg(ImGuiCol_FrameBg_NATIVE()),
    FrameBgHovered(ImGuiCol_FrameBgHovered_NATIVE()),
    FrameBgActive(ImGuiCol_FrameBgActive_NATIVE()),
    TitleBg(ImGuiCol_TitleBg_NATIVE()),
    TitleBgActive(ImGuiCol_TitleBgActive_NATIVE()),
    TitleBgCollapsed(ImGuiCol_TitleBgCollapsed_NATIVE()),
    MenuBarBg(ImGuiCol_MenuBarBg_NATIVE()),
    ScrollbarBg(ImGuiCol_ScrollbarBg_NATIVE()),
    ScrollbarGrab(ImGuiCol_ScrollbarGrab_NATIVE()),
    ScrollbarGrabHovered(ImGuiCol_ScrollbarGrabHovered_NATIVE()),
    ScrollbarGrabActive(ImGuiCol_ScrollbarGrabActive_NATIVE()),
    CheckMark(ImGuiCol_CheckMark_NATIVE()),
    SliderGrab(ImGuiCol_SliderGrab_NATIVE()),
    SliderGrabActive(ImGuiCol_SliderGrabActive_NATIVE()),
    Button(ImGuiCol_Button_NATIVE()),
    ButtonHovered(ImGuiCol_ButtonHovered_NATIVE()),
    ButtonActive(ImGuiCol_ButtonActive_NATIVE()),
    Header(ImGuiCol_Header_NATIVE()),
    HeaderHovered(ImGuiCol_HeaderHovered_NATIVE()),
    HeaderActive(ImGuiCol_HeaderActive_NATIVE()),
    Separator(ImGuiCol_Separator_NATIVE()),
    SeparatorHovered(ImGuiCol_SeparatorHovered_NATIVE()),
    SeparatorActive(ImGuiCol_SeparatorActive_NATIVE()),
    ResizeGrip(ImGuiCol_ResizeGrip_NATIVE()),
    ResizeGripHovered(ImGuiCol_ResizeGripHovered_NATIVE()),
    ResizeGripActive(ImGuiCol_ResizeGripActive_NATIVE()),
    InputTextCursor(ImGuiCol_InputTextCursor_NATIVE()),
    TabHovered(ImGuiCol_TabHovered_NATIVE()),
    Tab(ImGuiCol_Tab_NATIVE()),
    TabSelected(ImGuiCol_TabSelected_NATIVE()),
    TabSelectedOverline(ImGuiCol_TabSelectedOverline_NATIVE()),
    TabDimmed(ImGuiCol_TabDimmed_NATIVE()),
    TabDimmedSelected(ImGuiCol_TabDimmedSelected_NATIVE()),
    TabDimmedSelectedOverline(ImGuiCol_TabDimmedSelectedOverline_NATIVE()),
    DockingPreview(ImGuiCol_DockingPreview_NATIVE()),
    DockingEmptyBg(ImGuiCol_DockingEmptyBg_NATIVE()),
    PlotLines(ImGuiCol_PlotLines_NATIVE()),
    PlotLinesHovered(ImGuiCol_PlotLinesHovered_NATIVE()),
    PlotHistogram(ImGuiCol_PlotHistogram_NATIVE()),
    PlotHistogramHovered(ImGuiCol_PlotHistogramHovered_NATIVE()),
    TableHeaderBg(ImGuiCol_TableHeaderBg_NATIVE()),
    TableBorderStrong(ImGuiCol_TableBorderStrong_NATIVE()),
    TableBorderLight(ImGuiCol_TableBorderLight_NATIVE()),
    TableRowBg(ImGuiCol_TableRowBg_NATIVE()),
    TableRowBgAlt(ImGuiCol_TableRowBgAlt_NATIVE()),
    TextLink(ImGuiCol_TextLink_NATIVE()),
    TextSelectedBg(ImGuiCol_TextSelectedBg_NATIVE()),
    TreeLines(ImGuiCol_TreeLines_NATIVE()),
    DragDropTarget(ImGuiCol_DragDropTarget_NATIVE()),
    UnsavedMarker(ImGuiCol_UnsavedMarker_NATIVE()),
    NavCursor(ImGuiCol_NavCursor_NATIVE()),
    NavWindowingHighlight(ImGuiCol_NavWindowingHighlight_NATIVE()),
    NavWindowingDimBg(ImGuiCol_NavWindowingDimBg_NATIVE()),
    ModalWindowDimBg(ImGuiCol_ModalWindowDimBg_NATIVE());

    private int value;

    private ImGuiCol(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiCol setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiCol getCustom() {
        return CUSTOM;
    }

    private static int ImGuiCol_Text_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_Text_NATIVE();
    }

    private static int ImGuiCol_TextDisabled_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TextDisabled_NATIVE();
    }

    private static int ImGuiCol_WindowBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_WindowBg_NATIVE();
    }

    private static int ImGuiCol_ChildBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_ChildBg_NATIVE();
    }

    private static int ImGuiCol_PopupBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_PopupBg_NATIVE();
    }

    private static int ImGuiCol_Border_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_Border_NATIVE();
    }

    private static int ImGuiCol_BorderShadow_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_BorderShadow_NATIVE();
    }

    private static int ImGuiCol_FrameBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_FrameBg_NATIVE();
    }

    private static int ImGuiCol_FrameBgHovered_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_FrameBgHovered_NATIVE();
    }

    private static int ImGuiCol_FrameBgActive_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_FrameBgActive_NATIVE();
    }

    private static int ImGuiCol_TitleBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TitleBg_NATIVE();
    }

    private static int ImGuiCol_TitleBgActive_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TitleBgActive_NATIVE();
    }

    private static int ImGuiCol_TitleBgCollapsed_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TitleBgCollapsed_NATIVE();
    }

    private static int ImGuiCol_MenuBarBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_MenuBarBg_NATIVE();
    }

    private static int ImGuiCol_ScrollbarBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_ScrollbarBg_NATIVE();
    }

    private static int ImGuiCol_ScrollbarGrab_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_ScrollbarGrab_NATIVE();
    }

    private static int ImGuiCol_ScrollbarGrabHovered_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_ScrollbarGrabHovered_NATIVE();
    }

    private static int ImGuiCol_ScrollbarGrabActive_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_ScrollbarGrabActive_NATIVE();
    }

    private static int ImGuiCol_CheckMark_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_CheckMark_NATIVE();
    }

    private static int ImGuiCol_SliderGrab_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_SliderGrab_NATIVE();
    }

    private static int ImGuiCol_SliderGrabActive_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_SliderGrabActive_NATIVE();
    }

    private static int ImGuiCol_Button_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_Button_NATIVE();
    }

    private static int ImGuiCol_ButtonHovered_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_ButtonHovered_NATIVE();
    }

    private static int ImGuiCol_ButtonActive_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_ButtonActive_NATIVE();
    }

    private static int ImGuiCol_Header_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_Header_NATIVE();
    }

    private static int ImGuiCol_HeaderHovered_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_HeaderHovered_NATIVE();
    }

    private static int ImGuiCol_HeaderActive_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_HeaderActive_NATIVE();
    }

    private static int ImGuiCol_Separator_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_Separator_NATIVE();
    }

    private static int ImGuiCol_SeparatorHovered_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_SeparatorHovered_NATIVE();
    }

    private static int ImGuiCol_SeparatorActive_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_SeparatorActive_NATIVE();
    }

    private static int ImGuiCol_ResizeGrip_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_ResizeGrip_NATIVE();
    }

    private static int ImGuiCol_ResizeGripHovered_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_ResizeGripHovered_NATIVE();
    }

    private static int ImGuiCol_ResizeGripActive_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_ResizeGripActive_NATIVE();
    }

    private static int ImGuiCol_InputTextCursor_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_InputTextCursor_NATIVE();
    }

    private static int ImGuiCol_TabHovered_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TabHovered_NATIVE();
    }

    private static int ImGuiCol_Tab_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_Tab_NATIVE();
    }

    private static int ImGuiCol_TabSelected_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TabSelected_NATIVE();
    }

    private static int ImGuiCol_TabSelectedOverline_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TabSelectedOverline_NATIVE();
    }

    private static int ImGuiCol_TabDimmed_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TabDimmed_NATIVE();
    }

    private static int ImGuiCol_TabDimmedSelected_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TabDimmedSelected_NATIVE();
    }

    private static int ImGuiCol_TabDimmedSelectedOverline_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TabDimmedSelectedOverline_NATIVE();
    }

    private static int ImGuiCol_DockingPreview_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_DockingPreview_NATIVE();
    }

    private static int ImGuiCol_DockingEmptyBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_DockingEmptyBg_NATIVE();
    }

    private static int ImGuiCol_PlotLines_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_PlotLines_NATIVE();
    }

    private static int ImGuiCol_PlotLinesHovered_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_PlotLinesHovered_NATIVE();
    }

    private static int ImGuiCol_PlotHistogram_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_PlotHistogram_NATIVE();
    }

    private static int ImGuiCol_PlotHistogramHovered_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_PlotHistogramHovered_NATIVE();
    }

    private static int ImGuiCol_TableHeaderBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TableHeaderBg_NATIVE();
    }

    private static int ImGuiCol_TableBorderStrong_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TableBorderStrong_NATIVE();
    }

    private static int ImGuiCol_TableBorderLight_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TableBorderLight_NATIVE();
    }

    private static int ImGuiCol_TableRowBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TableRowBg_NATIVE();
    }

    private static int ImGuiCol_TableRowBgAlt_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TableRowBgAlt_NATIVE();
    }

    private static int ImGuiCol_TextLink_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TextLink_NATIVE();
    }

    private static int ImGuiCol_TextSelectedBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TextSelectedBg_NATIVE();
    }

    private static int ImGuiCol_TreeLines_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_TreeLines_NATIVE();
    }

    private static int ImGuiCol_DragDropTarget_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_DragDropTarget_NATIVE();
    }

    private static int ImGuiCol_UnsavedMarker_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_UnsavedMarker_NATIVE();
    }

    private static int ImGuiCol_NavCursor_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_NavCursor_NATIVE();
    }

    private static int ImGuiCol_NavWindowingHighlight_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_NavWindowingHighlight_NATIVE();
    }

    private static int ImGuiCol_NavWindowingDimBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_NavWindowingDimBg_NATIVE();
    }

    private static int ImGuiCol_ModalWindowDimBg_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiCol.ImGuiCol_ModalWindowDimBg_NATIVE();
    }
}
