/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImGuiSelectableFlagsPrivate_ implements NativeEnum<ImGuiSelectableFlagsPrivate_> {

    CUSTOM(0),
    NoHoldingActiveID(ImGuiSelectableFlags_NoHoldingActiveID_NATIVE()),
    SelectOnClick(ImGuiSelectableFlags_SelectOnClick_NATIVE()),
    SelectOnRelease(ImGuiSelectableFlags_SelectOnRelease_NATIVE()),
    SpanAvailWidth(ImGuiSelectableFlags_SpanAvailWidth_NATIVE()),
    SetNavIdOnHover(ImGuiSelectableFlags_SetNavIdOnHover_NATIVE()),
    NoPadWithHalfSpacing(ImGuiSelectableFlags_NoPadWithHalfSpacing_NATIVE()),
    NoSetKeyOwner(ImGuiSelectableFlags_NoSetKeyOwner_NATIVE());

    private int value;

    private ImGuiSelectableFlagsPrivate_(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiSelectableFlagsPrivate_ setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiSelectableFlagsPrivate_ getCustom() {
        return CUSTOM;
    }

    private static int ImGuiSelectableFlags_NoHoldingActiveID_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSelectableFlagsPrivate_.ImGuiSelectableFlags_NoHoldingActiveID_NATIVE();
    }

    private static int ImGuiSelectableFlags_SelectOnClick_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSelectableFlagsPrivate_.ImGuiSelectableFlags_SelectOnClick_NATIVE();
    }

    private static int ImGuiSelectableFlags_SelectOnRelease_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSelectableFlagsPrivate_.ImGuiSelectableFlags_SelectOnRelease_NATIVE();
    }

    private static int ImGuiSelectableFlags_SpanAvailWidth_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSelectableFlagsPrivate_.ImGuiSelectableFlags_SpanAvailWidth_NATIVE();
    }

    private static int ImGuiSelectableFlags_SetNavIdOnHover_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSelectableFlagsPrivate_.ImGuiSelectableFlags_SetNavIdOnHover_NATIVE();
    }

    private static int ImGuiSelectableFlags_NoPadWithHalfSpacing_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSelectableFlagsPrivate_.ImGuiSelectableFlags_NoPadWithHalfSpacing_NATIVE();
    }

    private static int ImGuiSelectableFlags_NoSetKeyOwner_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiSelectableFlagsPrivate_.ImGuiSelectableFlags_NoSetKeyOwner_NATIVE();
    }
}
