/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImGuiInputTextFlags implements NativeEnum<ImGuiInputTextFlags> {

    CUSTOM(0),
    None(ImGuiInputTextFlags_None_NATIVE()),
    CharsDecimal(ImGuiInputTextFlags_CharsDecimal_NATIVE()),
    CharsHexadecimal(ImGuiInputTextFlags_CharsHexadecimal_NATIVE()),
    CharsScientific(ImGuiInputTextFlags_CharsScientific_NATIVE()),
    CharsUppercase(ImGuiInputTextFlags_CharsUppercase_NATIVE()),
    CharsNoBlank(ImGuiInputTextFlags_CharsNoBlank_NATIVE()),
    AllowTabInput(ImGuiInputTextFlags_AllowTabInput_NATIVE()),
    EnterReturnsTrue(ImGuiInputTextFlags_EnterReturnsTrue_NATIVE()),
    EscapeClearsAll(ImGuiInputTextFlags_EscapeClearsAll_NATIVE()),
    CtrlEnterForNewLine(ImGuiInputTextFlags_CtrlEnterForNewLine_NATIVE()),
    ReadOnly(ImGuiInputTextFlags_ReadOnly_NATIVE()),
    Password(ImGuiInputTextFlags_Password_NATIVE()),
    AlwaysOverwrite(ImGuiInputTextFlags_AlwaysOverwrite_NATIVE()),
    AutoSelectAll(ImGuiInputTextFlags_AutoSelectAll_NATIVE()),
    ParseEmptyRefVal(ImGuiInputTextFlags_ParseEmptyRefVal_NATIVE()),
    DisplayEmptyRefVal(ImGuiInputTextFlags_DisplayEmptyRefVal_NATIVE()),
    NoHorizontalScroll(ImGuiInputTextFlags_NoHorizontalScroll_NATIVE()),
    NoUndoRedo(ImGuiInputTextFlags_NoUndoRedo_NATIVE()),
    ElideLeft(ImGuiInputTextFlags_ElideLeft_NATIVE()),
    CallbackCompletion(ImGuiInputTextFlags_CallbackCompletion_NATIVE()),
    CallbackHistory(ImGuiInputTextFlags_CallbackHistory_NATIVE()),
    CallbackAlways(ImGuiInputTextFlags_CallbackAlways_NATIVE()),
    CallbackCharFilter(ImGuiInputTextFlags_CallbackCharFilter_NATIVE()),
    CallbackResize(ImGuiInputTextFlags_CallbackResize_NATIVE()),
    CallbackEdit(ImGuiInputTextFlags_CallbackEdit_NATIVE()),
    WordWrap(ImGuiInputTextFlags_WordWrap_NATIVE());

    private int value;

    private ImGuiInputTextFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiInputTextFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiInputTextFlags getCustom() {
        return CUSTOM;
    }

    private static int ImGuiInputTextFlags_None_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_None_NATIVE();
    }

    private static int ImGuiInputTextFlags_CharsDecimal_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CharsDecimal_NATIVE();
    }

    private static int ImGuiInputTextFlags_CharsHexadecimal_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CharsHexadecimal_NATIVE();
    }

    private static int ImGuiInputTextFlags_CharsScientific_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CharsScientific_NATIVE();
    }

    private static int ImGuiInputTextFlags_CharsUppercase_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CharsUppercase_NATIVE();
    }

    private static int ImGuiInputTextFlags_CharsNoBlank_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CharsNoBlank_NATIVE();
    }

    private static int ImGuiInputTextFlags_AllowTabInput_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_AllowTabInput_NATIVE();
    }

    private static int ImGuiInputTextFlags_EnterReturnsTrue_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_EnterReturnsTrue_NATIVE();
    }

    private static int ImGuiInputTextFlags_EscapeClearsAll_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_EscapeClearsAll_NATIVE();
    }

    private static int ImGuiInputTextFlags_CtrlEnterForNewLine_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CtrlEnterForNewLine_NATIVE();
    }

    private static int ImGuiInputTextFlags_ReadOnly_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_ReadOnly_NATIVE();
    }

    private static int ImGuiInputTextFlags_Password_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_Password_NATIVE();
    }

    private static int ImGuiInputTextFlags_AlwaysOverwrite_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_AlwaysOverwrite_NATIVE();
    }

    private static int ImGuiInputTextFlags_AutoSelectAll_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_AutoSelectAll_NATIVE();
    }

    private static int ImGuiInputTextFlags_ParseEmptyRefVal_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_ParseEmptyRefVal_NATIVE();
    }

    private static int ImGuiInputTextFlags_DisplayEmptyRefVal_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_DisplayEmptyRefVal_NATIVE();
    }

    private static int ImGuiInputTextFlags_NoHorizontalScroll_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_NoHorizontalScroll_NATIVE();
    }

    private static int ImGuiInputTextFlags_NoUndoRedo_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_NoUndoRedo_NATIVE();
    }

    private static int ImGuiInputTextFlags_ElideLeft_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_ElideLeft_NATIVE();
    }

    private static int ImGuiInputTextFlags_CallbackCompletion_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CallbackCompletion_NATIVE();
    }

    private static int ImGuiInputTextFlags_CallbackHistory_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CallbackHistory_NATIVE();
    }

    private static int ImGuiInputTextFlags_CallbackAlways_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CallbackAlways_NATIVE();
    }

    private static int ImGuiInputTextFlags_CallbackCharFilter_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CallbackCharFilter_NATIVE();
    }

    private static int ImGuiInputTextFlags_CallbackResize_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CallbackResize_NATIVE();
    }

    private static int ImGuiInputTextFlags_CallbackEdit_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_CallbackEdit_NATIVE();
    }

    private static int ImGuiInputTextFlags_WordWrap_NATIVE() {
        return imgui.enums.natives.JNI_ImGuiInputTextFlags.ImGuiInputTextFlags_WordWrap_NATIVE();
    }
}
