/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ClipboardTextFunction extends NativeObject {

    static private NativeString NativeString_TEMP_STATIC_GEN_0;

    static private NativeString NativeString_TEMP_STATIC_GEN_1;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_onGetClipboardText = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetClipboardText = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onSetClipboardText = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onSetClipboardText = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    static public final ClipboardTextFunction NULL = ClipboardTextFunction.native_new();

    @Deprecated()
    protected ClipboardTextFunction(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ClipboardTextFunction native_new() {
        return new ClipboardTextFunction((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void setClipboardTextFunction(ImGuiPlatformIO io, ClipboardTextFunction clipboardFunction) {
        internal_native_setClipboardTextFunction(io.native_address, clipboardFunction.native_address);
    }

    public static void internal_native_setClipboardTextFunction(long io_addr, long clipboardFunction_addr) {
        try {
            FFMHandles.internal_native_setClipboardTextFunction__JJ.invokeExact(io_addr, clipboardFunction_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ClipboardTextFunction() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_onGetClipboardText = callbackLookup.findVirtual(ClipboardTextFunction.class, "internal_onGetClipboardText", callbackMethodType_onGetClipboardText).bindTo(this);
            upcallStub_onGetClipboardText = callbackLinker.upcallStub(mh_onGetClipboardText, callbackDescriptor_onGetClipboardText, upcallArena);
            java.lang.invoke.MethodHandle mh_onSetClipboardText = callbackLookup.findVirtual(ClipboardTextFunction.class, "internal_onSetClipboardText", callbackMethodType_onSetClipboardText).bindTo(this);
            upcallStub_onSetClipboardText = callbackLinker.upcallStub(mh_onSetClipboardText, callbackDescriptor_onSetClipboardText, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_onGetClipboardText.address(), upcallStub_onSetClipboardText.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected void onGetClipboardText(NativeString strOut) {
    }

    private void internal_onGetClipboardText(long strOut_addr) {
        if (NativeString_TEMP_STATIC_GEN_0 == null)
            NativeString_TEMP_STATIC_GEN_0 = NativeString.native_new();
        NativeString_TEMP_STATIC_GEN_0.internal_reset(strOut_addr, false);
        onGetClipboardText(NativeString_TEMP_STATIC_GEN_0);
    }

    protected void onSetClipboardText(NativeString text) {
    }

    private void internal_onSetClipboardText(long text_addr) {
        if (NativeString_TEMP_STATIC_GEN_1 == null)
            NativeString_TEMP_STATIC_GEN_1 = NativeString.native_new();
        NativeString_TEMP_STATIC_GEN_1.internal_reset(text_addr, false);
        onSetClipboardText(NativeString_TEMP_STATIC_GEN_1);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_onGetClipboardText;

    private MemorySegment upcallStub_onSetClipboardText;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_onGetClipboardText = null;
        upcallStub_onSetClipboardText = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long onGetClipboardText_fp, long onSetClipboardText_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJJ.invokeExact(this_addr, onGetClipboardText_fp, onSetClipboardText_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_clipboardtextfunction_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setClipboardTextFunction__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_clipboardtextfunction_setclipboardtextfunction", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_clipboardtextfunction_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_clipboardtextfunction_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
