/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ImFontConfig extends NativeObject {

    private NativeObject NativeObject_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_0;

    static public final ImFontConfig NULL = ImFontConfig.native_new();

    public ImFontConfig() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImFontConfig(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImFontConfig native_new() {
        return new ImFontConfig((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public byte get_Name(int index) {
        return internal_native_get_Name(native_address, index);
    }

    public static byte internal_native_get_Name(long this_addr, int index) {
        try {
            return (byte) FFMHandles.internal_native_get_Name__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_Name(int index, byte Name) {
        internal_native_set_Name(native_address, index, Name);
    }

    public static void internal_native_set_Name(long this_addr, int index, byte Name) {
        try {
            FFMHandles.internal_native_set_Name__JIB.invokeExact(this_addr, index, Name);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeObject get_FontData() {
        long addr = internal_native_get_FontData_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    public static long internal_native_get_FontData_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_FontData_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_FontData(NativeObject FontData) {
        internal_native_set_FontData(native_address, FontData.native_void_address);
    }

    public static void internal_native_set_FontData(long this_addr, long FontData_addr) {
        try {
            FFMHandles.internal_native_set_FontData__JJ.invokeExact(this_addr, FontData_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_FontDataSize() {
        return internal_native_get_FontDataSize(native_address);
    }

    public static int internal_native_get_FontDataSize(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_FontDataSize__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_FontDataSize(int FontDataSize) {
        internal_native_set_FontDataSize(native_address, FontDataSize);
    }

    public static void internal_native_set_FontDataSize(long this_addr, int FontDataSize) {
        try {
            FFMHandles.internal_native_set_FontDataSize__JI.invokeExact(this_addr, FontDataSize);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_FontDataOwnedByAtlas() {
        return internal_native_get_FontDataOwnedByAtlas(native_address);
    }

    public static boolean internal_native_get_FontDataOwnedByAtlas(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_FontDataOwnedByAtlas__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_FontDataOwnedByAtlas(boolean FontDataOwnedByAtlas) {
        internal_native_set_FontDataOwnedByAtlas(native_address, FontDataOwnedByAtlas);
    }

    public static void internal_native_set_FontDataOwnedByAtlas(long this_addr, boolean FontDataOwnedByAtlas) {
        try {
            FFMHandles.internal_native_set_FontDataOwnedByAtlas__JZ.invokeExact(this_addr, FontDataOwnedByAtlas);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_MergeMode() {
        return internal_native_get_MergeMode(native_address);
    }

    public static boolean internal_native_get_MergeMode(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_MergeMode__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_MergeMode(boolean MergeMode) {
        internal_native_set_MergeMode(native_address, MergeMode);
    }

    public static void internal_native_set_MergeMode(long this_addr, boolean MergeMode) {
        try {
            FFMHandles.internal_native_set_MergeMode__JZ.invokeExact(this_addr, MergeMode);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_PixelSnapH() {
        return internal_native_get_PixelSnapH(native_address);
    }

    public static boolean internal_native_get_PixelSnapH(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_PixelSnapH__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_PixelSnapH(boolean PixelSnapH) {
        internal_native_set_PixelSnapH(native_address, PixelSnapH);
    }

    public static void internal_native_set_PixelSnapH(long this_addr, boolean PixelSnapH) {
        try {
            FFMHandles.internal_native_set_PixelSnapH__JZ.invokeExact(this_addr, PixelSnapH);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_PixelSnapV() {
        return internal_native_get_PixelSnapV(native_address);
    }

    public static boolean internal_native_get_PixelSnapV(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_PixelSnapV__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_PixelSnapV(boolean PixelSnapV) {
        internal_native_set_PixelSnapV(native_address, PixelSnapV);
    }

    public static void internal_native_set_PixelSnapV(long this_addr, boolean PixelSnapV) {
        try {
            FFMHandles.internal_native_set_PixelSnapV__JZ.invokeExact(this_addr, PixelSnapV);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_OversampleH() {
        return internal_native_get_OversampleH(native_address);
    }

    public static int internal_native_get_OversampleH(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_OversampleH__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OversampleH(int OversampleH) {
        internal_native_set_OversampleH(native_address, OversampleH);
    }

    public static void internal_native_set_OversampleH(long this_addr, int OversampleH) {
        try {
            FFMHandles.internal_native_set_OversampleH__JI.invokeExact(this_addr, OversampleH);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_OversampleV() {
        return internal_native_get_OversampleV(native_address);
    }

    public static int internal_native_get_OversampleV(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_OversampleV__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_OversampleV(int OversampleV) {
        internal_native_set_OversampleV(native_address, OversampleV);
    }

    public static void internal_native_set_OversampleV(long this_addr, int OversampleV) {
        try {
            FFMHandles.internal_native_set_OversampleV__JI.invokeExact(this_addr, OversampleV);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public short get_EllipsisChar() {
        return internal_native_get_EllipsisChar(native_address);
    }

    public static short internal_native_get_EllipsisChar(long this_addr) {
        try {
            return (short) FFMHandles.internal_native_get_EllipsisChar__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_EllipsisChar(short EllipsisChar) {
        internal_native_set_EllipsisChar(native_address, EllipsisChar);
    }

    public static void internal_native_set_EllipsisChar(long this_addr, short EllipsisChar) {
        try {
            FFMHandles.internal_native_set_EllipsisChar__JS.invokeExact(this_addr, EllipsisChar);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_SizePixels() {
        return internal_native_get_SizePixels(native_address);
    }

    public static float internal_native_get_SizePixels(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_SizePixels__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_SizePixels(float SizePixels) {
        internal_native_set_SizePixels(native_address, SizePixels);
    }

    public static void internal_native_set_SizePixels(long this_addr, float SizePixels) {
        try {
            FFMHandles.internal_native_set_SizePixels__JF.invokeExact(this_addr, SizePixels);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImVec2 get_GlyphOffset() {
        long addr = internal_native_get_GlyphOffset_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_0 == null)
            ImVec2_TEMP_GEN_0 = ImVec2.native_new();
        ImVec2_TEMP_GEN_0.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_0;
    }

    public static long internal_native_get_GlyphOffset_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_GlyphOffset_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_GlyphOffset(ImVec2 GlyphOffset) {
        internal_native_set_GlyphOffset(native_address, GlyphOffset.native_address);
    }

    public static void internal_native_set_GlyphOffset(long this_addr, long GlyphOffset_addr) {
        try {
            FFMHandles.internal_native_set_GlyphOffset__JJ.invokeExact(this_addr, GlyphOffset_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_GlyphMinAdvanceX() {
        return internal_native_get_GlyphMinAdvanceX(native_address);
    }

    public static float internal_native_get_GlyphMinAdvanceX(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_GlyphMinAdvanceX__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_GlyphMinAdvanceX(float GlyphMinAdvanceX) {
        internal_native_set_GlyphMinAdvanceX(native_address, GlyphMinAdvanceX);
    }

    public static void internal_native_set_GlyphMinAdvanceX(long this_addr, float GlyphMinAdvanceX) {
        try {
            FFMHandles.internal_native_set_GlyphMinAdvanceX__JF.invokeExact(this_addr, GlyphMinAdvanceX);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_GlyphMaxAdvanceX() {
        return internal_native_get_GlyphMaxAdvanceX(native_address);
    }

    public static float internal_native_get_GlyphMaxAdvanceX(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_GlyphMaxAdvanceX__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_GlyphMaxAdvanceX(float GlyphMaxAdvanceX) {
        internal_native_set_GlyphMaxAdvanceX(native_address, GlyphMaxAdvanceX);
    }

    public static void internal_native_set_GlyphMaxAdvanceX(long this_addr, float GlyphMaxAdvanceX) {
        try {
            FFMHandles.internal_native_set_GlyphMaxAdvanceX__JF.invokeExact(this_addr, GlyphMaxAdvanceX);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_GlyphExtraAdvanceX() {
        return internal_native_get_GlyphExtraAdvanceX(native_address);
    }

    public static float internal_native_get_GlyphExtraAdvanceX(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_GlyphExtraAdvanceX__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_GlyphExtraAdvanceX(float GlyphExtraAdvanceX) {
        internal_native_set_GlyphExtraAdvanceX(native_address, GlyphExtraAdvanceX);
    }

    public static void internal_native_set_GlyphExtraAdvanceX(long this_addr, float GlyphExtraAdvanceX) {
        try {
            FFMHandles.internal_native_set_GlyphExtraAdvanceX__JF.invokeExact(this_addr, GlyphExtraAdvanceX);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_FontNo() {
        return internal_native_get_FontNo(native_address);
    }

    public static int internal_native_get_FontNo(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_FontNo__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_FontNo(int FontNo) {
        internal_native_set_FontNo(native_address, FontNo);
    }

    public static void internal_native_set_FontNo(long this_addr, int FontNo) {
        try {
            FFMHandles.internal_native_set_FontNo__JI.invokeExact(this_addr, FontNo);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_FontLoaderFlags() {
        return internal_native_get_FontLoaderFlags(native_address);
    }

    public static int internal_native_get_FontLoaderFlags(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_FontLoaderFlags__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_FontLoaderFlags(int FontLoaderFlags) {
        internal_native_set_FontLoaderFlags(native_address, FontLoaderFlags);
    }

    public static void internal_native_set_FontLoaderFlags(long this_addr, int FontLoaderFlags) {
        try {
            FFMHandles.internal_native_set_FontLoaderFlags__JI.invokeExact(this_addr, FontLoaderFlags);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_RasterizerMultiply() {
        return internal_native_get_RasterizerMultiply(native_address);
    }

    public static float internal_native_get_RasterizerMultiply(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_RasterizerMultiply__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_RasterizerMultiply(float RasterizerMultiply) {
        internal_native_set_RasterizerMultiply(native_address, RasterizerMultiply);
    }

    public static void internal_native_set_RasterizerMultiply(long this_addr, float RasterizerMultiply) {
        try {
            FFMHandles.internal_native_set_RasterizerMultiply__JF.invokeExact(this_addr, RasterizerMultiply);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_RasterizerDensity() {
        return internal_native_get_RasterizerDensity(native_address);
    }

    public static float internal_native_get_RasterizerDensity(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_RasterizerDensity__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_RasterizerDensity(float RasterizerDensity) {
        internal_native_set_RasterizerDensity(native_address, RasterizerDensity);
    }

    public static void internal_native_set_RasterizerDensity(long this_addr, float RasterizerDensity) {
        try {
            FFMHandles.internal_native_set_RasterizerDensity__JF.invokeExact(this_addr, RasterizerDensity);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imfontconfig_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_Name__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_name", FunctionDescriptor.of(ValueLayout.JAVA_BYTE, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_set_Name__JIB = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_name", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_BYTE));

        static final java.lang.invoke.MethodHandle internal_native_get_FontData_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_fontdata_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_FontData__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_fontdata", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_FontDataSize__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_fontdatasize", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_FontDataSize__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_fontdatasize", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_FontDataOwnedByAtlas__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_fontdataownedbyatlas", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_FontDataOwnedByAtlas__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_fontdataownedbyatlas", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_MergeMode__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_mergemode", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_MergeMode__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_mergemode", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_PixelSnapH__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_pixelsnaph", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_PixelSnapH__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_pixelsnaph", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_PixelSnapV__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_pixelsnapv", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_PixelSnapV__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_pixelsnapv", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_OversampleH__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_oversampleh", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OversampleH__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_oversampleh", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_OversampleV__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_oversamplev", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_OversampleV__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_oversamplev", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_EllipsisChar__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_ellipsischar", FunctionDescriptor.of(ValueLayout.JAVA_SHORT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_EllipsisChar__JS = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_ellipsischar", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_SHORT));

        static final java.lang.invoke.MethodHandle internal_native_get_SizePixels__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_sizepixels", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_SizePixels__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_sizepixels", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_GlyphOffset_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_glyphoffset_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_GlyphOffset__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_glyphoffset", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_GlyphMinAdvanceX__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_glyphminadvancex", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_GlyphMinAdvanceX__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_glyphminadvancex", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_GlyphMaxAdvanceX__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_glyphmaxadvancex", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_GlyphMaxAdvanceX__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_glyphmaxadvancex", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_GlyphExtraAdvanceX__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_glyphextraadvancex", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_GlyphExtraAdvanceX__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_glyphextraadvancex", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_FontNo__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_fontno", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_FontNo__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_fontno", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_FontLoaderFlags__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_fontloaderflags", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_FontLoaderFlags__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_fontloaderflags", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_RasterizerMultiply__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_rasterizermultiply", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_RasterizerMultiply__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_rasterizermultiply", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_RasterizerDensity__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_get_rasterizerdensity", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_RasterizerDensity__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontconfig_set_rasterizerdensity", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));
    }
}
