/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import imgui.enums.ImGuiInputTextFlags;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ImGuiInputTextCallbackData extends NativeObject {

    static public final ImGuiInputTextCallbackData NULL = ImGuiInputTextCallbackData.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiInputTextCallbackData(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiInputTextCallbackData native_new() {
        return new ImGuiInputTextCallbackData((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
ImGuiInputTextCallbackData* nativeObject = (ImGuiInputTextCallbackData*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public int get_BufSize() {
        return internal_native_get_BufSize(native_address);
    }

    /*[-FFM;-NATIVE]
ImGuiInputTextCallbackData* nativeObject = (ImGuiInputTextCallbackData*)this_addr;
return nativeObject->BufSize;
*/
    public static int internal_native_get_BufSize(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_BufSize__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void set_BufSize(int BufSize) {
        internal_native_set_BufSize(native_address, BufSize);
    }

    /*[-FFM;-NATIVE]
ImGuiInputTextCallbackData* nativeObject = (ImGuiInputTextCallbackData*)this_addr;
nativeObject->BufSize = BufSize;
*/
    public static void internal_native_set_BufSize(long this_addr, int BufSize) {
        try {
            FFMHandles.internal_native_set_BufSize__JI.invokeExact(this_addr, BufSize);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public boolean get_BufDirty() {
        return internal_native_get_BufDirty(native_address);
    }

    /*[-FFM;-NATIVE]
ImGuiInputTextCallbackData* nativeObject = (ImGuiInputTextCallbackData*)this_addr;
return nativeObject->BufDirty;
*/
    public static boolean internal_native_get_BufDirty(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_BufDirty__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void set_BufDirty(boolean BufDirty) {
        internal_native_set_BufDirty(native_address, BufDirty);
    }

    /*[-FFM;-NATIVE]
ImGuiInputTextCallbackData* nativeObject = (ImGuiInputTextCallbackData*)this_addr;
nativeObject->BufDirty = BufDirty;
*/
    public static void internal_native_set_BufDirty(long this_addr, boolean BufDirty) {
        try {
            FFMHandles.internal_native_set_BufDirty__JZ.invokeExact(this_addr, BufDirty);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public int get_BufTextLen() {
        return internal_native_get_BufTextLen(native_address);
    }

    /*[-FFM;-NATIVE]
ImGuiInputTextCallbackData* nativeObject = (ImGuiInputTextCallbackData*)this_addr;
return nativeObject->BufTextLen;
*/
    public static int internal_native_get_BufTextLen(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_BufTextLen__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void set_BufTextLen(int BufTextLen) {
        internal_native_set_BufTextLen(native_address, BufTextLen);
    }

    /*[-FFM;-NATIVE]
ImGuiInputTextCallbackData* nativeObject = (ImGuiInputTextCallbackData*)this_addr;
nativeObject->BufTextLen = BufTextLen;
*/
    public static void internal_native_set_BufTextLen(long this_addr, int BufTextLen) {
        try {
            FFMHandles.internal_native_set_BufTextLen__JI.invokeExact(this_addr, BufTextLen);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public ImGuiInputTextFlags get_Flags() {
        int value = internal_native_get_Flags(native_address);
        ImGuiInputTextFlags[] values = ImGuiInputTextFlags.values();
        for (int i = 0; i < values.length; i++) {
            ImGuiInputTextFlags enumVal = values[i];
            if (enumVal != ImGuiInputTextFlags.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return ImGuiInputTextFlags.CUSTOM.setValue(value);
    }

    /*[-FFM;-NATIVE]
ImGuiInputTextCallbackData* nativeObject = (ImGuiInputTextCallbackData*)this_addr;
return (int32_t)nativeObject->Flags;
*/
    public static int internal_native_get_Flags(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_Flags__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void set_Flags(ImGuiInputTextFlags Flags) {
        internal_native_set_Flags(native_address, Flags.getValue());
    }

    /*[-FFM;-NATIVE]
ImGuiInputTextCallbackData* nativeObject = (ImGuiInputTextCallbackData*)this_addr;
nativeObject->Flags = (::ImGuiInputTextFlags)Flags;
*/
    public static void internal_native_set_Flags(long this_addr, int Flags) {
        try {
            FFMHandles.internal_native_set_Flags__JI.invokeExact(this_addr, Flags);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_CRITICAL = new java.lang.foreign.Linker.Option[] { java.lang.foreign.Linker.Option.critical(true) };

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_DEFAULT = new java.lang.foreign.Linker.Option[0];

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static RuntimeException rethrow(Throwable e) {
            if (e instanceof RuntimeException)
                return (RuntimeException) e;
            if (e instanceof Error)
                throw (Error) e;
            return new RuntimeException(e);
        }

        static java.lang.invoke.MethodHandle downcallDefault(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
        }

        static java.lang.invoke.MethodHandle downcallCritical(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            try {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_CRITICAL);
            } catch (Throwable ignored) {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
            }
        }

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = downcallDefault("jparser_imgui_ImGuiInputTextCallbackData_internal_1native_1deleteNative__J", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_BufSize__J = downcallDefault("jparser_imgui_ImGuiInputTextCallbackData_internal_1native_1get_1BufSize__J", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_BufSize__JI = downcallDefault("jparser_imgui_ImGuiInputTextCallbackData_internal_1native_1set_1BufSize__JI", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_BufDirty__J = downcallDefault("jparser_imgui_ImGuiInputTextCallbackData_internal_1native_1get_1BufDirty__J", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_BufDirty__JZ = downcallDefault("jparser_imgui_ImGuiInputTextCallbackData_internal_1native_1set_1BufDirty__JZ", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_BufTextLen__J = downcallDefault("jparser_imgui_ImGuiInputTextCallbackData_internal_1native_1get_1BufTextLen__J", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_BufTextLen__JI = downcallDefault("jparser_imgui_ImGuiInputTextCallbackData_internal_1native_1set_1BufTextLen__JI", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_Flags__J = downcallDefault("jparser_imgui_ImGuiInputTextCallbackData_internal_1native_1get_1Flags__J", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_Flags__JI = downcallDefault("jparser_imgui_ImGuiInputTextCallbackData_internal_1native_1set_1Flags__JI", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    }
}
