/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ImGuiTabBar extends NativeObject {

    static public final ImGuiTabBar NULL = ImGuiTabBar.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiTabBar(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiTabBar native_new() {
        return new ImGuiTabBar((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
ImGuiTabBar* nativeObject = (ImGuiTabBar*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public int get_SelectedTabId() {
        return internal_native_get_SelectedTabId(native_address);
    }

    /*[-FFM;-NATIVE]
ImGuiTabBar* nativeObject = (ImGuiTabBar*)this_addr;
return nativeObject->SelectedTabId;
*/
    public static int internal_native_get_SelectedTabId(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_SelectedTabId__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void set_SelectedTabId(int SelectedTabId) {
        internal_native_set_SelectedTabId(native_address, SelectedTabId);
    }

    /*[-FFM;-NATIVE]
ImGuiTabBar* nativeObject = (ImGuiTabBar*)this_addr;
nativeObject->SelectedTabId = SelectedTabId;
*/
    public static void internal_native_set_SelectedTabId(long this_addr, int SelectedTabId) {
        try {
            FFMHandles.internal_native_set_SelectedTabId__JI.invokeExact(this_addr, SelectedTabId);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public int get_NextSelectedTabId() {
        return internal_native_get_NextSelectedTabId(native_address);
    }

    /*[-FFM;-NATIVE]
ImGuiTabBar* nativeObject = (ImGuiTabBar*)this_addr;
return nativeObject->NextSelectedTabId;
*/
    public static int internal_native_get_NextSelectedTabId(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_NextSelectedTabId__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void set_NextSelectedTabId(int NextSelectedTabId) {
        internal_native_set_NextSelectedTabId(native_address, NextSelectedTabId);
    }

    /*[-FFM;-NATIVE]
ImGuiTabBar* nativeObject = (ImGuiTabBar*)this_addr;
nativeObject->NextSelectedTabId = NextSelectedTabId;
*/
    public static void internal_native_set_NextSelectedTabId(long this_addr, int NextSelectedTabId) {
        try {
            FFMHandles.internal_native_set_NextSelectedTabId__JI.invokeExact(this_addr, NextSelectedTabId);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_CRITICAL = new java.lang.foreign.Linker.Option[] { java.lang.foreign.Linker.Option.critical(true) };

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_DEFAULT = new java.lang.foreign.Linker.Option[0];

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static RuntimeException rethrow(Throwable e) {
            if (e instanceof RuntimeException)
                return (RuntimeException) e;
            if (e instanceof Error)
                throw (Error) e;
            return new RuntimeException(e);
        }

        static java.lang.invoke.MethodHandle downcallDefault(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
        }

        static java.lang.invoke.MethodHandle downcallCritical(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            try {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_CRITICAL);
            } catch (Throwable ignored) {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
            }
        }

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = downcallDefault("jparser_imgui_ImGuiTabBar_internal_1native_1deleteNative__J", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_SelectedTabId__J = downcallDefault("jparser_imgui_ImGuiTabBar_internal_1native_1get_1SelectedTabId__J", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_SelectedTabId__JI = downcallDefault("jparser_imgui_ImGuiTabBar_internal_1native_1set_1SelectedTabId__JI", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_NextSelectedTabId__J = downcallDefault("jparser_imgui_ImGuiTabBar_internal_1native_1get_1NextSelectedTabId__J", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_NextSelectedTabId__JI = downcallDefault("jparser_imgui_ImGuiTabBar_internal_1native_1set_1NextSelectedTabId__JI", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    }
}
