/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ImGuiStorage extends NativeObject {

    private NativeObject NativeObject_TEMP_GEN_0;

    private ImVectorImGuiStoragePair ImVectorImGuiStoragePair_TEMP_GEN_0;

    static public final ImGuiStorage NULL = ImGuiStorage.native_new();

    public ImGuiStorage() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    /*[-FFM;-NATIVE]
return (int64_t)new ImGuiStorage();
*/
    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiStorage(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiStorage native_new() {
        return new ImGuiStorage((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void Clear() {
        internal_native_Clear(native_address);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
nativeObject->Clear();
*/
    public static void internal_native_Clear(long this_addr) {
        try {
            FFMHandles.internal_native_Clear__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public int GetInt(int key, int default_val) {
        return internal_native_GetInt(native_address, key, default_val);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
return nativeObject->GetInt((int)key, (int)default_val);
*/
    public static int internal_native_GetInt(long this_addr, int key, int default_val) {
        try {
            return (int) FFMHandles.internal_native_GetInt__JII.invokeExact(this_addr, key, default_val);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public int GetInt(int key) {
        return internal_native_GetInt(native_address, key);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
return nativeObject->GetInt((int)key);
*/
    public static int internal_native_GetInt(long this_addr, int key) {
        try {
            return (int) FFMHandles.internal_native_GetInt__JI.invokeExact(this_addr, key);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void SetInt(int key, int val) {
        internal_native_SetInt(native_address, key, val);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
nativeObject->SetInt((int)key, (int)val);
*/
    public static void internal_native_SetInt(long this_addr, int key, int val) {
        try {
            FFMHandles.internal_native_SetInt__JII.invokeExact(this_addr, key, val);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public boolean GetBool(int key, boolean default_val) {
        return internal_native_GetBool(native_address, key, default_val);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
return nativeObject->GetBool((int)key, default_val);
*/
    public static boolean internal_native_GetBool(long this_addr, int key, boolean default_val) {
        try {
            return (boolean) FFMHandles.internal_native_GetBool__JIZ.invokeExact(this_addr, key, default_val);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public boolean GetBool(int key) {
        return internal_native_GetBool(native_address, key);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
return nativeObject->GetBool((int)key);
*/
    public static boolean internal_native_GetBool(long this_addr, int key) {
        try {
            return (boolean) FFMHandles.internal_native_GetBool__JI.invokeExact(this_addr, key);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void SetBool(int key, boolean val) {
        internal_native_SetBool(native_address, key, val);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
nativeObject->SetBool((int)key, val);
*/
    public static void internal_native_SetBool(long this_addr, int key, boolean val) {
        try {
            FFMHandles.internal_native_SetBool__JIZ.invokeExact(this_addr, key, val);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public float GetFloat(int key, float default_val) {
        return internal_native_GetFloat(native_address, key, default_val);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
return nativeObject->GetFloat((int)key, (float)default_val);
*/
    public static float internal_native_GetFloat(long this_addr, int key, float default_val) {
        try {
            return (float) FFMHandles.internal_native_GetFloat__JIF.invokeExact(this_addr, key, default_val);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public float GetFloat(int key) {
        return internal_native_GetFloat(native_address, key);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
return nativeObject->GetFloat((int)key);
*/
    public static float internal_native_GetFloat(long this_addr, int key) {
        try {
            return (float) FFMHandles.internal_native_GetFloat__JI.invokeExact(this_addr, key);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void SetFloat(int key, float val) {
        internal_native_SetFloat(native_address, key, val);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
nativeObject->SetFloat((int)key, (float)val);
*/
    public static void internal_native_SetFloat(long this_addr, int key, float val) {
        try {
            FFMHandles.internal_native_SetFloat__JIF.invokeExact(this_addr, key, val);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public NativeObject GetVoidPtr(int key) {
        long addr = internal_native_GetVoidPtr_addr(native_address, key);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
return (int64_t)nativeObject->GetVoidPtr((int)key);
*/
    public static long internal_native_GetVoidPtr_addr(long this_addr, int key) {
        try {
            return (long) FFMHandles.internal_native_GetVoidPtr_addr__JI.invokeExact(this_addr, key);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void SetVoidPtr(int key, NativeObject val) {
        internal_native_SetVoidPtr(native_address, key, val.native_void_address);
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
nativeObject->SetVoidPtr((int)key, (void*)val_addr);
*/
    public static void internal_native_SetVoidPtr(long this_addr, int key, long val_addr) {
        try {
            FFMHandles.internal_native_SetVoidPtr__JIJ.invokeExact(this_addr, key, val_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public ImVectorImGuiStoragePair get_Data() {
        long addr = internal_native_get_Data_addr(native_address);
        if (addr == 0)
            return ImVectorImGuiStoragePair.NULL;
        if (ImVectorImGuiStoragePair_TEMP_GEN_0 == null)
            ImVectorImGuiStoragePair_TEMP_GEN_0 = ImVectorImGuiStoragePair.native_new();
        ImVectorImGuiStoragePair_TEMP_GEN_0.internal_reset(addr, false);
        return ImVectorImGuiStoragePair_TEMP_GEN_0;
    }

    /*[-FFM;-NATIVE]
ImGuiStorage* nativeObject = (ImGuiStorage*)this_addr;
return (int64_t)&nativeObject->Data;
*/
    public static long internal_native_get_Data_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_Data_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_CRITICAL = new java.lang.foreign.Linker.Option[] { java.lang.foreign.Linker.Option.critical(true) };

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_DEFAULT = new java.lang.foreign.Linker.Option[0];

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static RuntimeException rethrow(Throwable e) {
            if (e instanceof RuntimeException)
                return (RuntimeException) e;
            if (e instanceof Error)
                throw (Error) e;
            return new RuntimeException(e);
        }

        static java.lang.invoke.MethodHandle downcallDefault(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
        }

        static java.lang.invoke.MethodHandle downcallCritical(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            try {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_CRITICAL);
            } catch (Throwable ignored) {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
            }
        }

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1create_1addr__", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1deleteNative__J", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Clear__J = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1Clear__J", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetInt__JII = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1GetInt__JII", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetInt__JI = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1GetInt__JI", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_SetInt__JII = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1SetInt__JII", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetBool__JIZ = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1GetBool__JIZ", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetBool__JI = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1GetBool__JI", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_SetBool__JIZ = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1SetBool__JIZ", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetFloat__JIF = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1GetFloat__JIF", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetFloat__JI = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1GetFloat__JI", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_SetFloat__JIF = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1SetFloat__JIF", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetVoidPtr_addr__JI = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1GetVoidPtr_1addr__JI", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_SetVoidPtr__JIJ = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1SetVoidPtr__JIJ", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_Data_addr__J = downcallDefault("jparser_imgui_ImGuiStorage_internal_1native_1get_1Data_1addr__J", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
