/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ImVectorImGuiID extends NativeObject {

    private NativeObject NativeObject_TEMP_GEN_0;

    static public final ImVectorImGuiID NULL = ImVectorImGuiID.native_new();

    public ImVectorImGuiID() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    /*[-FFM;-NATIVE]
return (int64_t)new ImVectorImGuiID();
*/
    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImVectorImGuiID(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImVectorImGuiID native_new() {
        return new ImVectorImGuiID((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
ImVectorImGuiID* nativeObject = (ImVectorImGuiID*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public int size() {
        return internal_native_size(native_address);
    }

    /*[-FFM;-NATIVE]
ImVectorImGuiID* nativeObject = (ImVectorImGuiID*)this_addr;
return nativeObject->size();
*/
    public static int internal_native_size(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_size__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public int getData(int index) {
        return internal_native_getData(native_address, index);
    }

    /*[-FFM;-NATIVE]
ImVectorImGuiID* nativeObject = (ImVectorImGuiID*)this_addr;
return ((*nativeObject)[(int)index]);*/
    public static int internal_native_getData(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_getData__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void push_back(int v) {
        internal_native_push_back(native_address, v);
    }

    /*[-FFM;-NATIVE]
ImVectorImGuiID* nativeObject = (ImVectorImGuiID*)this_addr;
nativeObject->push_back((int)v);
*/
    public static void internal_native_push_back(long this_addr, int v) {
        try {
            FFMHandles.internal_native_push_back__JI.invokeExact(this_addr, v);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void reserve(int new_capacity) {
        internal_native_reserve(native_address, new_capacity);
    }

    /*[-FFM;-NATIVE]
ImVectorImGuiID* nativeObject = (ImVectorImGuiID*)this_addr;
nativeObject->reserve((int)new_capacity);
*/
    public static void internal_native_reserve(long this_addr, int new_capacity) {
        try {
            FFMHandles.internal_native_reserve__JI.invokeExact(this_addr, new_capacity);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void resize(int new_size) {
        internal_native_resize(native_address, new_size);
    }

    /*[-FFM;-NATIVE]
ImVectorImGuiID* nativeObject = (ImVectorImGuiID*)this_addr;
nativeObject->resize((int)new_size);
*/
    public static void internal_native_resize(long this_addr, int new_size) {
        try {
            FFMHandles.internal_native_resize__JI.invokeExact(this_addr, new_size);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void clear() {
        internal_native_clear(native_address);
    }

    /*[-FFM;-NATIVE]
ImVectorImGuiID* nativeObject = (ImVectorImGuiID*)this_addr;
nativeObject->clear();
*/
    public static void internal_native_clear(long this_addr) {
        try {
            FFMHandles.internal_native_clear__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public NativeObject get_Data() {
        long addr = internal_native_get_Data_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    /*[-FFM;-NATIVE]
ImVectorImGuiID* nativeObject = (ImVectorImGuiID*)this_addr;
return (int64_t)nativeObject->Data;
*/
    public static long internal_native_get_Data_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_Data_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_CRITICAL = new java.lang.foreign.Linker.Option[] { java.lang.foreign.Linker.Option.critical(true) };

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_DEFAULT = new java.lang.foreign.Linker.Option[0];

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static RuntimeException rethrow(Throwable e) {
            if (e instanceof RuntimeException)
                return (RuntimeException) e;
            if (e instanceof Error)
                throw (Error) e;
            return new RuntimeException(e);
        }

        static java.lang.invoke.MethodHandle downcallDefault(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
        }

        static java.lang.invoke.MethodHandle downcallCritical(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            try {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_CRITICAL);
            } catch (Throwable ignored) {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
            }
        }

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = downcallDefault("jparser_imgui_ImVectorImGuiID_internal_1native_1create_1addr__", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = downcallDefault("jparser_imgui_ImVectorImGuiID_internal_1native_1deleteNative__J", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_size__J = downcallDefault("jparser_imgui_ImVectorImGuiID_internal_1native_1size__J", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_getData__JI = downcallDefault("jparser_imgui_ImVectorImGuiID_internal_1native_1getData__JI", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_push_back__JI = downcallDefault("jparser_imgui_ImVectorImGuiID_internal_1native_1push_1back__JI", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_reserve__JI = downcallDefault("jparser_imgui_ImVectorImGuiID_internal_1native_1reserve__JI", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_resize__JI = downcallDefault("jparser_imgui_ImVectorImGuiID_internal_1native_1resize__JI", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_clear__J = downcallDefault("jparser_imgui_ImVectorImGuiID_internal_1native_1clear__J", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_Data_addr__J = downcallDefault("jparser_imgui_ImVectorImGuiID_internal_1native_1get_1Data_1addr__J", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
