/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ImVec2 extends NativeObject {

    static public final ImVec2 NULL = ImVec2.native_new();

    public ImVec2() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    /*[-FFM;-NATIVE]
return (int64_t)new ImVec2();
*/
    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public ImVec2(float x, float y) {
        long addr = internal_native_create_float_float_addr(x, y);
        internal_reset(addr, true);
    }

    /*[-FFM;-NATIVE]
return (int64_t)new ImVec2((float)x, (float)y);
*/
    public static long internal_native_create_float_float_addr(float x, float y) {
        try {
            return (long) FFMHandles.internal_native_create_float_float_addr__FF.invokeExact(x, y);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImVec2(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImVec2 native_new() {
        return new ImVec2((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
ImVec2* nativeObject = (ImVec2*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public float get_x() {
        return internal_native_get_x(native_address);
    }

    /*[-FFM;-NATIVE]
ImVec2* nativeObject = (ImVec2*)this_addr;
return nativeObject->x;
*/
    public static float internal_native_get_x(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_x__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void set_x(float x) {
        internal_native_set_x(native_address, x);
    }

    /*[-FFM;-NATIVE]
ImVec2* nativeObject = (ImVec2*)this_addr;
nativeObject->x = x;
*/
    public static void internal_native_set_x(long this_addr, float x) {
        try {
            FFMHandles.internal_native_set_x__JF.invokeExact(this_addr, x);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public float get_y() {
        return internal_native_get_y(native_address);
    }

    /*[-FFM;-NATIVE]
ImVec2* nativeObject = (ImVec2*)this_addr;
return nativeObject->y;
*/
    public static float internal_native_get_y(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_y__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void set_y(float y) {
        internal_native_set_y(native_address, y);
    }

    /*[-FFM;-NATIVE]
ImVec2* nativeObject = (ImVec2*)this_addr;
nativeObject->y = y;
*/
    public static void internal_native_set_y(long this_addr, float y) {
        try {
            FFMHandles.internal_native_set_y__JF.invokeExact(this_addr, y);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_CRITICAL = new java.lang.foreign.Linker.Option[] { java.lang.foreign.Linker.Option.critical(true) };

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_DEFAULT = new java.lang.foreign.Linker.Option[0];

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static RuntimeException rethrow(Throwable e) {
            if (e instanceof RuntimeException)
                return (RuntimeException) e;
            if (e instanceof Error)
                throw (Error) e;
            return new RuntimeException(e);
        }

        static java.lang.invoke.MethodHandle downcallDefault(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
        }

        static java.lang.invoke.MethodHandle downcallCritical(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            try {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_CRITICAL);
            } catch (Throwable ignored) {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
            }
        }

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = downcallDefault("jparser_imgui_ImVec2_internal_1native_1create_1addr__", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_float_float_addr__FF = downcallDefault("jparser_imgui_ImVec2_internal_1native_1create_1float_1float_1addr__FF", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = downcallDefault("jparser_imgui_ImVec2_internal_1native_1deleteNative__J", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_x__J = downcallDefault("jparser_imgui_ImVec2_internal_1native_1get_1x__J", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_x__JF = downcallDefault("jparser_imgui_ImVec2_internal_1native_1set_1x__JF", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_y__J = downcallDefault("jparser_imgui_ImVec2_internal_1native_1get_1y__J", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_y__JF = downcallDefault("jparser_imgui_ImVec2_internal_1native_1set_1y__JF", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));
    }
}
