/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui;

import com.github.xpenatan.jParser.idl.IDLBase;

public class ImFontBaked extends IDLBase {

    static public final ImFontBaked NULL = ImFontBaked.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImFontBaked(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImFontBaked native_new() {
        return new ImFontBaked((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
ImFontBaked* nativeObject = (ImFontBaked*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
