/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui;

import imgui.idl.IDLBase;

public class ImGuiLastItemData extends IDLBase {

    private ImRect ImRect_TEMP_GEN_0;

    static public final ImGuiLastItemData NULL = ImGuiLastItemData.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiLastItemData(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiLastItemData native_new() {
        return new ImGuiLastItemData((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiLastItemData* nativeObject = (ImGuiLastItemData*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public ImRect get_Rect() {
        long pointer = internal_native_get_Rect(native_address);
        if (pointer == 0)
            return ImRect.NULL;
        if (ImRect_TEMP_GEN_0 == null)
            ImRect_TEMP_GEN_0 = ImRect.native_new();
        ImRect_TEMP_GEN_0.internal_reset(pointer, false);
        return ImRect_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ImGuiLastItemData* nativeObject = (ImGuiLastItemData*)this_addr;
return (jlong)&nativeObject->Rect;
*/
    public static native long internal_native_get_Rect(long this_addr);
}
