/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui;

import java.util.Map;
import java.util.HashMap;
import imgui.idl.IDLEnum;

public enum ImGuiTabItemFlags implements IDLEnum<ImGuiTabItemFlags> {

    CUSTOM(0),
    None(ImGuiTabItemFlags_None_NATIVE()),
    UnsavedDocument(ImGuiTabItemFlags_UnsavedDocument_NATIVE()),
    SetSelected(ImGuiTabItemFlags_SetSelected_NATIVE()),
    NoCloseWithMiddleMouseButton(ImGuiTabItemFlags_NoCloseWithMiddleMouseButton_NATIVE()),
    NoPushId(ImGuiTabItemFlags_NoPushId_NATIVE()),
    NoTooltip(ImGuiTabItemFlags_NoTooltip_NATIVE()),
    NoReorder(ImGuiTabItemFlags_NoReorder_NATIVE()),
    Leading(ImGuiTabItemFlags_Leading_NATIVE()),
    Trailing(ImGuiTabItemFlags_Trailing_NATIVE());

    private int value;

    private ImGuiTabItemFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiTabItemFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiTabItemFlags getCustom() {
        return CUSTOM;
    }

    public static final Map<Integer, ImGuiTabItemFlags> MAP = new HashMap<>();

    static {
        for (ImGuiTabItemFlags value : values()) {
            if (value != CUSTOM) {
                MAP.put(value.value, value);
            }
        }
    }

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_None;
*/
    private static native int ImGuiTabItemFlags_None_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_UnsavedDocument;
*/
    private static native int ImGuiTabItemFlags_UnsavedDocument_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_SetSelected;
*/
    private static native int ImGuiTabItemFlags_SetSelected_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_NoCloseWithMiddleMouseButton;
*/
    private static native int ImGuiTabItemFlags_NoCloseWithMiddleMouseButton_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_NoPushId;
*/
    private static native int ImGuiTabItemFlags_NoPushId_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_NoTooltip;
*/
    private static native int ImGuiTabItemFlags_NoTooltip_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_NoReorder;
*/
    private static native int ImGuiTabItemFlags_NoReorder_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_Leading;
*/
    private static native int ImGuiTabItemFlags_Leading_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiTabItemFlags_Trailing;
*/
    private static native int ImGuiTabItemFlags_Trailing_NATIVE();
}
