/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package imgui;

public interface ImGuiImpl {

    void newFrame();

    void render(ImDrawData drawData);

    void dispose();
}
