/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package imgui;

import imgui.idl.IDLBase;

public class ImGuiPayload extends IDLBase {

    public int get_Data() {
        return getDataNATIVE(native_address);
    }

    /*
      [-JNI;-NATIVE]
              ImGuiPayload* nativeObject = (ImGuiPayload*)addr;
              return *(const int*)nativeObject->Data;
    */
    private static native int getDataNATIVE(long addr);

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiPayload(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiPayload native_new() {
        return new ImGuiPayload((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      ImGuiPayload* nativeObject = (ImGuiPayload*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public boolean IsPreview() {
        return internal_native_IsPreview(native_address);
    }

    /*
      [-JNI;-NATIVE]
      ImGuiPayload* nativeObject = (ImGuiPayload*)this_addr;
      return nativeObject->IsPreview();
    */
    public static native boolean internal_native_IsPreview(long this_addr);

    public boolean IsDelivery() {
        return internal_native_IsDelivery(native_address);
    }

    /*
      [-JNI;-NATIVE]
      ImGuiPayload* nativeObject = (ImGuiPayload*)this_addr;
      return nativeObject->IsDelivery();
    */
    public static native boolean internal_native_IsDelivery(long this_addr);
}
