/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum ImGuiMultiSelectFlags implements IDLEnum<ImGuiMultiSelectFlags> {

    CUSTOM(0),
    None(ImGuiMultiSelectFlags_None_NATIVE()),
    SingleSelect(ImGuiMultiSelectFlags_SingleSelect_NATIVE()),
    NoSelectAll(ImGuiMultiSelectFlags_NoSelectAll_NATIVE()),
    NoRangeSelect(ImGuiMultiSelectFlags_NoRangeSelect_NATIVE()),
    NoAutoSelect(ImGuiMultiSelectFlags_NoAutoSelect_NATIVE()),
    NoAutoClear(ImGuiMultiSelectFlags_NoAutoClear_NATIVE()),
    NoAutoClearOnReselect(ImGuiMultiSelectFlags_NoAutoClearOnReselect_NATIVE()),
    BoxSelect1d(ImGuiMultiSelectFlags_BoxSelect1d_NATIVE()),
    BoxSelect2d(ImGuiMultiSelectFlags_BoxSelect2d_NATIVE()),
    BoxSelectNoScroll(ImGuiMultiSelectFlags_BoxSelectNoScroll_NATIVE()),
    ClearOnEscape(ImGuiMultiSelectFlags_ClearOnEscape_NATIVE()),
    ClearOnClickVoid(ImGuiMultiSelectFlags_ClearOnClickVoid_NATIVE()),
    ScopeWindow(ImGuiMultiSelectFlags_ScopeWindow_NATIVE()),
    ScopeRect(ImGuiMultiSelectFlags_ScopeRect_NATIVE()),
    SelectOnClick(ImGuiMultiSelectFlags_SelectOnClick_NATIVE()),
    SelectOnClickRelease(ImGuiMultiSelectFlags_SelectOnClickRelease_NATIVE()),
    NavWrapX(ImGuiMultiSelectFlags_NavWrapX_NATIVE());

    private int value;

    private ImGuiMultiSelectFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiMultiSelectFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiMultiSelectFlags getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_None;
*/
    private static native int ImGuiMultiSelectFlags_None_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_SingleSelect;
*/
    private static native int ImGuiMultiSelectFlags_SingleSelect_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_NoSelectAll;
*/
    private static native int ImGuiMultiSelectFlags_NoSelectAll_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_NoRangeSelect;
*/
    private static native int ImGuiMultiSelectFlags_NoRangeSelect_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_NoAutoSelect;
*/
    private static native int ImGuiMultiSelectFlags_NoAutoSelect_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_NoAutoClear;
*/
    private static native int ImGuiMultiSelectFlags_NoAutoClear_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_NoAutoClearOnReselect;
*/
    private static native int ImGuiMultiSelectFlags_NoAutoClearOnReselect_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_BoxSelect1d;
*/
    private static native int ImGuiMultiSelectFlags_BoxSelect1d_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_BoxSelect2d;
*/
    private static native int ImGuiMultiSelectFlags_BoxSelect2d_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_BoxSelectNoScroll;
*/
    private static native int ImGuiMultiSelectFlags_BoxSelectNoScroll_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_ClearOnEscape;
*/
    private static native int ImGuiMultiSelectFlags_ClearOnEscape_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_ClearOnClickVoid;
*/
    private static native int ImGuiMultiSelectFlags_ClearOnClickVoid_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_ScopeWindow;
*/
    private static native int ImGuiMultiSelectFlags_ScopeWindow_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_ScopeRect;
*/
    private static native int ImGuiMultiSelectFlags_ScopeRect_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_SelectOnClick;
*/
    private static native int ImGuiMultiSelectFlags_SelectOnClick_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_SelectOnClickRelease;
*/
    private static native int ImGuiMultiSelectFlags_SelectOnClickRelease_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiMultiSelectFlags_NavWrapX;
*/
    private static native int ImGuiMultiSelectFlags_NavWrapX_NATIVE();
}
