/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum ImGuiCol implements IDLEnum<ImGuiCol> {

    CUSTOM(0),
    Text(ImGuiCol_Text_NATIVE()),
    TextDisabled(ImGuiCol_TextDisabled_NATIVE()),
    WindowBg(ImGuiCol_WindowBg_NATIVE()),
    ChildBg(ImGuiCol_ChildBg_NATIVE()),
    PopupBg(ImGuiCol_PopupBg_NATIVE()),
    Border(ImGuiCol_Border_NATIVE()),
    BorderShadow(ImGuiCol_BorderShadow_NATIVE()),
    FrameBg(ImGuiCol_FrameBg_NATIVE()),
    FrameBgHovered(ImGuiCol_FrameBgHovered_NATIVE()),
    FrameBgActive(ImGuiCol_FrameBgActive_NATIVE()),
    TitleBg(ImGuiCol_TitleBg_NATIVE()),
    TitleBgActive(ImGuiCol_TitleBgActive_NATIVE()),
    TitleBgCollapsed(ImGuiCol_TitleBgCollapsed_NATIVE()),
    MenuBarBg(ImGuiCol_MenuBarBg_NATIVE()),
    ScrollbarBg(ImGuiCol_ScrollbarBg_NATIVE()),
    ScrollbarGrab(ImGuiCol_ScrollbarGrab_NATIVE()),
    ScrollbarGrabHovered(ImGuiCol_ScrollbarGrabHovered_NATIVE()),
    ScrollbarGrabActive(ImGuiCol_ScrollbarGrabActive_NATIVE()),
    CheckMark(ImGuiCol_CheckMark_NATIVE()),
    SliderGrab(ImGuiCol_SliderGrab_NATIVE()),
    SliderGrabActive(ImGuiCol_SliderGrabActive_NATIVE()),
    Button(ImGuiCol_Button_NATIVE()),
    ButtonHovered(ImGuiCol_ButtonHovered_NATIVE()),
    ButtonActive(ImGuiCol_ButtonActive_NATIVE()),
    Header(ImGuiCol_Header_NATIVE()),
    HeaderHovered(ImGuiCol_HeaderHovered_NATIVE()),
    HeaderActive(ImGuiCol_HeaderActive_NATIVE()),
    Separator(ImGuiCol_Separator_NATIVE()),
    SeparatorHovered(ImGuiCol_SeparatorHovered_NATIVE()),
    SeparatorActive(ImGuiCol_SeparatorActive_NATIVE()),
    ResizeGrip(ImGuiCol_ResizeGrip_NATIVE()),
    ResizeGripHovered(ImGuiCol_ResizeGripHovered_NATIVE()),
    ResizeGripActive(ImGuiCol_ResizeGripActive_NATIVE()),
    Tab(ImGuiCol_Tab_NATIVE()),
    TabHovered(ImGuiCol_TabHovered_NATIVE()),
    TabActive(ImGuiCol_TabActive_NATIVE()),
    TabUnfocused(ImGuiCol_TabUnfocused_NATIVE()),
    TabUnfocusedActive(ImGuiCol_TabUnfocusedActive_NATIVE()),
    DockingPreview(ImGuiCol_DockingPreview_NATIVE()),
    DockingEmptyBg(ImGuiCol_DockingEmptyBg_NATIVE()),
    PlotLines(ImGuiCol_PlotLines_NATIVE()),
    PlotLinesHovered(ImGuiCol_PlotLinesHovered_NATIVE()),
    PlotHistogram(ImGuiCol_PlotHistogram_NATIVE()),
    PlotHistogramHovered(ImGuiCol_PlotHistogramHovered_NATIVE()),
    TableHeaderBg(ImGuiCol_TableHeaderBg_NATIVE()),
    TableBorderStrong(ImGuiCol_TableBorderStrong_NATIVE()),
    TableBorderLight(ImGuiCol_TableBorderLight_NATIVE()),
    TableRowBg(ImGuiCol_TableRowBg_NATIVE()),
    TableRowBgAlt(ImGuiCol_TableRowBgAlt_NATIVE()),
    TextSelectedBg(ImGuiCol_TextSelectedBg_NATIVE()),
    DragDropTarget(ImGuiCol_DragDropTarget_NATIVE()),
    NavHighlight(ImGuiCol_NavHighlight_NATIVE()),
    NavWindowingHighlight(ImGuiCol_NavWindowingHighlight_NATIVE()),
    NavWindowingDimBg(ImGuiCol_NavWindowingDimBg_NATIVE()),
    ModalWindowDimBg(ImGuiCol_ModalWindowDimBg_NATIVE());

    private int value;

    private ImGuiCol(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiCol setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiCol getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_Text;
*/
    private static native int ImGuiCol_Text_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TextDisabled;
*/
    private static native int ImGuiCol_TextDisabled_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_WindowBg;
*/
    private static native int ImGuiCol_WindowBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_ChildBg;
*/
    private static native int ImGuiCol_ChildBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_PopupBg;
*/
    private static native int ImGuiCol_PopupBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_Border;
*/
    private static native int ImGuiCol_Border_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_BorderShadow;
*/
    private static native int ImGuiCol_BorderShadow_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_FrameBg;
*/
    private static native int ImGuiCol_FrameBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_FrameBgHovered;
*/
    private static native int ImGuiCol_FrameBgHovered_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_FrameBgActive;
*/
    private static native int ImGuiCol_FrameBgActive_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TitleBg;
*/
    private static native int ImGuiCol_TitleBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TitleBgActive;
*/
    private static native int ImGuiCol_TitleBgActive_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TitleBgCollapsed;
*/
    private static native int ImGuiCol_TitleBgCollapsed_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_MenuBarBg;
*/
    private static native int ImGuiCol_MenuBarBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_ScrollbarBg;
*/
    private static native int ImGuiCol_ScrollbarBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_ScrollbarGrab;
*/
    private static native int ImGuiCol_ScrollbarGrab_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_ScrollbarGrabHovered;
*/
    private static native int ImGuiCol_ScrollbarGrabHovered_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_ScrollbarGrabActive;
*/
    private static native int ImGuiCol_ScrollbarGrabActive_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_CheckMark;
*/
    private static native int ImGuiCol_CheckMark_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_SliderGrab;
*/
    private static native int ImGuiCol_SliderGrab_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_SliderGrabActive;
*/
    private static native int ImGuiCol_SliderGrabActive_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_Button;
*/
    private static native int ImGuiCol_Button_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_ButtonHovered;
*/
    private static native int ImGuiCol_ButtonHovered_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_ButtonActive;
*/
    private static native int ImGuiCol_ButtonActive_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_Header;
*/
    private static native int ImGuiCol_Header_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_HeaderHovered;
*/
    private static native int ImGuiCol_HeaderHovered_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_HeaderActive;
*/
    private static native int ImGuiCol_HeaderActive_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_Separator;
*/
    private static native int ImGuiCol_Separator_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_SeparatorHovered;
*/
    private static native int ImGuiCol_SeparatorHovered_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_SeparatorActive;
*/
    private static native int ImGuiCol_SeparatorActive_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_ResizeGrip;
*/
    private static native int ImGuiCol_ResizeGrip_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_ResizeGripHovered;
*/
    private static native int ImGuiCol_ResizeGripHovered_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_ResizeGripActive;
*/
    private static native int ImGuiCol_ResizeGripActive_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_Tab;
*/
    private static native int ImGuiCol_Tab_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TabHovered;
*/
    private static native int ImGuiCol_TabHovered_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TabActive;
*/
    private static native int ImGuiCol_TabActive_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TabUnfocused;
*/
    private static native int ImGuiCol_TabUnfocused_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TabUnfocusedActive;
*/
    private static native int ImGuiCol_TabUnfocusedActive_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_DockingPreview;
*/
    private static native int ImGuiCol_DockingPreview_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_DockingEmptyBg;
*/
    private static native int ImGuiCol_DockingEmptyBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_PlotLines;
*/
    private static native int ImGuiCol_PlotLines_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_PlotLinesHovered;
*/
    private static native int ImGuiCol_PlotLinesHovered_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_PlotHistogram;
*/
    private static native int ImGuiCol_PlotHistogram_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_PlotHistogramHovered;
*/
    private static native int ImGuiCol_PlotHistogramHovered_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TableHeaderBg;
*/
    private static native int ImGuiCol_TableHeaderBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TableBorderStrong;
*/
    private static native int ImGuiCol_TableBorderStrong_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TableBorderLight;
*/
    private static native int ImGuiCol_TableBorderLight_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TableRowBg;
*/
    private static native int ImGuiCol_TableRowBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TableRowBgAlt;
*/
    private static native int ImGuiCol_TableRowBgAlt_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_TextSelectedBg;
*/
    private static native int ImGuiCol_TextSelectedBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_DragDropTarget;
*/
    private static native int ImGuiCol_DragDropTarget_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_NavHighlight;
*/
    private static native int ImGuiCol_NavHighlight_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_NavWindowingHighlight;
*/
    private static native int ImGuiCol_NavWindowingHighlight_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_NavWindowingDimBg;
*/
    private static native int ImGuiCol_NavWindowingDimBg_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)ImGuiCol_ModalWindowDimBg;
*/
    private static native int ImGuiCol_ModalWindowDimBg_NATIVE();
}
