/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui;

import com.github.xpenatan.jParser.idl.IDLBase;
import imgui.enums.ImGuiKey;
import imgui.enums.ImGuiMouseSource;
import imgui.enums.ImGuiConfigFlags;
import imgui.enums.ImGuiBackendFlags;

public class ImGuiIO extends IDLBase {

    private ImVec2 ImVec2_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_1;

    private IDLBase IDLBase_TEMP_GEN_0;

    private ImFontAtlas ImFontAtlas_TEMP_GEN_0;

    private ImFont ImFont_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_2;

    static public final ImGuiIO NULL = ImGuiIO.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiIO(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiIO native_new() {
        return new ImGuiIO((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void AddKeyEvent(ImGuiKey key, boolean down) {
        internal_native_AddKeyEvent(native_address, key.getValue(), down);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->AddKeyEvent((::ImGuiKey)key, down);
*/
    public static native void internal_native_AddKeyEvent(long this_addr, int key, boolean down);

    public void AddKeyAnalogEvent(ImGuiKey key, boolean down, float v) {
        internal_native_AddKeyAnalogEvent(native_address, key.getValue(), down, v);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->AddKeyAnalogEvent((::ImGuiKey)key, down, (float)v);
*/
    public static native void internal_native_AddKeyAnalogEvent(long this_addr, int key, boolean down, float v);

    public void AddMousePosEvent(float x, float y) {
        internal_native_AddMousePosEvent(native_address, x, y);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->AddMousePosEvent((float)x, (float)y);
*/
    public static native void internal_native_AddMousePosEvent(long this_addr, float x, float y);

    public void AddMouseButtonEvent(int button, boolean down) {
        internal_native_AddMouseButtonEvent(native_address, button, down);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->AddMouseButtonEvent((int)button, down);
*/
    public static native void internal_native_AddMouseButtonEvent(long this_addr, int button, boolean down);

    public void AddMouseWheelEvent(float wheel_x, float wheel_y) {
        internal_native_AddMouseWheelEvent(native_address, wheel_x, wheel_y);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->AddMouseWheelEvent((float)wheel_x, (float)wheel_y);
*/
    public static native void internal_native_AddMouseWheelEvent(long this_addr, float wheel_x, float wheel_y);

    public void AddMouseSourceEvent(ImGuiMouseSource source) {
        internal_native_AddMouseSourceEvent(native_address, source.getValue());
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->AddMouseSourceEvent((::ImGuiMouseSource)source);
*/
    public static native void internal_native_AddMouseSourceEvent(long this_addr, int source);

    public void AddMouseViewportEvent(int id) {
        internal_native_AddMouseViewportEvent(native_address, id);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->AddMouseViewportEvent((int)id);
*/
    public static native void internal_native_AddMouseViewportEvent(long this_addr, int id);

    public void AddFocusEvent(boolean focused) {
        internal_native_AddFocusEvent(native_address, focused);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->AddFocusEvent(focused);
*/
    public static native void internal_native_AddFocusEvent(long this_addr, boolean focused);

    public void AddInputCharacter(int c) {
        internal_native_AddInputCharacter(native_address, c);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->AddInputCharacter(c);
*/
    public static native void internal_native_AddInputCharacter(long this_addr, int c);

    public void AddInputCharacterUTF16(short c) {
        internal_native_AddInputCharacterUTF16(native_address, c);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->AddInputCharacterUTF16(c);
*/
    public static native void internal_native_AddInputCharacterUTF16(long this_addr, short c);

    public void AddInputCharactersUTF8(String str) {
        internal_native_AddInputCharactersUTF8(native_address, str);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->AddInputCharactersUTF8(str);
*/
    public static native void internal_native_AddInputCharactersUTF8(long this_addr, String str);

    public void SetKeyEventNativeData(ImGuiKey key, int native_keycode, int native_scancode, int native_legacy_index) {
        internal_native_SetKeyEventNativeData(native_address, key.getValue(), native_keycode, native_scancode, native_legacy_index);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->SetKeyEventNativeData((::ImGuiKey)key, (int)native_keycode, (int)native_scancode, (int)native_legacy_index);
*/
    public static native void internal_native_SetKeyEventNativeData(long this_addr, int key, int native_keycode, int native_scancode, int native_legacy_index);

    public void SetKeyEventNativeData(ImGuiKey key, int native_keycode, int native_scancode) {
        internal_native_SetKeyEventNativeData(native_address, key.getValue(), native_keycode, native_scancode);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->SetKeyEventNativeData((::ImGuiKey)key, (int)native_keycode, (int)native_scancode);
*/
    public static native void internal_native_SetKeyEventNativeData(long this_addr, int key, int native_keycode, int native_scancode);

    public void SetAppAcceptingEvents(boolean accepting_events) {
        internal_native_SetAppAcceptingEvents(native_address, accepting_events);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->SetAppAcceptingEvents(accepting_events);
*/
    public static native void internal_native_SetAppAcceptingEvents(long this_addr, boolean accepting_events);

    public void ClearEventsQueue() {
        internal_native_ClearEventsQueue(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ClearEventsQueue();
*/
    public static native void internal_native_ClearEventsQueue(long this_addr);

    public void ClearInputKeys() {
        internal_native_ClearInputKeys(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ClearInputKeys();
*/
    public static native void internal_native_ClearInputKeys(long this_addr);

    public void ClearInputMouse() {
        internal_native_ClearInputMouse(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ClearInputMouse();
*/
    public static native void internal_native_ClearInputMouse(long this_addr);

    public ImGuiConfigFlags get_ConfigFlags() {
        int value = internal_native_get_ConfigFlags(native_address);
        ImGuiConfigFlags[] values = ImGuiConfigFlags.values();
        for (int i = 0; i < values.length; i++) {
            ImGuiConfigFlags enumVal = values[i];
            if (enumVal != ImGuiConfigFlags.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return ImGuiConfigFlags.CUSTOM.setValue(value);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return (jint)nativeObject->ConfigFlags;
*/
    public static native int internal_native_get_ConfigFlags(long this_addr);

    public void set_ConfigFlags(ImGuiConfigFlags ConfigFlags) {
        internal_native_set_ConfigFlags(native_address, ConfigFlags.getValue());
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigFlags = (::ImGuiConfigFlags)ConfigFlags;
*/
    public static native void internal_native_set_ConfigFlags(long this_addr, int ConfigFlags);

    public ImGuiBackendFlags get_BackendFlags() {
        int value = internal_native_get_BackendFlags(native_address);
        ImGuiBackendFlags[] values = ImGuiBackendFlags.values();
        for (int i = 0; i < values.length; i++) {
            ImGuiBackendFlags enumVal = values[i];
            if (enumVal != ImGuiBackendFlags.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return ImGuiBackendFlags.CUSTOM.setValue(value);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return (jint)nativeObject->BackendFlags;
*/
    public static native int internal_native_get_BackendFlags(long this_addr);

    public void set_BackendFlags(ImGuiBackendFlags BackendFlags) {
        internal_native_set_BackendFlags(native_address, BackendFlags.getValue());
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->BackendFlags = (::ImGuiBackendFlags)BackendFlags;
*/
    public static native void internal_native_set_BackendFlags(long this_addr, int BackendFlags);

    public ImVec2 get_DisplaySize() {
        long pointer = internal_native_get_DisplaySize(native_address);
        if (pointer == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_0 == null)
            ImVec2_TEMP_GEN_0 = ImVec2.native_new();
        ImVec2_TEMP_GEN_0.internal_reset(pointer, false);
        return ImVec2_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return (jlong)&nativeObject->DisplaySize;
*/
    public static native long internal_native_get_DisplaySize(long this_addr);

    public void set_DisplaySize(ImVec2 DisplaySize) {
        internal_native_set_DisplaySize(native_address, DisplaySize.native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->DisplaySize = *((ImVec2*)DisplaySize_addr);
*/
    public static native void internal_native_set_DisplaySize(long this_addr, long DisplaySize_addr);

    public ImVec2 get_DisplayFramebufferScale() {
        long pointer = internal_native_get_DisplayFramebufferScale(native_address);
        if (pointer == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_1 == null)
            ImVec2_TEMP_GEN_1 = ImVec2.native_new();
        ImVec2_TEMP_GEN_1.internal_reset(pointer, false);
        return ImVec2_TEMP_GEN_1;
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return (jlong)&nativeObject->DisplayFramebufferScale;
*/
    public static native long internal_native_get_DisplayFramebufferScale(long this_addr);

    public void set_DisplayFramebufferScale(ImVec2 DisplayFramebufferScale) {
        internal_native_set_DisplayFramebufferScale(native_address, DisplayFramebufferScale.native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->DisplayFramebufferScale = *((ImVec2*)DisplayFramebufferScale_addr);
*/
    public static native void internal_native_set_DisplayFramebufferScale(long this_addr, long DisplayFramebufferScale_addr);

    public float get_DeltaTime() {
        return internal_native_get_DeltaTime(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->DeltaTime;
*/
    public static native float internal_native_get_DeltaTime(long this_addr);

    public void set_DeltaTime(float DeltaTime) {
        internal_native_set_DeltaTime(native_address, DeltaTime);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->DeltaTime = DeltaTime;
*/
    public static native void internal_native_set_DeltaTime(long this_addr, float DeltaTime);

    public float get_IniSavingRate() {
        return internal_native_get_IniSavingRate(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->IniSavingRate;
*/
    public static native float internal_native_get_IniSavingRate(long this_addr);

    public void set_IniSavingRate(float IniSavingRate) {
        internal_native_set_IniSavingRate(native_address, IniSavingRate);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->IniSavingRate = IniSavingRate;
*/
    public static native void internal_native_set_IniSavingRate(long this_addr, float IniSavingRate);

    public IDLBase get_UserData() {
        long pointer = internal_native_get_UserData(native_address);
        if (pointer == 0)
            return IDLBase.NULL;
        if (IDLBase_TEMP_GEN_0 == null)
            IDLBase_TEMP_GEN_0 = IDLBase.native_new();
        IDLBase_TEMP_GEN_0.internal_reset(pointer, false);
        return IDLBase_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return (jlong)nativeObject->UserData;
*/
    public static native long internal_native_get_UserData(long this_addr);

    public void set_UserData(IDLBase UserData) {
        internal_native_set_UserData(native_address, UserData.native_void_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->UserData = (void**)UserData_addr;
*/
    public static native void internal_native_set_UserData(long this_addr, long UserData_addr);

    public ImFontAtlas get_Fonts() {
        long pointer = internal_native_get_Fonts(native_address);
        if (pointer == 0)
            return ImFontAtlas.NULL;
        if (ImFontAtlas_TEMP_GEN_0 == null)
            ImFontAtlas_TEMP_GEN_0 = ImFontAtlas.native_new();
        ImFontAtlas_TEMP_GEN_0.internal_reset(pointer, false);
        return ImFontAtlas_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
ImFontAtlas* attr = nativeObject->Fonts;
return (jlong)attr;
*/
    public static native long internal_native_get_Fonts(long this_addr);

    public void set_Fonts(ImFontAtlas Fonts) {
        internal_native_set_Fonts(native_address, Fonts.native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->Fonts = (ImFontAtlas*)Fonts_addr;
*/
    public static native void internal_native_set_Fonts(long this_addr, long Fonts_addr);

    public ImFont get_FontDefault() {
        long pointer = internal_native_get_FontDefault(native_address);
        if (pointer == 0)
            return ImFont.NULL;
        if (ImFont_TEMP_GEN_0 == null)
            ImFont_TEMP_GEN_0 = ImFont.native_new();
        ImFont_TEMP_GEN_0.internal_reset(pointer, false);
        return ImFont_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
ImFont* attr = nativeObject->FontDefault;
return (jlong)attr;
*/
    public static native long internal_native_get_FontDefault(long this_addr);

    public void set_FontDefault(ImFont FontDefault) {
        internal_native_set_FontDefault(native_address, FontDefault.native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->FontDefault = (ImFont*)FontDefault_addr;
*/
    public static native void internal_native_set_FontDefault(long this_addr, long FontDefault_addr);

    public boolean get_FontAllowUserScaling() {
        return internal_native_get_FontAllowUserScaling(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->FontAllowUserScaling;
*/
    public static native boolean internal_native_get_FontAllowUserScaling(long this_addr);

    public void set_FontAllowUserScaling(boolean FontAllowUserScaling) {
        internal_native_set_FontAllowUserScaling(native_address, FontAllowUserScaling);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->FontAllowUserScaling = FontAllowUserScaling;
*/
    public static native void internal_native_set_FontAllowUserScaling(long this_addr, boolean FontAllowUserScaling);

    public boolean get_ConfigNavSwapGamepadButtons() {
        return internal_native_get_ConfigNavSwapGamepadButtons(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigNavSwapGamepadButtons;
*/
    public static native boolean internal_native_get_ConfigNavSwapGamepadButtons(long this_addr);

    public void set_ConfigNavSwapGamepadButtons(boolean ConfigNavSwapGamepadButtons) {
        internal_native_set_ConfigNavSwapGamepadButtons(native_address, ConfigNavSwapGamepadButtons);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigNavSwapGamepadButtons = ConfigNavSwapGamepadButtons;
*/
    public static native void internal_native_set_ConfigNavSwapGamepadButtons(long this_addr, boolean ConfigNavSwapGamepadButtons);

    public boolean get_ConfigNavMoveSetMousePos() {
        return internal_native_get_ConfigNavMoveSetMousePos(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigNavMoveSetMousePos;
*/
    public static native boolean internal_native_get_ConfigNavMoveSetMousePos(long this_addr);

    public void set_ConfigNavMoveSetMousePos(boolean ConfigNavMoveSetMousePos) {
        internal_native_set_ConfigNavMoveSetMousePos(native_address, ConfigNavMoveSetMousePos);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigNavMoveSetMousePos = ConfigNavMoveSetMousePos;
*/
    public static native void internal_native_set_ConfigNavMoveSetMousePos(long this_addr, boolean ConfigNavMoveSetMousePos);

    public boolean get_ConfigNavCaptureKeyboard() {
        return internal_native_get_ConfigNavCaptureKeyboard(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigNavCaptureKeyboard;
*/
    public static native boolean internal_native_get_ConfigNavCaptureKeyboard(long this_addr);

    public void set_ConfigNavCaptureKeyboard(boolean ConfigNavCaptureKeyboard) {
        internal_native_set_ConfigNavCaptureKeyboard(native_address, ConfigNavCaptureKeyboard);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigNavCaptureKeyboard = ConfigNavCaptureKeyboard;
*/
    public static native void internal_native_set_ConfigNavCaptureKeyboard(long this_addr, boolean ConfigNavCaptureKeyboard);

    public boolean get_ConfigNavEscapeClearFocusItem() {
        return internal_native_get_ConfigNavEscapeClearFocusItem(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigNavEscapeClearFocusItem;
*/
    public static native boolean internal_native_get_ConfigNavEscapeClearFocusItem(long this_addr);

    public void set_ConfigNavEscapeClearFocusItem(boolean ConfigNavEscapeClearFocusItem) {
        internal_native_set_ConfigNavEscapeClearFocusItem(native_address, ConfigNavEscapeClearFocusItem);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigNavEscapeClearFocusItem = ConfigNavEscapeClearFocusItem;
*/
    public static native void internal_native_set_ConfigNavEscapeClearFocusItem(long this_addr, boolean ConfigNavEscapeClearFocusItem);

    public boolean get_ConfigNavEscapeClearFocusWindow() {
        return internal_native_get_ConfigNavEscapeClearFocusWindow(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigNavEscapeClearFocusWindow;
*/
    public static native boolean internal_native_get_ConfigNavEscapeClearFocusWindow(long this_addr);

    public void set_ConfigNavEscapeClearFocusWindow(boolean ConfigNavEscapeClearFocusWindow) {
        internal_native_set_ConfigNavEscapeClearFocusWindow(native_address, ConfigNavEscapeClearFocusWindow);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigNavEscapeClearFocusWindow = ConfigNavEscapeClearFocusWindow;
*/
    public static native void internal_native_set_ConfigNavEscapeClearFocusWindow(long this_addr, boolean ConfigNavEscapeClearFocusWindow);

    public boolean get_ConfigNavCursorVisibleAuto() {
        return internal_native_get_ConfigNavCursorVisibleAuto(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigNavCursorVisibleAuto;
*/
    public static native boolean internal_native_get_ConfigNavCursorVisibleAuto(long this_addr);

    public void set_ConfigNavCursorVisibleAuto(boolean ConfigNavCursorVisibleAuto) {
        internal_native_set_ConfigNavCursorVisibleAuto(native_address, ConfigNavCursorVisibleAuto);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigNavCursorVisibleAuto = ConfigNavCursorVisibleAuto;
*/
    public static native void internal_native_set_ConfigNavCursorVisibleAuto(long this_addr, boolean ConfigNavCursorVisibleAuto);

    public boolean get_ConfigNavCursorVisibleAlways() {
        return internal_native_get_ConfigNavCursorVisibleAlways(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigNavCursorVisibleAlways;
*/
    public static native boolean internal_native_get_ConfigNavCursorVisibleAlways(long this_addr);

    public void set_ConfigNavCursorVisibleAlways(boolean ConfigNavCursorVisibleAlways) {
        internal_native_set_ConfigNavCursorVisibleAlways(native_address, ConfigNavCursorVisibleAlways);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigNavCursorVisibleAlways = ConfigNavCursorVisibleAlways;
*/
    public static native void internal_native_set_ConfigNavCursorVisibleAlways(long this_addr, boolean ConfigNavCursorVisibleAlways);

    public boolean get_ConfigDockingNoSplit() {
        return internal_native_get_ConfigDockingNoSplit(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigDockingNoSplit;
*/
    public static native boolean internal_native_get_ConfigDockingNoSplit(long this_addr);

    public void set_ConfigDockingNoSplit(boolean ConfigDockingNoSplit) {
        internal_native_set_ConfigDockingNoSplit(native_address, ConfigDockingNoSplit);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigDockingNoSplit = ConfigDockingNoSplit;
*/
    public static native void internal_native_set_ConfigDockingNoSplit(long this_addr, boolean ConfigDockingNoSplit);

    public boolean get_ConfigDockingWithShift() {
        return internal_native_get_ConfigDockingWithShift(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigDockingWithShift;
*/
    public static native boolean internal_native_get_ConfigDockingWithShift(long this_addr);

    public void set_ConfigDockingWithShift(boolean ConfigDockingWithShift) {
        internal_native_set_ConfigDockingWithShift(native_address, ConfigDockingWithShift);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigDockingWithShift = ConfigDockingWithShift;
*/
    public static native void internal_native_set_ConfigDockingWithShift(long this_addr, boolean ConfigDockingWithShift);

    public boolean get_ConfigDockingAlwaysTabBar() {
        return internal_native_get_ConfigDockingAlwaysTabBar(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigDockingAlwaysTabBar;
*/
    public static native boolean internal_native_get_ConfigDockingAlwaysTabBar(long this_addr);

    public void set_ConfigDockingAlwaysTabBar(boolean ConfigDockingAlwaysTabBar) {
        internal_native_set_ConfigDockingAlwaysTabBar(native_address, ConfigDockingAlwaysTabBar);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigDockingAlwaysTabBar = ConfigDockingAlwaysTabBar;
*/
    public static native void internal_native_set_ConfigDockingAlwaysTabBar(long this_addr, boolean ConfigDockingAlwaysTabBar);

    public boolean get_ConfigDockingTransparentPayload() {
        return internal_native_get_ConfigDockingTransparentPayload(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigDockingTransparentPayload;
*/
    public static native boolean internal_native_get_ConfigDockingTransparentPayload(long this_addr);

    public void set_ConfigDockingTransparentPayload(boolean ConfigDockingTransparentPayload) {
        internal_native_set_ConfigDockingTransparentPayload(native_address, ConfigDockingTransparentPayload);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigDockingTransparentPayload = ConfigDockingTransparentPayload;
*/
    public static native void internal_native_set_ConfigDockingTransparentPayload(long this_addr, boolean ConfigDockingTransparentPayload);

    public boolean get_ConfigViewportsNoAutoMerge() {
        return internal_native_get_ConfigViewportsNoAutoMerge(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigViewportsNoAutoMerge;
*/
    public static native boolean internal_native_get_ConfigViewportsNoAutoMerge(long this_addr);

    public void set_ConfigViewportsNoAutoMerge(boolean ConfigViewportsNoAutoMerge) {
        internal_native_set_ConfigViewportsNoAutoMerge(native_address, ConfigViewportsNoAutoMerge);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigViewportsNoAutoMerge = ConfigViewportsNoAutoMerge;
*/
    public static native void internal_native_set_ConfigViewportsNoAutoMerge(long this_addr, boolean ConfigViewportsNoAutoMerge);

    public boolean get_ConfigViewportsNoTaskBarIcon() {
        return internal_native_get_ConfigViewportsNoTaskBarIcon(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigViewportsNoTaskBarIcon;
*/
    public static native boolean internal_native_get_ConfigViewportsNoTaskBarIcon(long this_addr);

    public void set_ConfigViewportsNoTaskBarIcon(boolean ConfigViewportsNoTaskBarIcon) {
        internal_native_set_ConfigViewportsNoTaskBarIcon(native_address, ConfigViewportsNoTaskBarIcon);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigViewportsNoTaskBarIcon = ConfigViewportsNoTaskBarIcon;
*/
    public static native void internal_native_set_ConfigViewportsNoTaskBarIcon(long this_addr, boolean ConfigViewportsNoTaskBarIcon);

    public boolean get_ConfigViewportsNoDecoration() {
        return internal_native_get_ConfigViewportsNoDecoration(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigViewportsNoDecoration;
*/
    public static native boolean internal_native_get_ConfigViewportsNoDecoration(long this_addr);

    public void set_ConfigViewportsNoDecoration(boolean ConfigViewportsNoDecoration) {
        internal_native_set_ConfigViewportsNoDecoration(native_address, ConfigViewportsNoDecoration);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigViewportsNoDecoration = ConfigViewportsNoDecoration;
*/
    public static native void internal_native_set_ConfigViewportsNoDecoration(long this_addr, boolean ConfigViewportsNoDecoration);

    public boolean get_ConfigViewportsNoDefaultParent() {
        return internal_native_get_ConfigViewportsNoDefaultParent(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigViewportsNoDefaultParent;
*/
    public static native boolean internal_native_get_ConfigViewportsNoDefaultParent(long this_addr);

    public void set_ConfigViewportsNoDefaultParent(boolean ConfigViewportsNoDefaultParent) {
        internal_native_set_ConfigViewportsNoDefaultParent(native_address, ConfigViewportsNoDefaultParent);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigViewportsNoDefaultParent = ConfigViewportsNoDefaultParent;
*/
    public static native void internal_native_set_ConfigViewportsNoDefaultParent(long this_addr, boolean ConfigViewportsNoDefaultParent);

    public boolean get_ConfigViewportsPlatformFocusSetsImGuiFocus() {
        return internal_native_get_ConfigViewportsPlatformFocusSetsImGuiFocus(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigViewportsPlatformFocusSetsImGuiFocus;
*/
    public static native boolean internal_native_get_ConfigViewportsPlatformFocusSetsImGuiFocus(long this_addr);

    public void set_ConfigViewportsPlatformFocusSetsImGuiFocus(boolean ConfigViewportsPlatformFocusSetsImGuiFocus) {
        internal_native_set_ConfigViewportsPlatformFocusSetsImGuiFocus(native_address, ConfigViewportsPlatformFocusSetsImGuiFocus);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigViewportsPlatformFocusSetsImGuiFocus = ConfigViewportsPlatformFocusSetsImGuiFocus;
*/
    public static native void internal_native_set_ConfigViewportsPlatformFocusSetsImGuiFocus(long this_addr, boolean ConfigViewportsPlatformFocusSetsImGuiFocus);

    public boolean get_ConfigDpiScaleFonts() {
        return internal_native_get_ConfigDpiScaleFonts(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigDpiScaleFonts;
*/
    public static native boolean internal_native_get_ConfigDpiScaleFonts(long this_addr);

    public void set_ConfigDpiScaleFonts(boolean ConfigDpiScaleFonts) {
        internal_native_set_ConfigDpiScaleFonts(native_address, ConfigDpiScaleFonts);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigDpiScaleFonts = ConfigDpiScaleFonts;
*/
    public static native void internal_native_set_ConfigDpiScaleFonts(long this_addr, boolean ConfigDpiScaleFonts);

    public boolean get_ConfigDpiScaleViewports() {
        return internal_native_get_ConfigDpiScaleViewports(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigDpiScaleViewports;
*/
    public static native boolean internal_native_get_ConfigDpiScaleViewports(long this_addr);

    public void set_ConfigDpiScaleViewports(boolean ConfigDpiScaleViewports) {
        internal_native_set_ConfigDpiScaleViewports(native_address, ConfigDpiScaleViewports);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigDpiScaleViewports = ConfigDpiScaleViewports;
*/
    public static native void internal_native_set_ConfigDpiScaleViewports(long this_addr, boolean ConfigDpiScaleViewports);

    public boolean get_MouseDrawCursor() {
        return internal_native_get_MouseDrawCursor(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->MouseDrawCursor;
*/
    public static native boolean internal_native_get_MouseDrawCursor(long this_addr);

    public void set_MouseDrawCursor(boolean MouseDrawCursor) {
        internal_native_set_MouseDrawCursor(native_address, MouseDrawCursor);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->MouseDrawCursor = MouseDrawCursor;
*/
    public static native void internal_native_set_MouseDrawCursor(long this_addr, boolean MouseDrawCursor);

    public boolean get_ConfigMacOSXBehaviors() {
        return internal_native_get_ConfigMacOSXBehaviors(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigMacOSXBehaviors;
*/
    public static native boolean internal_native_get_ConfigMacOSXBehaviors(long this_addr);

    public void set_ConfigMacOSXBehaviors(boolean ConfigMacOSXBehaviors) {
        internal_native_set_ConfigMacOSXBehaviors(native_address, ConfigMacOSXBehaviors);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigMacOSXBehaviors = ConfigMacOSXBehaviors;
*/
    public static native void internal_native_set_ConfigMacOSXBehaviors(long this_addr, boolean ConfigMacOSXBehaviors);

    public boolean get_ConfigInputTrickleEventQueue() {
        return internal_native_get_ConfigInputTrickleEventQueue(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigInputTrickleEventQueue;
*/
    public static native boolean internal_native_get_ConfigInputTrickleEventQueue(long this_addr);

    public void set_ConfigInputTrickleEventQueue(boolean ConfigInputTrickleEventQueue) {
        internal_native_set_ConfigInputTrickleEventQueue(native_address, ConfigInputTrickleEventQueue);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigInputTrickleEventQueue = ConfigInputTrickleEventQueue;
*/
    public static native void internal_native_set_ConfigInputTrickleEventQueue(long this_addr, boolean ConfigInputTrickleEventQueue);

    public boolean get_ConfigInputTextCursorBlink() {
        return internal_native_get_ConfigInputTextCursorBlink(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigInputTextCursorBlink;
*/
    public static native boolean internal_native_get_ConfigInputTextCursorBlink(long this_addr);

    public void set_ConfigInputTextCursorBlink(boolean ConfigInputTextCursorBlink) {
        internal_native_set_ConfigInputTextCursorBlink(native_address, ConfigInputTextCursorBlink);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigInputTextCursorBlink = ConfigInputTextCursorBlink;
*/
    public static native void internal_native_set_ConfigInputTextCursorBlink(long this_addr, boolean ConfigInputTextCursorBlink);

    public boolean get_ConfigInputTextEnterKeepActive() {
        return internal_native_get_ConfigInputTextEnterKeepActive(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigInputTextEnterKeepActive;
*/
    public static native boolean internal_native_get_ConfigInputTextEnterKeepActive(long this_addr);

    public void set_ConfigInputTextEnterKeepActive(boolean ConfigInputTextEnterKeepActive) {
        internal_native_set_ConfigInputTextEnterKeepActive(native_address, ConfigInputTextEnterKeepActive);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigInputTextEnterKeepActive = ConfigInputTextEnterKeepActive;
*/
    public static native void internal_native_set_ConfigInputTextEnterKeepActive(long this_addr, boolean ConfigInputTextEnterKeepActive);

    public boolean get_ConfigDragClickToInputText() {
        return internal_native_get_ConfigDragClickToInputText(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigDragClickToInputText;
*/
    public static native boolean internal_native_get_ConfigDragClickToInputText(long this_addr);

    public void set_ConfigDragClickToInputText(boolean ConfigDragClickToInputText) {
        internal_native_set_ConfigDragClickToInputText(native_address, ConfigDragClickToInputText);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigDragClickToInputText = ConfigDragClickToInputText;
*/
    public static native void internal_native_set_ConfigDragClickToInputText(long this_addr, boolean ConfigDragClickToInputText);

    public boolean get_ConfigWindowsResizeFromEdges() {
        return internal_native_get_ConfigWindowsResizeFromEdges(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigWindowsResizeFromEdges;
*/
    public static native boolean internal_native_get_ConfigWindowsResizeFromEdges(long this_addr);

    public void set_ConfigWindowsResizeFromEdges(boolean ConfigWindowsResizeFromEdges) {
        internal_native_set_ConfigWindowsResizeFromEdges(native_address, ConfigWindowsResizeFromEdges);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigWindowsResizeFromEdges = ConfigWindowsResizeFromEdges;
*/
    public static native void internal_native_set_ConfigWindowsResizeFromEdges(long this_addr, boolean ConfigWindowsResizeFromEdges);

    public boolean get_ConfigWindowsMoveFromTitleBarOnly() {
        return internal_native_get_ConfigWindowsMoveFromTitleBarOnly(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigWindowsMoveFromTitleBarOnly;
*/
    public static native boolean internal_native_get_ConfigWindowsMoveFromTitleBarOnly(long this_addr);

    public void set_ConfigWindowsMoveFromTitleBarOnly(boolean ConfigWindowsMoveFromTitleBarOnly) {
        internal_native_set_ConfigWindowsMoveFromTitleBarOnly(native_address, ConfigWindowsMoveFromTitleBarOnly);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigWindowsMoveFromTitleBarOnly = ConfigWindowsMoveFromTitleBarOnly;
*/
    public static native void internal_native_set_ConfigWindowsMoveFromTitleBarOnly(long this_addr, boolean ConfigWindowsMoveFromTitleBarOnly);

    public boolean get_ConfigWindowsCopyContentsWithCtrlC() {
        return internal_native_get_ConfigWindowsCopyContentsWithCtrlC(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigWindowsCopyContentsWithCtrlC;
*/
    public static native boolean internal_native_get_ConfigWindowsCopyContentsWithCtrlC(long this_addr);

    public void set_ConfigWindowsCopyContentsWithCtrlC(boolean ConfigWindowsCopyContentsWithCtrlC) {
        internal_native_set_ConfigWindowsCopyContentsWithCtrlC(native_address, ConfigWindowsCopyContentsWithCtrlC);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigWindowsCopyContentsWithCtrlC = ConfigWindowsCopyContentsWithCtrlC;
*/
    public static native void internal_native_set_ConfigWindowsCopyContentsWithCtrlC(long this_addr, boolean ConfigWindowsCopyContentsWithCtrlC);

    public boolean get_ConfigScrollbarScrollByPage() {
        return internal_native_get_ConfigScrollbarScrollByPage(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigScrollbarScrollByPage;
*/
    public static native boolean internal_native_get_ConfigScrollbarScrollByPage(long this_addr);

    public void set_ConfigScrollbarScrollByPage(boolean ConfigScrollbarScrollByPage) {
        internal_native_set_ConfigScrollbarScrollByPage(native_address, ConfigScrollbarScrollByPage);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigScrollbarScrollByPage = ConfigScrollbarScrollByPage;
*/
    public static native void internal_native_set_ConfigScrollbarScrollByPage(long this_addr, boolean ConfigScrollbarScrollByPage);

    public float get_ConfigMemoryCompactTimer() {
        return internal_native_get_ConfigMemoryCompactTimer(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->ConfigMemoryCompactTimer;
*/
    public static native float internal_native_get_ConfigMemoryCompactTimer(long this_addr);

    public void set_ConfigMemoryCompactTimer(float ConfigMemoryCompactTimer) {
        internal_native_set_ConfigMemoryCompactTimer(native_address, ConfigMemoryCompactTimer);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->ConfigMemoryCompactTimer = ConfigMemoryCompactTimer;
*/
    public static native void internal_native_set_ConfigMemoryCompactTimer(long this_addr, float ConfigMemoryCompactTimer);

    public float get_MouseDoubleClickTime() {
        return internal_native_get_MouseDoubleClickTime(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->MouseDoubleClickTime;
*/
    public static native float internal_native_get_MouseDoubleClickTime(long this_addr);

    public void set_MouseDoubleClickTime(float MouseDoubleClickTime) {
        internal_native_set_MouseDoubleClickTime(native_address, MouseDoubleClickTime);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->MouseDoubleClickTime = MouseDoubleClickTime;
*/
    public static native void internal_native_set_MouseDoubleClickTime(long this_addr, float MouseDoubleClickTime);

    public float get_MouseDoubleClickMaxDist() {
        return internal_native_get_MouseDoubleClickMaxDist(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->MouseDoubleClickMaxDist;
*/
    public static native float internal_native_get_MouseDoubleClickMaxDist(long this_addr);

    public void set_MouseDoubleClickMaxDist(float MouseDoubleClickMaxDist) {
        internal_native_set_MouseDoubleClickMaxDist(native_address, MouseDoubleClickMaxDist);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->MouseDoubleClickMaxDist = MouseDoubleClickMaxDist;
*/
    public static native void internal_native_set_MouseDoubleClickMaxDist(long this_addr, float MouseDoubleClickMaxDist);

    public float get_MouseDragThreshold() {
        return internal_native_get_MouseDragThreshold(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->MouseDragThreshold;
*/
    public static native float internal_native_get_MouseDragThreshold(long this_addr);

    public void set_MouseDragThreshold(float MouseDragThreshold) {
        internal_native_set_MouseDragThreshold(native_address, MouseDragThreshold);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->MouseDragThreshold = MouseDragThreshold;
*/
    public static native void internal_native_set_MouseDragThreshold(long this_addr, float MouseDragThreshold);

    public float get_KeyRepeatDelay() {
        return internal_native_get_KeyRepeatDelay(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->KeyRepeatDelay;
*/
    public static native float internal_native_get_KeyRepeatDelay(long this_addr);

    public void set_KeyRepeatDelay(float KeyRepeatDelay) {
        internal_native_set_KeyRepeatDelay(native_address, KeyRepeatDelay);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->KeyRepeatDelay = KeyRepeatDelay;
*/
    public static native void internal_native_set_KeyRepeatDelay(long this_addr, float KeyRepeatDelay);

    public float get_KeyRepeatRate() {
        return internal_native_get_KeyRepeatRate(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->KeyRepeatRate;
*/
    public static native float internal_native_get_KeyRepeatRate(long this_addr);

    public void set_KeyRepeatRate(float KeyRepeatRate) {
        internal_native_set_KeyRepeatRate(native_address, KeyRepeatRate);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->KeyRepeatRate = KeyRepeatRate;
*/
    public static native void internal_native_set_KeyRepeatRate(long this_addr, float KeyRepeatRate);

    public boolean get_WantCaptureMouse() {
        return internal_native_get_WantCaptureMouse(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->WantCaptureMouse;
*/
    public static native boolean internal_native_get_WantCaptureMouse(long this_addr);

    public void set_WantCaptureMouse(boolean WantCaptureMouse) {
        internal_native_set_WantCaptureMouse(native_address, WantCaptureMouse);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->WantCaptureMouse = WantCaptureMouse;
*/
    public static native void internal_native_set_WantCaptureMouse(long this_addr, boolean WantCaptureMouse);

    public boolean get_WantCaptureKeyboard() {
        return internal_native_get_WantCaptureKeyboard(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->WantCaptureKeyboard;
*/
    public static native boolean internal_native_get_WantCaptureKeyboard(long this_addr);

    public void set_WantCaptureKeyboard(boolean WantCaptureKeyboard) {
        internal_native_set_WantCaptureKeyboard(native_address, WantCaptureKeyboard);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->WantCaptureKeyboard = WantCaptureKeyboard;
*/
    public static native void internal_native_set_WantCaptureKeyboard(long this_addr, boolean WantCaptureKeyboard);

    public boolean get_WantTextInput() {
        return internal_native_get_WantTextInput(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->WantTextInput;
*/
    public static native boolean internal_native_get_WantTextInput(long this_addr);

    public void set_WantTextInput(boolean WantTextInput) {
        internal_native_set_WantTextInput(native_address, WantTextInput);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->WantTextInput = WantTextInput;
*/
    public static native void internal_native_set_WantTextInput(long this_addr, boolean WantTextInput);

    public boolean get_WantSetMousePos() {
        return internal_native_get_WantSetMousePos(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->WantSetMousePos;
*/
    public static native boolean internal_native_get_WantSetMousePos(long this_addr);

    public void set_WantSetMousePos(boolean WantSetMousePos) {
        internal_native_set_WantSetMousePos(native_address, WantSetMousePos);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->WantSetMousePos = WantSetMousePos;
*/
    public static native void internal_native_set_WantSetMousePos(long this_addr, boolean WantSetMousePos);

    public boolean get_WantSaveIniSettings() {
        return internal_native_get_WantSaveIniSettings(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->WantSaveIniSettings;
*/
    public static native boolean internal_native_get_WantSaveIniSettings(long this_addr);

    public void set_WantSaveIniSettings(boolean WantSaveIniSettings) {
        internal_native_set_WantSaveIniSettings(native_address, WantSaveIniSettings);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->WantSaveIniSettings = WantSaveIniSettings;
*/
    public static native void internal_native_set_WantSaveIniSettings(long this_addr, boolean WantSaveIniSettings);

    public boolean get_NavActive() {
        return internal_native_get_NavActive(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->NavActive;
*/
    public static native boolean internal_native_get_NavActive(long this_addr);

    public void set_NavActive(boolean NavActive) {
        internal_native_set_NavActive(native_address, NavActive);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->NavActive = NavActive;
*/
    public static native void internal_native_set_NavActive(long this_addr, boolean NavActive);

    public boolean get_NavVisible() {
        return internal_native_get_NavVisible(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->NavVisible;
*/
    public static native boolean internal_native_get_NavVisible(long this_addr);

    public void set_NavVisible(boolean NavVisible) {
        internal_native_set_NavVisible(native_address, NavVisible);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->NavVisible = NavVisible;
*/
    public static native void internal_native_set_NavVisible(long this_addr, boolean NavVisible);

    public float get_Framerate() {
        return internal_native_get_Framerate(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->Framerate;
*/
    public static native float internal_native_get_Framerate(long this_addr);

    public void set_Framerate(float Framerate) {
        internal_native_set_Framerate(native_address, Framerate);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->Framerate = Framerate;
*/
    public static native void internal_native_set_Framerate(long this_addr, float Framerate);

    public int get_MetricsRenderVertices() {
        return internal_native_get_MetricsRenderVertices(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->MetricsRenderVertices;
*/
    public static native int internal_native_get_MetricsRenderVertices(long this_addr);

    public void set_MetricsRenderVertices(int MetricsRenderVertices) {
        internal_native_set_MetricsRenderVertices(native_address, MetricsRenderVertices);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->MetricsRenderVertices = MetricsRenderVertices;
*/
    public static native void internal_native_set_MetricsRenderVertices(long this_addr, int MetricsRenderVertices);

    public int get_MetricsRenderIndices() {
        return internal_native_get_MetricsRenderIndices(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->MetricsRenderIndices;
*/
    public static native int internal_native_get_MetricsRenderIndices(long this_addr);

    public void set_MetricsRenderIndices(int MetricsRenderIndices) {
        internal_native_set_MetricsRenderIndices(native_address, MetricsRenderIndices);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->MetricsRenderIndices = MetricsRenderIndices;
*/
    public static native void internal_native_set_MetricsRenderIndices(long this_addr, int MetricsRenderIndices);

    public int get_MetricsRenderWindows() {
        return internal_native_get_MetricsRenderWindows(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->MetricsRenderWindows;
*/
    public static native int internal_native_get_MetricsRenderWindows(long this_addr);

    public void set_MetricsRenderWindows(int MetricsRenderWindows) {
        internal_native_set_MetricsRenderWindows(native_address, MetricsRenderWindows);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->MetricsRenderWindows = MetricsRenderWindows;
*/
    public static native void internal_native_set_MetricsRenderWindows(long this_addr, int MetricsRenderWindows);

    public int get_MetricsActiveWindows() {
        return internal_native_get_MetricsActiveWindows(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return nativeObject->MetricsActiveWindows;
*/
    public static native int internal_native_get_MetricsActiveWindows(long this_addr);

    public void set_MetricsActiveWindows(int MetricsActiveWindows) {
        internal_native_set_MetricsActiveWindows(native_address, MetricsActiveWindows);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->MetricsActiveWindows = MetricsActiveWindows;
*/
    public static native void internal_native_set_MetricsActiveWindows(long this_addr, int MetricsActiveWindows);

    public ImVec2 get_MouseDelta() {
        long pointer = internal_native_get_MouseDelta(native_address);
        if (pointer == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_2 == null)
            ImVec2_TEMP_GEN_2 = ImVec2.native_new();
        ImVec2_TEMP_GEN_2.internal_reset(pointer, false);
        return ImVec2_TEMP_GEN_2;
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
return (jlong)&nativeObject->MouseDelta;
*/
    public static native long internal_native_get_MouseDelta(long this_addr);

    public void set_MouseDelta(ImVec2 MouseDelta) {
        internal_native_set_MouseDelta(native_address, MouseDelta.native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiIO* nativeObject = (ImGuiIO*)this_addr;
nativeObject->MouseDelta = *((ImVec2*)MouseDelta_addr);
*/
    public static native void internal_native_set_MouseDelta(long this_addr, long MouseDelta_addr);
}
