/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui;

import com.github.xpenatan.jParser.idl.IDLBase;

public class ImGuiWindowStackData extends IDLBase {

    static public final ImGuiWindowStackData NULL = ImGuiWindowStackData.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiWindowStackData(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiWindowStackData native_new() {
        return new ImGuiWindowStackData((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
ImGuiWindowStackData* nativeObject = (ImGuiWindowStackData*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);
}
