/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public class ImGuiStoragePair extends NativeObject {

    static public final ImGuiStoragePair NULL = ImGuiStoragePair.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiStoragePair(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiStoragePair native_new() {
        return new ImGuiStoragePair((byte) 0, (char) 0);
    }

    public NativeObject get_val_p() {
        return null;
    }

    public void set_val_p(NativeObject val_p) {
    }
}
