/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import imgui.enums.ImGuiInputTextFlags;

public class ImGuiInputTextCallbackData extends NativeObject {

    static public final ImGuiInputTextCallbackData NULL = ImGuiInputTextCallbackData.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiInputTextCallbackData(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiInputTextCallbackData native_new() {
        return new ImGuiInputTextCallbackData((byte) 0, (char) 0);
    }

    public int get_BufSize() {
        return 0;
    }

    public void set_BufSize(int BufSize) {
    }

    public boolean get_BufDirty() {
        return false;
    }

    public void set_BufDirty(boolean BufDirty) {
    }

    public int get_BufTextLen() {
        return 0;
    }

    public void set_BufTextLen(int BufTextLen) {
    }

    public ImGuiInputTextFlags get_Flags() {
        return null;
    }

    public void set_Flags(ImGuiInputTextFlags Flags) {
    }
}
