/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package imgui;

import imgui.idl.IDLBase;

public class ImVec4 extends IDLBase {

    public final static ImVec4 NULL = createInstance();

    public static ImVec4 TMP_1 = new ImVec4();

    public static ImVec4 TMP_2 = new ImVec4();

    public static ImVec4 TMP_3 = new ImVec4();

    public static ImVec4 TMP_4 = new ImVec4();

    public static ImVec4 TMP_INTERNAL_1 = new ImVec4();

    public static ImVec4 TMP_INTERNAL_2 = new ImVec4();

    public static ImVec4 createInstance() {
        return new ImVec4((byte) 0, (char) 0);
    }

    private ImVec4(byte v, char c) {
    }

    public ImVec4() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    public ImVec4 set(float x, float y, float z, float w) {
        set_x(x);
        set_y(y);
        set_z(z);
        set_w(w);
        return this;
    }

    public ImVec4 set(ImVec4 vec) {
        float x = vec.get_x();
        float y = vec.get_y();
        float z = vec.get_z();
        float w = vec.get_w();
        set_x(x);
        set_y(y);
        set_z(z);
        set_w(w);
        return this;
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new ImVec4();
    */
    public static native long internal_native_create();

    public ImVec4(float x, float y, float z, float w) {
        long addr = internal_native_create_float_float_float_float(x, y, z, w);
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new ImVec4((float)x, (float)y, (float)z, (float)w);
    */
    public static native long internal_native_create_float_float_float_float(float x, float y, float z, float w);

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      ImVec4* nativeObject = (ImVec4*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public ImVec4 copy(ImVec4 value) {
        internal_native_copy(native_address, value.native_address);
        return this;
    }

    /*
      [-JNI;-NATIVE]
      ImVec4* nativeObject = (ImVec4*)this_addr;
      return (jlong)&(*nativeObject = *((ImVec4* )value_addr));
    */
    public static native long internal_native_copy(long this_addr, long value_addr);

    public float get_x() {
        return internal_native_get_x(native_address);
    }

    /*
      [-JNI;-NATIVE]
      ImVec4* nativeObject = (ImVec4*)this_addr;
      return nativeObject->x;
    */
    public static native float internal_native_get_x(long this_addr);

    public void set_x(float x) {
        internal_native_set_x(native_address, x);
    }

    /*
      [-JNI;-NATIVE]
      ImVec4* nativeObject = (ImVec4*)this_addr;
      nativeObject->x = x;
    */
    public static native void internal_native_set_x(long this_addr, float x);

    public float get_y() {
        return internal_native_get_y(native_address);
    }

    /*
      [-JNI;-NATIVE]
      ImVec4* nativeObject = (ImVec4*)this_addr;
      return nativeObject->y;
    */
    public static native float internal_native_get_y(long this_addr);

    public void set_y(float y) {
        internal_native_set_y(native_address, y);
    }

    /*
      [-JNI;-NATIVE]
      ImVec4* nativeObject = (ImVec4*)this_addr;
      nativeObject->y = y;
    */
    public static native void internal_native_set_y(long this_addr, float y);

    public float get_z() {
        return internal_native_get_z(native_address);
    }

    /*
      [-JNI;-NATIVE]
      ImVec4* nativeObject = (ImVec4*)this_addr;
      return nativeObject->z;
    */
    public static native float internal_native_get_z(long this_addr);

    public void set_z(float z) {
        internal_native_set_z(native_address, z);
    }

    /*
      [-JNI;-NATIVE]
      ImVec4* nativeObject = (ImVec4*)this_addr;
      nativeObject->z = z;
    */
    public static native void internal_native_set_z(long this_addr, float z);

    public float get_w() {
        return internal_native_get_w(native_address);
    }

    /*
      [-JNI;-NATIVE]
      ImVec4* nativeObject = (ImVec4*)this_addr;
      return nativeObject->w;
    */
    public static native float internal_native_get_w(long this_addr);

    public void set_w(float w) {
        internal_native_set_w(native_address, w);
    }

    /*
      [-JNI;-NATIVE]
      ImVec4* nativeObject = (ImVec4*)this_addr;
      nativeObject->w = w;
    */
    public static native void internal_native_set_w(long this_addr, float w);
}
