/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public class ImVectorImGuiWindowPtr extends NativeObject {

    static public final ImVectorImGuiWindowPtr NULL = ImVectorImGuiWindowPtr.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImVectorImGuiWindowPtr(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImVectorImGuiWindowPtr native_new() {
        return new ImVectorImGuiWindowPtr((byte) 0, (char) 0);
    }

    public int size() {
        return 0;
    }

    public ImGuiWindow getData(int index) {
        return null;
    }

    public NativeObject get_Data() {
        return null;
    }
}
