/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package imgui;

import imgui.idl.IDLBase;

public class ImVec2 extends IDLBase {

    public final static ImVec2 NULL = native_new();

    public static ImVec2 TMP_1 = new ImVec2();

    public static ImVec2 TMP_2 = new ImVec2();

    public static ImVec2 TMP_3 = new ImVec2();

    public static ImVec2 TMP_4 = new ImVec2();

    public static ImVec2 native_new() {
        return new ImVec2((byte) 0, (char) 0);
    }

    private ImVec2(byte v, char c) {
    }

    public ImVec2() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    public ImVec2 set(float x, float y) {
        set_x(x);
        set_y(y);
        return this;
    }

    public ImVec2 set(ImVec2 vec) {
        float x = vec.get_x();
        float y = vec.get_y();
        set_x(x);
        set_y(y);
        return this;
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new ImVec2();
    */
    public static native long internal_native_create();

    public ImVec2(float x, float y) {
        long addr = internal_native_create_float_float(x, y);
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new ImVec2((float)x, (float)y);
    */
    public static native long internal_native_create_float_float(float x, float y);

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      ImVec2* nativeObject = (ImVec2*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public float get_x() {
        return internal_native_get_x(native_address);
    }

    /*
      [-JNI;-NATIVE]
      ImVec2* nativeObject = (ImVec2*)this_addr;
      return nativeObject->x;
    */
    public static native float internal_native_get_x(long this_addr);

    public void set_x(float x) {
        internal_native_set_x(native_address, x);
    }

    /*
      [-JNI;-NATIVE]
      ImVec2* nativeObject = (ImVec2*)this_addr;
      nativeObject->x = x;
    */
    public static native void internal_native_set_x(long this_addr, float x);

    public float get_y() {
        return internal_native_get_y(native_address);
    }

    /*
      [-JNI;-NATIVE]
      ImVec2* nativeObject = (ImVec2*)this_addr;
      return nativeObject->y;
    */
    public static native float internal_native_get_y(long this_addr);

    public void set_y(float y) {
        internal_native_set_y(native_address, y);
    }

    /*
      [-JNI;-NATIVE]
      ImVec2* nativeObject = (ImVec2*)this_addr;
      nativeObject->y = y;
    */
    public static native void internal_native_set_y(long this_addr, float y);
}
