/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.idl.IDLBase;

public class ImVectorImGuiWindowStackData extends IDLBase {

    private ImGuiWindowStackData ImGuiWindowStackData_TEMP_GEN_0;

    private IDLBase IDLBase_TEMP_GEN_0;

    static public final ImVectorImGuiWindowStackData NULL = ImVectorImGuiWindowStackData.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImVectorImGuiWindowStackData(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImVectorImGuiWindowStackData native_new() {
        return new ImVectorImGuiWindowStackData((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
ImVectorImGuiWindowStackData* nativeObject = (ImVectorImGuiWindowStackData*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public int size() {
        return internal_native_size(native_address);
    }

    /*[-JNI;-NATIVE]
ImVectorImGuiWindowStackData* nativeObject = (ImVectorImGuiWindowStackData*)this_addr;
return nativeObject->size();
*/
    public static native int internal_native_size(long this_addr);

    public ImGuiWindowStackData getData(int index) {
        long addr = internal_native_getData_addr(native_address, index);
        if (addr == 0)
            return ImGuiWindowStackData.NULL;
        if (ImGuiWindowStackData_TEMP_GEN_0 == null)
            ImGuiWindowStackData_TEMP_GEN_0 = ImGuiWindowStackData.native_new();
        ImGuiWindowStackData_TEMP_GEN_0.internal_reset(addr, false);
        return ImGuiWindowStackData_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ImVectorImGuiWindowStackData* nativeObject = (ImVectorImGuiWindowStackData*)this_addr;
return (jlong)&(*nativeObject)[(int)index];
*/
    public static native long internal_native_getData_addr(long this_addr, int index);

    public IDLBase get_Data() {
        long addr = internal_native_get_Data_addr(native_address);
        if (addr == 0)
            return IDLBase.NULL;
        if (IDLBase_TEMP_GEN_0 == null)
            IDLBase_TEMP_GEN_0 = IDLBase.native_new();
        IDLBase_TEMP_GEN_0.internal_reset(addr, false);
        return IDLBase_TEMP_GEN_0;
    }

    /*[-JNI;-NATIVE]
ImVectorImGuiWindowStackData* nativeObject = (ImVectorImGuiWindowStackData*)this_addr;
return (jlong)nativeObject->Data;
*/
    public static native long internal_native_get_Data_addr(long this_addr);
}
