/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public class ImVectorImTextureRect extends NativeObject {

    static public final ImVectorImTextureRect NULL = ImVectorImTextureRect.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImVectorImTextureRect(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImVectorImTextureRect native_new() {
        return new ImVectorImTextureRect((byte) 0, (char) 0);
    }

    public int size() {
        return 0;
    }

    public ImTextureRect getData(int index) {
        return null;
    }

    public NativeObject get_Data() {
        return null;
    }
}
