/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package imgui.extension.textedit;

import java.util.Map;
import java.util.HashMap;
import com.github.xpenatan.jParser.idl.IDLEnum;

public enum PaletteId implements IDLEnum<PaletteId> {

    CUSTOM(0), Dark(Dark_NATIVE()), Light(Light_NATIVE()), Mariana(Mariana_NATIVE()), RetroBlue(RetroBlue_NATIVE());

    private int value;

    private PaletteId(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public PaletteId setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public PaletteId getCustom() {
        return CUSTOM;
    }

    public static final Map<Integer, PaletteId> MAP = new HashMap<>();

    static {
        for (PaletteId value : values()) {
            if (value != CUSTOM) {
                MAP.put(value.value, value);
            }
        }
    }

    /*[-JNI;-NATIVE]
return (jlong)PaletteId::Dark;
*/
    private static native int Dark_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)PaletteId::Light;
*/
    private static native int Light_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)PaletteId::Mariana;
*/
    private static native int Mariana_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)PaletteId::RetroBlue;
*/
    private static native int RetroBlue_NATIVE();
}
