/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.extension.textedit;

import com.github.xpenatan.jParser.api.NativeObject;
import imgui.ImVec2;
import com.github.xpenatan.jparser.runtime.helper.NativeString;
import com.github.xpenatan.jparser.runtime.helper.NativeIntArray;

public class TextEditor extends NativeObject {

    static public final TextEditor NULL = TextEditor.native_new();

    public TextEditor() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected TextEditor(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static TextEditor native_new() {
        return new TextEditor((byte) 0, (char) 0);
    }

    public void SetReadOnlyEnabled(boolean aValue) {
    }

    public boolean IsReadOnlyEnabled() {
        return false;
    }

    public void SetAutoIndentEnabled(boolean aValue) {
    }

    public boolean IsAutoIndentEnabled() {
        return false;
    }

    public void SetShowWhitespacesEnabled(boolean aValue) {
    }

    public boolean IsShowWhitespacesEnabled() {
        return false;
    }

    public void SetShowLineNumbersEnabled(boolean aValue) {
    }

    public boolean IsShowLineNumbersEnabled() {
        return false;
    }

    public void SetShortTabsEnabled(boolean aValue) {
    }

    public boolean IsShortTabsEnabled() {
        return false;
    }

    public int GetLineCount() {
        return 0;
    }

    public void SetPalette(PaletteId aValue) {
    }

    public PaletteId GetPalette() {
        return null;
    }

    public void SetLanguageDefinition(LanguageDefinitionId aValue) {
    }

    public LanguageDefinitionId GetLanguageDefinition() {
        return null;
    }

    public NativeString GetLanguageDefinitionName() {
        return null;
    }

    public void SetTabSize(int aValue) {
    }

    public int GetTabSize() {
        return 0;
    }

    public void SetLineSpacing(float aValue) {
    }

    public float GetLineSpacing() {
        return 0;
    }

    public static void SetDefaultPalette(PaletteId aValue) {
    }

    public static PaletteId GetDefaultPalette() {
        return null;
    }

    public void SelectAll() {
    }

    public void SelectLine(int aLine) {
    }

    public void SelectRegion(int aStartLine, int aStartChar, int aEndLine, int aEndChar) {
    }

    public void SelectNextOccurrenceOf(String aText, int aTextSize, boolean aCaseSensitive) {
    }

    public void SelectNextOccurrenceOf(String aText, int aTextSize) {
    }

    public void SelectAllOccurrencesOf(String aText, int aTextSize, boolean aCaseSensitive) {
    }

    public void SelectAllOccurrencesOf(String aText, int aTextSize) {
    }

    public boolean AnyCursorHasSelection() {
        return false;
    }

    public boolean AllCursorsHaveSelection() {
        return false;
    }

    public void ClearExtraCursors() {
    }

    public void ClearSelections() {
    }

    public void SetCursorPosition(int aLine, int aCharIndex) {
    }

    public void GetCursorPosition(NativeIntArray outLine, NativeIntArray outColumn) {
    }

    public int GetFirstVisibleLine() {
        return 0;
    }

    public int GetLastVisibleLine() {
        return 0;
    }

    public void SetViewAtLine(int aLine, SetViewAtLineMode aMode) {
    }

    public void Copy() {
    }

    public void Cut() {
    }

    public void Paste() {
    }

    public void Undo(int aSteps) {
    }

    public void Undo() {
    }

    public void Redo(int aSteps) {
    }

    public void Redo() {
    }

    public boolean CanUndo() {
        return false;
    }

    public boolean CanRedo() {
        return false;
    }

    public int GetUndoIndex() {
        return 0;
    }

    public void SetText(String aText) {
    }

    public NativeString GetText() {
        return null;
    }

    public void Render(String aTitle, boolean aParentIsFocused, ImVec2 aSize, boolean aBorder) {
    }

    public void Render(String aTitle, boolean aParentIsFocused, ImVec2 aSize) {
    }

    public void Render(String aTitle, boolean aParentIsFocused) {
    }

    public void Render(String aTitle) {
    }
}
