/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.extension.textedit.natives;

import imgui.extension.textedit.*;

final public class JNI_PaletteId {

    static native public int Dark_NATIVE();

    static native public int Light_NATIVE();

    static native public int Mariana_NATIVE();

    static native public int RetroBlue_NATIVE();
}
